In [10]:
# ============================================
# [1] 라이브러리 & DB 설정
# ============================================
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text
import urllib.parse
from IPython.display import display

# PostgreSQL 접속 정보
DB_CONFIG = {
    "host": "localhost",
    "port": 5432,
    "dbname": "postgres",
    "user": "postgres",
    "password": "",
}

def get_engine(config=DB_CONFIG):
    user = config["user"]
    password = urllib.parse.quote_plus(config["password"])
    host = config["host"]
    port = config["port"]
    dbname = config["dbname"]
    conn_str = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{dbname}"
    print("[INFO] DB 연결:", conn_str)
    return create_engine(conn_str)

engine = get_engine()


# ============================================
# [2] Vision1 / Vision2 머신로그 로딩
#      - c.테이블의 dayornight 컬럼 그대로 가져오기
#      - 교대 경계 시간대 제외
# ============================================
query_vision1 = text("""
    SELECT
        end_day,
        time,
        contents,
        dayornight,
        'Vision1'::text AS station
    FROM d1_machine_log."Vision1_machine_log"
    ORDER BY end_day, time;
""")

query_vision2 = text("""
    SELECT
        end_day,
        time,
        contents,
        dayornight,
        'Vision2'::text AS station
    FROM d1_machine_log."Vision2_machine_log"
    ORDER BY end_day, time;
""")

df_v1 = pd.read_sql(query_vision1, engine)
df_v2 = pd.read_sql(query_vision2, engine)

df = pd.concat([df_v1, df_v2], ignore_index=True)

# ---------- 교대 경계 시간(08:20~08:30, 20:20~20:30) 제거 ----------
df["time_secs"] = pd.to_timedelta(df["time"].astype(str)).dt.total_seconds()

start_0820 = 8 * 3600 + 20 * 60   # 08:20:00
end_0830   = 8 * 3600 + 30 * 60   # 08:30:00
start_2020 = 20 * 3600 + 20 * 60  # 20:20:00
end_2030   = 20 * 3600 + 30 * 60  # 20:30:00

mask_shift = ~(
    ((df["time_secs"] >= start_0820) & (df["time_secs"] <= end_0830)) |
    ((df["time_secs"] >= start_2020) & (df["time_secs"] <= end_2030))
)
df = df[mask_shift].copy()

df = df.sort_values(["station", "end_day", "time"]).reset_index(drop=True)

print("[INFO] 필터 적용 후 데이터 크기:", df.shape)
display(df.head())


# ============================================
# [3] from_row 선택 로직
#   - 'MES 바코드 공정 불량' 연속 5회 이상 → 그 구간의 첫 행만 사용
#   - 'MES 바코드 조회 완료' 나오기 전까지 추가 구간은 모두 무시
#   - 조회 완료가 나오면 다시 리셋
# ============================================
df["is_mes_ng"] = df["contents"].str.contains("MES 바코드 공정 불량", na=False)
df["is_done"]   = df["contents"].str.contains("MES 바코드 조회 완료", na=False)

def mark_mes_start_rows(group: pd.DataFrame) -> pd.DataFrame:
    group = group.sort_values("time").copy()
    n = len(group)
    group["is_from_row"] = False

    used_before_done = False  # 조회 완료 나오기 전 재검 run 방지

    i = 0
    while i < n:

        # 조회 완료 나오면 다시 run 허용
        if group["is_done"].iloc[i]:
            used_before_done = False
            i += 1
            continue

        # 연속 MES NG run 탐색
        if group["is_mes_ng"].iloc[i]:

            run_start = i
            j = i + 1
            while j < n and group["is_mes_ng"].iloc[j]:
                j += 1
            run_end = j - 1
            run_len = run_end - run_start + 1

            if run_len >= 5 and not used_before_done:
                group.loc[group.index[run_start], "is_from_row"] = True
                used_before_done = True

            i = j
        else:
            i += 1

    return group


groups = []
for (_, _), g in df.groupby(["station", "end_day"], sort=False):
    groups.append(mark_mes_start_rows(g))

df = pd.concat(groups, ignore_index=True)

from_rows = df[df["is_from_row"]].copy()

if from_rows.empty:
    print("[INFO] from_row 없음")
    result = pd.DataFrame()
else:
    print("[INFO] from_rows 개수:", len(from_rows))

    from_rows = from_rows.sort_values(["station", "end_day", "time"]).copy()
    from_rows = from_rows[
        ["end_day", "station", "dayornight", "time", "contents"]
    ]
    from_rows = from_rows.rename(columns={
        "time": "from_time",
        "contents": "from_contents",
    })


# ============================================
# [4] 이후 첫 번째 'MES 바코드 조회 완료' 행 찾기
# ============================================
done_rows = df[df["is_done"]].copy()
done_rows = done_rows.sort_values(["station", "end_day", "time"])[
    ["end_day", "station", "time", "contents"]
]
done_rows = done_rows.rename(columns={
    "time": "to_time",
    "contents": "to_contents",
})

def time_to_seconds(s: pd.Series) -> pd.Series:
    return pd.to_timedelta(s.astype(str)).dt.total_seconds()

from_rows["from_key"] = time_to_seconds(from_rows["from_time"])
done_rows["to_key"]   = time_to_seconds(done_rows["to_time"])

merged_list = []

done_group = {
    (st, day): g.sort_values("to_key").reset_index(drop=True)
    for (st, day), g in done_rows.groupby(["station", "end_day"])
}

for (st, day), g_from in from_rows.groupby(["station", "end_day"]):

    g_from = g_from.sort_values("from_key").reset_index(drop=True)
    g_done = done_group.get((st, day))

    if g_done is None or g_done.empty:
        continue

    keys_done = g_done["to_key"].to_numpy()
    keys_from = g_from["from_key"].to_numpy()

    idx = np.searchsorted(keys_done, keys_from, side="left")
    mask = idx < len(keys_done)

    if not mask.any():
        continue

    idx_valid = idx[mask]
    g_from_valid = g_from.loc[mask].reset_index(drop=True)
    g_done_valid = g_done.iloc[idx_valid].reset_index(drop=True)

    tmp = pd.concat(
        [
            g_from_valid,
            g_done_valid[["to_time", "to_key", "to_contents"]],
        ],
        axis=1,
    )
    merged_list.append(tmp)

if not merged_list:
    print("[INFO] 매칭 실패")
    result = pd.DataFrame()
else:
    merged = pd.concat(merged_list, ignore_index=True)

    # wasted_time 계산
    merged["wasted_time"] = (merged["to_key"] - merged["from_key"]).abs().round(2)

    # 10분 이상 제외
    merged = merged[merged["wasted_time"] <= 600].copy()

    # hh:mm:ss.ss 포맷 변환
    def secs_to_hhmmss_ss(sec: float) -> str:
        h = int(sec // 3600)
        m = int((sec % 3600) // 60)
        s = sec - h * 3600 - m * 60
        return f"{h:02d}:{m:02d}:{s:05.2f}"

    merged["from_time_str"] = merged["from_key"].map(secs_to_hhmmss_ss)
    merged["to_time_str"]   = merged["to_key"].map(secs_to_hhmmss_ss)

    # 최종 result
    result = merged[[
        "end_day",
        "station",
        "dayornight",
        "from_contents",
        "from_time_str",
        "to_contents",
        "to_time_str",
        "wasted_time",
    ]].copy()

    result = result.rename(columns={
        "from_time_str": "from_time",
        "to_time_str": "to_time",
    })

    result = result.reset_index(drop=True)
    result.insert(0, "id", result.index + 1)


# ============================================
# [5] 결과 출력
# ============================================
print("[INFO] MES 불량 소요 시간 결과:")
display(result)

[INFO] DB 연결: postgresql+psycopg2://postgres:leejangwoo1%21@localhost:5432/postgres
[INFO] 필터 적용 후 데이터 크기: (1349290, 6)

,end_day,time,contents,dayornight,station,time_secs
0,20250930,01:25:28.68,바코드 스캔 신호 수신,night,Vision1,5128.68
1,20250930,01:25:28.88,바코드 수신 - BA1WJ25273504257SJ8T-14F014-AE,night,Vision1,5128.88
2,20250930,01:25:28.96,MES 바코드 조회 완료,night,Vision1,5128.96
3,20250930,01:25:31.78,검사 시작 신호 수신,night,Vision1,5131.78
4,20250930,01:25:33.71,BA1WJ25273504257SJ8T-14F014-AE :: TEST RESULT ...,night,Vision1,5133.71

[INFO] from_rows 개수: 2639
[INFO] MES 불량 소요 시간 결과:

,id,end_day,station,dayornight,from_contents,from_time,to_contents,to_time,wasted_time
0,1,20250930,Vision1,night,MES 바코드 공정 불량 - Error code - 03,01:28:04.02,MES 바코드 조회 완료,01:28:22.14,18.12
1,2,20250930,Vision1,night,MES 바코드 공정 불량 - Error code - 03,01:54:02.97,MES 바코드 조회 완료,01:54:38.67,35.70
2,3,20250930,Vision1,night,MES 바코드 공정 불량 - Error code - 03,02:03:28.65,MES 바코드 조회 완료,02:04:06.60,37.95
3,4,20250930,Vision1,night,MES 바코드 공정 불량 - Error code - 03,02:05:04.75,MES 바코드 조회 완료,02:05:19.97,15.22
4,5,20250930,Vision1,night,MES 바코드 공정 불량 - Error code - 03,02:14:38.61,MES 바코드 조회 완료,02:15:51.12,72.51
...,...,...,...,...,...,...,...,...,...
2594,2595,20251118,Vision2,day,MES 바코드 공정 불량 - Error code - 03,10:58:57.07,MES 바코드 조회 완료,10:59:16.16,19.09
2595,2596,20251118,Vision2,day,MES 바코드 공정 불량 - Error code - 03,10:59:37.15,MES 바코드 조회 완료,11:00:13.05,35.90
2596,2597,20251118,Vision2,day,MES 바코드 공정 불량 - Error code - 03,11:07:41.70,MES 바코드 조회 완료,11:08:07.10,25.40
2597,2598,20251118,Vision2,day,MES 바코드 공정 불량 - Error code - 03,11:13:46.75,MES 바코드 조회 완료,11:15:08.42,81.67
2598,2599,20251118,Vision2,day,MES 바코드 공정 불량 - Error code - 03,11:21:37.56,MES 바코드 조회 완료,11:22:15.11,37.55

In [17]:
# ============================================
# [자동 DROP → CREATE → INSERT] CHAR 타입 버전
# ============================================
from sqlalchemy import text

TABLE_SCHEMA = "d1_machine_log"
TABLE_NAME   = "mes_fail_wasted_time"

# ------------------------------------------------
# 0) DataFrame end_day 를 8자리 문자열로 강제 변환
# ------------------------------------------------
result["end_day"] = (
    result["end_day"]
    .astype(str)
    .str.replace(",", "", regex=False)  # 콤마 제거
    .str.zfill(8)                       # 항상 8자리 유지
)

# ------------------------------------------------
# 1) 기존 테이블 완전 삭제 후 CHAR(8) 타입으로 재생성
# ------------------------------------------------
drop_sql = f"DROP TABLE IF EXISTS {TABLE_SCHEMA}.{TABLE_NAME};"

create_sql = f"""
CREATE TABLE {TABLE_SCHEMA}.{TABLE_NAME} (
    id            INTEGER,
    end_day       CHAR(8),
    station       TEXT,
    dayornight    TEXT,
    from_contents TEXT,
    from_time     TEXT,
    to_contents   TEXT,
    to_time       TEXT,
    wasted_time   NUMERIC(10,2)
);
"""

with engine.begin() as conn:
    conn.execute(text(drop_sql))
    conn.execute(text(create_sql))
    print(f"[INFO] {TABLE_SCHEMA}.{TABLE_NAME} 테이블 DROP 후 CHAR(8) 타입으로 재생성 완료.")


# ------------------------------------------------
# 2) DataFrame → PostgreSQL INSERT
# ------------------------------------------------
result.to_sql(
    TABLE_NAME,
    engine,
    schema=TABLE_SCHEMA,
    if_exists="append",
    index=False
)

print(f"[INFO] {TABLE_SCHEMA}.{TABLE_NAME} 저장 완료 (rows={len(result)})")
display(result.head())

[INFO] d1_machine_log.mes_fail_wasted_time 테이블 DROP 후 CHAR(8) 타입으로 재생성 완료.
[INFO] d1_machine_log.mes_fail_wasted_time 저장 완료 (rows=2599)

,id,end_day,station,dayornight,from_contents,from_time,to_contents,to_time,wasted_time
0,1,20250930,Vision1,night,MES 바코드 공정 불량 - Error code - 03,01:28:04.02,MES 바코드 조회 완료,01:28:22.14,18.12
1,2,20250930,Vision1,night,MES 바코드 공정 불량 - Error code - 03,01:54:02.97,MES 바코드 조회 완료,01:54:38.67,35.70
2,3,20250930,Vision1,night,MES 바코드 공정 불량 - Error code - 03,02:03:28.65,MES 바코드 조회 완료,02:04:06.60,37.95
3,4,20250930,Vision1,night,MES 바코드 공정 불량 - Error code - 03,02:05:04.75,MES 바코드 조회 완료,02:05:19.97,15.22
4,5,20250930,Vision1,night,MES 바코드 공정 불량 - Error code - 03,02:14:38.61,MES 바코드 조회 완료,02:15:51.12,72.51