In [28]:
# ============================================
# [1] 라이브러리 임포트 & DB 접속 설정
# ============================================
import pandas as pd
from sqlalchemy import create_engine
import urllib.parse
from IPython.display import display

# PostgreSQL 접속 정보
DB_CONFIG = {
    "host": "localhost",
    "port": 5432,
    "dbname": "postgres",
    "user": "postgres",
    "password": "leejangwoo1!",
}

# 엔진 생성 함수
def get_engine(config=DB_CONFIG):
    user = config["user"]
    password = urllib.parse.quote_plus(config["password"])  # 특수문자 대비 인코딩
    host = config["host"]
    port = config["port"]
    dbname = config["dbname"]

    conn_str = f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{dbname}"
    print("[INFO] Connection String:", conn_str)
    engine = create_engine(conn_str)
    return engine

engine = get_engine()
print("[INFO] PostgreSQL 엔진 생성 완료")

[INFO] Connection String: postgresql+psycopg2://postgres:leejangwoo1%21@localhost:5432/postgres
[INFO] PostgreSQL 엔진 생성 완료

In [29]:
# ============================================
# [2] FAIL 처리된 barcode_information 목록 가져오기
#     스키마: e2_fct_vision_test_ct
#     테이블: fct_test_fail_info
# ============================================

query_fail_barcodes = """
SELECT
    barcode_information
FROM
    e2_fct_vision_test_ct.fct_test_fail_info
WHERE
    barcode_information IS NOT NULL
"""

df_fail = pd.read_sql(query_fail_barcodes, engine)

print("[INFO] FAIL 바코드 개수:", len(df_fail))
display(df_fail.head())

# 이후 3번에서 사용할 FAIL 바코드 리스트(중복 제거)
fail_barcodes = (
    df_fail["barcode_information"]
    .dropna()
    .astype(str)
    .unique()
    .tolist()
)

print("[INFO] FAIL 바코드 unique 개수:", len(fail_barcodes))

[INFO] FAIL 바코드 개수: 5310

              barcode_information
0  BA1WJ25273504256SJ8T-14F014-AE
1  BA1WJ25273503731SJ8T-14F014-AE
2  BA1WJ25273503864SJ8T-14F014-AE
3  BA1WJ25273503901SJ8T-14F014-AE
4  BA1WJ25274500274SJ8T-14F014-AE

[INFO] FAIL 바코드 unique 개수: 4025

In [30]:
# ============================================
# [3] FAIL 바코드 + FCT1~4
#     같은 주/야간(shift) 안에서
#     - 가장 늦은 PASS  (3-4)
#     - 최초로 기록된 FAIL (3-8)
#
#     스키마: a2_fct_vision_testlog_json_processing
#     테이블: fct_vision_testlog_json_processing
# ============================================

if not fail_barcodes:
    print("[WARN] FAIL 바코드가 없어 3번 쿼리를 수행할 수 없습니다.")
else:
    # IN 절에 들어갈 FAIL 바코드 리스트 생성 (SQL 인젝션 방지용 간단 escape)
    barcodes_sql = ",".join(
        "'" + b.replace("'", "''") + "'" for b in fail_barcodes
    )

    # ==============================
    # 3-1 ~ 3-7 : 같은 주/야간 내 마지막 PASS
    # ==============================
    query_shift_pass = f"""
    WITH base AS (
        SELECT
            station,
            end_day,
            end_time,
            barcode_information,
            result,
            -- 날짜+시간 타임스탬프
            to_timestamp(end_day || ' ' || end_time, 'YYYYMMDD HH24:MI:SS') AS end_ts,
            -- 주/야간 구분
            CASE
                WHEN end_time::time >= time '08:30:00'
                 AND end_time::time <= time '20:29:59'
                    THEN 'DAY'
                ELSE 'NIGHT'
            END AS shift_type,
            -- 같은 야간(D-DAY 20:30 ~ D+1 08:29)을 하나로 묶기 위한 기준 날짜(shift_base_date)
            CASE
                -- 주간: D 08:30 ~ D 20:29 → 기준일 = D
                WHEN end_time::time >= time '08:30:00'
                 AND end_time::time <= time '20:29:59'
                    THEN to_date(end_day, 'YYYYMMDD')

                -- 야간 앞부분: D 20:30 ~ 23:59 → 기준일 = D
                WHEN end_time::time >= time '20:30:00'
                    THEN to_date(end_day, 'YYYYMMDD')

                -- 야간 뒷부분: D(실제는 D+1) 00:00 ~ 08:29 → 기준일 = D-1
                ELSE to_date(end_day, 'YYYYMMDD') - INTERVAL '1 day'
            END AS shift_base_date
        FROM
            a2_fct_vision_testlog_json_processing.fct_vision_testlog_json_processing
        WHERE
            station IN ('FCT1', 'FCT2', 'FCT3', 'FCT4')
            AND barcode_information IN ({barcodes_sql})
    ),
    ranked AS (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY
                    station,
                    barcode_information,
                    shift_base_date,
                    shift_type
                ORDER BY
                    end_ts DESC       -- 같은 주/야간 안에서 가장 늦은 시간 순
            ) AS rn
        FROM
            base
    )
    SELECT
        station,
        to_char(shift_base_date, 'YYYYMMDD') AS end_day,  -- D-DAY 기준일
        to_char(end_ts, 'HH24:MI:SS')        AS end_time, -- 가장 늦은 시간
        barcode_information,
        result
    FROM
        ranked
    WHERE
        rn = 1          -- 같은 (station, barcode, 주/야간) 그룹에서 마지막 1개
        AND result = 'PASS'  -- 그 마지막 결과가 PASS인 경우만
    ORDER BY
        end_day ASC,
        end_time ASC;
    """

    df_shift_pass = pd.read_sql(query_shift_pass, engine)

    print("[INFO] 같은 주/야간 내 마지막 결과가 PASS인 행 개수:", len(df_shift_pass))
    display(df_shift_pass.head(50))

    # ---- 3-6, 3-7: station 별로 4개 DataFrame 분리 + 정렬 ----
    sort_cols = ["end_day", "end_time"]

    df_shift_pass_FCT1 = (df_shift_pass[df_shift_pass["station"] == "FCT1"]
                          .sort_values(sort_cols).reset_index(drop=True))
    df_shift_pass_FCT2 = (df_shift_pass[df_shift_pass["station"] == "FCT2"]
                          .sort_values(sort_cols).reset_index(drop=True))
    df_shift_pass_FCT3 = (df_shift_pass[df_shift_pass["station"] == "FCT3"]
                          .sort_values(sort_cols).reset_index(drop=True))
    df_shift_pass_FCT4 = (df_shift_pass[df_shift_pass["station"] == "FCT4"]
                          .sort_values(sort_cols).reset_index(drop=True))

    print("\n[INFO] FCT1 - 같은 주/야간 내 마지막 PASS")
    display(df_shift_pass_FCT1.head(30))

    print("\n[INFO] FCT2 - 같은 주/야간 내 마지막 PASS")
    display(df_shift_pass_FCT2.head(30))

    print("\n[INFO] FCT3 - 같은 주/야간 내 마지막 PASS")
    display(df_shift_pass_FCT3.head(30))

    print("\n[INFO] FCT4 - 같은 주/야간 내 마지막 PASS")
    display(df_shift_pass_FCT4.head(30))


    # ==============================
    # 3-8 : 같은 주/야간 내에서
    #       end_time 기준 "최초 FAIL" 행 추출
    #       [station, end_day, end_time, barcode_information, result]
    # ==============================
    query_first_fail = f"""
    WITH base AS (
        SELECT
            station,
            end_day,
            end_time,
            barcode_information,
            result,
            to_timestamp(end_day || ' ' || end_time, 'YYYYMMDD HH24:MI:SS') AS end_ts,
            CASE
                WHEN end_time::time >= time '08:30:00'
                 AND end_time::time <= time '20:29:59'
                    THEN 'DAY'
                ELSE 'NIGHT'
            END AS shift_type,
            CASE
                WHEN end_time::time >= time '08:30:00'
                 AND end_time::time <= time '20:29:59'
                    THEN to_date(end_day, 'YYYYMMDD')
                WHEN end_time::time >= time '20:30:00'
                    THEN to_date(end_day, 'YYYYMMDD')
                ELSE to_date(end_day, 'YYYYMMDD') - INTERVAL '1 day'
            END AS shift_base_date
        FROM
            a2_fct_vision_testlog_json_processing.fct_vision_testlog_json_processing
        WHERE
            station IN ('FCT1', 'FCT2', 'FCT3', 'FCT4')
            AND barcode_information IN ({barcodes_sql})
    ),
    fail_ranked AS (
        SELECT
            *,
            ROW_NUMBER() OVER (
                PARTITION BY
                    station,
                    barcode_information,
                    shift_base_date,
                    shift_type
                ORDER BY
                    end_ts ASC      -- 같은 주/야간 안에서 가장 이른 시간 순
            ) AS rn
        FROM
            base
        WHERE
            result = 'FAIL'
    )
    SELECT
        station,
        to_char(shift_base_date, 'YYYYMMDD') AS end_day,  -- 기준일(D-DAY)
        to_char(end_ts, 'HH24:MI:SS')        AS end_time, -- 최초 FAIL 시간
        barcode_information,
        result
    FROM
        fail_ranked
    WHERE
        rn = 1
    ORDER BY
        end_day ASC,
        end_time ASC;
    """

    df_first_fail = pd.read_sql(query_first_fail, engine)

    print("\n[INFO] 같은 주/야간 내 최초 FAIL 행 개수:", len(df_first_fail))
    df_first_fail = pd.read_sql(query_first_fail, engine)

    print("\n[INFO] 같은 주/야간 내 최초 FAIL 행 개수:", len(df_first_fail))

    # 3-8 요구 컬럼 순서: [station, end_day, end_time, barcode_information, result]
    df_first_fail = df_first_fail[[
        "station",
        "end_day",
        "end_time",
        "barcode_information",
        "result"
    ]]

    # station별 FCT1~FCT4로 분리
    sort_cols = ["end_day", "end_time"]

    df_first_fail_FCT1 = (df_first_fail[df_first_fail["station"] == "FCT1"]
                          .sort_values(sort_cols)
                          .reset_index(drop=True))

    df_first_fail_FCT2 = (df_first_fail[df_first_fail["station"] == "FCT2"]
                          .sort_values(sort_cols)
                          .reset_index(drop=True))

    df_first_fail_FCT3 = (df_first_fail[df_first_fail["station"] == "FCT3"]
                          .sort_values(sort_cols)
                          .reset_index(drop=True))

    df_first_fail_FCT4 = (df_first_fail[df_first_fail["station"] == "FCT4"]
                          .sort_values(sort_cols)
                          .reset_index(drop=True))

    print("\n[INFO] FCT1 - 같은 주/야간 내 최초 FAIL")
    display(df_first_fail_FCT1.head(30))

    print("\n[INFO] FCT2 - 같은 주/야간 내 최초 FAIL")
    display(df_first_fail_FCT2.head(30))

    print("\n[INFO] FCT3 - 같은 주/야간 내 최초 FAIL")
    display(df_first_fail_FCT3.head(30))

    print("\n[INFO] FCT4 - 같은 주/야간 내 최초 FAIL")
    display(df_first_fail_FCT4.head(30))

[INFO] 같은 주/야간 내 마지막 결과가 PASS인 행 개수: 3669

   station   end_day  end_time              barcode_information result
0     FCT4  20250930  06:35:58   BA1WJ25273504256SJ8T-14F014-AE   PASS
1     FCT3  20250930  06:36:13   BA1WJ25273504258SJ8T-14F014-AE   PASS
2     FCT4  20250930  06:36:33   BA1WJ25273503731SJ8T-14F014-AE   PASS
3     FCT3  20250930  06:36:49   BA1WJ25273503864SJ8T-14F014-AE   PASS
4     FCT4  20250930  06:37:07   BA1WJ25273503892SJ8T-14F014-AE   PASS
5     FCT3  20250930  06:37:24   BA1WJ25273503901SJ8T-14F014-AE   PASS
6     FCT4  20250930  06:37:50   BA1WJ25274500026SJ8T-14F014-AE   PASS
7     FCT3  20250930  06:38:00   BA1WJ25274500030SJ8T-14F014-AE   PASS
8     FCT4  20250930  06:38:26   BA1WJ25274500260SJ8T-14F014-AE   PASS
9     FCT4  20250930  06:39:10   BA1WJ25274500955SJ8T-14F014-AE   PASS
10    FCT3  20250930  06:39:25   BA1WJ25274500964SJ8T-14F014-AE   PASS
11    FCT4  20250930  06:39:50   BA1WJ25274500975SJ8T-14F014-AE   PASS
12    FCT3  20250930  06:40:07   BA1WJ25274500974SJ8T-14F014-AE   PASS
13    FCT4  20250930  06:40:23   BA1WJ25274501122SJ8T-14F014-AE   PASS
14    FCT3  20250930  06:40:42   BA1WJ25274500790SJ8T-14F014-AE   PASS
15    FCT4  20250930  06:40:58   BA1WJ25274500729SJ8T-14F014-AE   PASS
16    FCT3  20250930  06:41:17   BA1WJ25274500737SJ8T-14F014-AE   PASS
17    FCT4  20250930  06:41:32   BA1WJ25274501226SJ8T-14F014-AE   PASS
18    FCT3  20250930  06:42:23   BA1WJ25274501383SJ8T-14F014-AE   PASS
19    FCT4  20250930  06:43:51   BA1WJ25274501052SJ8T-14F014-AE   PASS
20    FCT4  20250930  06:44:26   BA1WJ25274501546SJ8T-14F014-AE   PASS
21    FCT3  20250930  06:45:23   BA1WJ25274501407SJ8T-14F014-AE   PASS
22    FCT3  20250930  06:45:57   BA1WJ25274501044SJ8T-14F014-AE   PASS
23    FCT1  20250930  08:21:43  BA1WJ23243500743UPC3T-14F014-AC   PASS
24    FCT2  20250930  08:21:52   BA1WJ23228500512N1WT-14F014-AC   PASS
25    FCT3  20250930  08:22:03   BA1WJ24085501579N1WT-14F014-AC   PASS
26    FCT4  20250930  08:22:10  BA1WJ23243500760UPC3T-14F014-AC   PASS
27    FCT1  20250930  08:23:15   BA1WJ24243500454SJ8T-14F014-AE   PASS
28    FCT2  20250930  08:23:30   BA1WJ24243500234SJ8T-14F014-AE   PASS
29    FCT3  20250930  08:23:30   BA1WJ24243500541SJ8T-14F014-AE   PASS
30    FCT4  20250930  08:23:45   BA1WJ24243500396SJ8T-14F014-AE   PASS
31    FCT4  20251001  00:33:52  BA1WJ25274502846USJ8T-14F014-AE   PASS
32    FCT3  20251001  00:34:13  BA1WJ25274501565USJ8T-14F014-AE   PASS
33    FCT4  20251001  00:34:28  BA1WJ25274503117USJ8T-14F014-AE   PASS
34    FCT4  20251001  00:35:08  BA1WJ25274503034USJ8T-14F014-AE   PASS
35    FCT3  20251001  00:35:17  BA1WJ25274502676USJ8T-14F014-AE   PASS
36    FCT4  20251001  00:35:51  BA1WJ25274502572USJ8T-14F014-AE   PASS
37    FCT4  20251001  00:37:39  BA1WJ25274502770USJ8T-14F014-AE   PASS
38    FCT3  20251001  00:38:00  BA1WJ25274502732USJ8T-14F014-AE   PASS
39    FCT2  20251001  04:33:43  BA1WJ25275500849USJ8T-14F014-AE   PASS
40    FCT4  20251001  05:12:00  BA1WJ25274502393USJ8T-14F014-AE   PASS
41    FCT3  20251001  05:12:19  BA1WJ25274502360USJ8T-14F014-AE   PASS
42    FCT4  20251001  05:12:42  BA1WJ25274502297USJ8T-14F014-AE   PASS
43    FCT3  20251001  05:13:01  BA1WJ25274502505USJ8T-14F014-AE   PASS
44    FCT4  20251001  05:13:22  BA1WJ25274503138USJ8T-14F014-AE   PASS
45    FCT3  20251001  05:13:35  BA1WJ25274502953USJ8T-14F014-AE   PASS
46    FCT4  20251001  05:13:57  BA1WJ25275500262USJ8T-14F014-AE   PASS
47    FCT3  20251001  05:14:16  BA1WJ25275500124USJ8T-14F014-AE   PASS
48    FCT4  20251001  05:14:39  BA1WJ25275500265USJ8T-14F014-AE   PASS
49    FCT3  20251001  05:14:57  BA1WJ25275500249USJ8T-14F014-AE   PASS

[INFO] FCT1 - 같은 주/야간 내 마지막 PASS

   station   end_day  end_time              barcode_information result
0     FCT1  20250930  08:21:43  BA1WJ23243500743UPC3T-14F014-AC   PASS
1     FCT1  20250930  08:23:15   BA1WJ24243500454SJ8T-14F014-AE   PASS
2     FCT1  20251001  08:21:54  BA1WJ23243500743UPC3T-14F014-AC   PASS
3     FCT1  20251001  08:23:26   BA1WJ24243500454SJ8T-14F014-AE   PASS
4     FCT1  20251001  20:27:06  BA1WJ23243500743UPC3T-14F014-AC   PASS
5     FCT1  20251001  20:28:42   BA1WJ24243500454SJ8T-14F014-AE   PASS
6     FCT1  20251002  03:31:14  BA1WJ25275501127USJ8T-14F014-AE   PASS
7     FCT1  20251002  03:31:59  BA1WJ25275500750USJ8T-14F014-AE   PASS
8     FCT1  20251002  03:32:35  BA1WJ25275501040USJ8T-14F014-AE   PASS
9     FCT1  20251002  03:33:31  BA1WJ25274500565USJ8T-14F014-AE   PASS
10    FCT1  20251002  20:21:58  BA1WJ23243500743UPC3T-14F014-AC   PASS
11    FCT1  20251002  20:23:20   BA1WJ24243500454SJ8T-14F014-AE   PASS
12    FCT1  20251009  08:20:37  BA1WJ23243500743UPC3T-14F014-AC   PASS
13    FCT1  20251009  08:22:08   BA1WJ24243500454SJ8T-14F014-AE   PASS
14    FCT1  20251010  00:16:56  BA1WJ25283500166UPC3T-14F014-AC   PASS
15    FCT1  20251010  01:49:37  BA1WJ25284500487UPC3T-14F014-AC   PASS
16    FCT1  20251010  01:52:06  BA1WJ25284500491UPC3T-14F014-AC   PASS
17    FCT1  20251010  02:41:09  BA1WJ25284500850UPC3T-14F014-AC   PASS
18    FCT1  20251010  02:44:15  BA1WJ25284500852UPC3T-14F014-AC   PASS
19    FCT1  20251010  04:16:02  BA1WJ25284501506UPC3T-14F014-AC   PASS
20    FCT1  20251010  05:25:24  BA1WJ25283500674UPC3T-14F014-AC   PASS
21    FCT1  20251010  05:32:02  BA1WJ25283500512UPC3T-14F014-AC   PASS
22    FCT1  20251010  07:21:34   BA1WJ25284500925PC3T-14F014-AC   PASS
23    FCT1  20251010  15:00:13   BA1WJ25283500905PC3T-14F014-AC   PASS
24    FCT1  20251010  15:46:41   BA1WJ25283500836PC3T-14F014-AC   PASS
25    FCT1  20251010  17:48:15   BA1WJ25283501089PC3T-14F014-AC   PASS
26    FCT1  20251010  17:55:46   BA1WJ25283501055PC3T-14F014-AC   PASS
27    FCT1  20251010  18:00:39   BA1WJ25283500009PC3T-14F014-AC   PASS
28    FCT1  20251010  18:16:01   BA1WJ25283502158PC3T-14F014-AC   PASS
29    FCT1  20251010  19:22:42   BA1WJ25283502620PC3T-14F014-AC   PASS

[INFO] FCT2 - 같은 주/야간 내 마지막 PASS

   station   end_day  end_time              barcode_information result
0     FCT2  20250930  08:21:52   BA1WJ23228500512N1WT-14F014-AC   PASS
1     FCT2  20250930  08:23:30   BA1WJ24243500234SJ8T-14F014-AE   PASS
2     FCT2  20251001  04:33:43  BA1WJ25275500849USJ8T-14F014-AE   PASS
3     FCT2  20251001  08:22:04   BA1WJ23228500512N1WT-14F014-AC   PASS
4     FCT2  20251001  08:23:48   BA1WJ24243500234SJ8T-14F014-AE   PASS
5     FCT2  20251001  20:27:15   BA1WJ23228500512N1WT-14F014-AC   PASS
6     FCT2  20251001  20:28:53   BA1WJ24243500234SJ8T-14F014-AE   PASS
7     FCT2  20251002  03:13:15  BA1WJ25275500719USJ8T-14F014-AE   PASS
8     FCT2  20251002  03:31:07  BA1WJ25274500553USJ8T-14F014-AE   PASS
9     FCT2  20251002  03:31:44  BA1WJ25274500451USJ8T-14F014-AE   PASS
10    FCT2  20251002  03:32:25  BA1WJ25275500752USJ8T-14F014-AE   PASS
11    FCT2  20251002  03:33:12  BA1WJ25275500745USJ8T-14F014-AE   PASS
12    FCT2  20251002  03:33:53  BA1WJ25275500478USJ8T-14F014-AE   PASS
13    FCT2  20251002  17:50:29  BA1WJ25275505795USJ8T-14F014-AE   PASS
14    FCT2  20251002  20:22:00   BA1WJ23228500512N1WT-14F014-AC   PASS
15    FCT2  20251002  20:23:38   BA1WJ24243500234SJ8T-14F014-AE   PASS
16    FCT2  20251009  08:20:47   BA1WJ23228500512N1WT-14F014-AC   PASS
17    FCT2  20251009  08:22:25   BA1WJ24243500234SJ8T-14F014-AE   PASS
18    FCT2  20251010  01:24:58  BA1WJ25284500128UPC3T-14F014-AC   PASS
19    FCT2  20251010  01:46:41  BA1WJ25284500300UPC3T-14F014-AC   PASS
20    FCT2  20251010  02:16:12  BA1WJ25284500648UPC3T-14F014-AC   PASS
21    FCT2  20251010  03:08:53  BA1WJ25284500014UPC3T-14F014-AC   PASS
22    FCT2  20251010  03:47:37  BA1WJ25284501193UPC3T-14F014-AC   PASS
23    FCT2  20251010  03:50:13  BA1WJ25284501197UPC3T-14F014-AC   PASS
24    FCT2  20251010  04:18:54  BA1WJ25284501545UPC3T-14F014-AC   PASS
25    FCT2  20251010  04:20:23  BA1WJ25284501539UPC3T-14F014-AC   PASS
26    FCT2  20251010  04:24:30  BA1WJ25284501608UPC3T-14F014-AC   PASS
27    FCT2  20251010  04:28:38  BA1WJ25284501620UPC3T-14F014-AC   PASS
28    FCT2  20251010  04:30:45  BA1WJ25284501647UPC3T-14F014-AC   PASS
29    FCT2  20251010  05:48:22  BA1WJ25283500749UPC3T-14F014-AC   PASS

[INFO] FCT3 - 같은 주/야간 내 마지막 PASS

   station   end_day  end_time              barcode_information result
0     FCT3  20250930  06:36:13   BA1WJ25273504258SJ8T-14F014-AE   PASS
1     FCT3  20250930  06:36:49   BA1WJ25273503864SJ8T-14F014-AE   PASS
2     FCT3  20250930  06:37:24   BA1WJ25273503901SJ8T-14F014-AE   PASS
3     FCT3  20250930  06:38:00   BA1WJ25274500030SJ8T-14F014-AE   PASS
4     FCT3  20250930  06:39:25   BA1WJ25274500964SJ8T-14F014-AE   PASS
5     FCT3  20250930  06:40:07   BA1WJ25274500974SJ8T-14F014-AE   PASS
6     FCT3  20250930  06:40:42   BA1WJ25274500790SJ8T-14F014-AE   PASS
7     FCT3  20250930  06:41:17   BA1WJ25274500737SJ8T-14F014-AE   PASS
8     FCT3  20250930  06:42:23   BA1WJ25274501383SJ8T-14F014-AE   PASS
9     FCT3  20250930  06:45:23   BA1WJ25274501407SJ8T-14F014-AE   PASS
10    FCT3  20250930  06:45:57   BA1WJ25274501044SJ8T-14F014-AE   PASS
11    FCT3  20250930  08:22:03   BA1WJ24085501579N1WT-14F014-AC   PASS
12    FCT3  20250930  08:23:30   BA1WJ24243500541SJ8T-14F014-AE   PASS
13    FCT3  20251001  00:34:13  BA1WJ25274501565USJ8T-14F014-AE   PASS
14    FCT3  20251001  00:35:17  BA1WJ25274502676USJ8T-14F014-AE   PASS
15    FCT3  20251001  00:38:00  BA1WJ25274502732USJ8T-14F014-AE   PASS
16    FCT3  20251001  05:12:19  BA1WJ25274502360USJ8T-14F014-AE   PASS
17    FCT3  20251001  05:13:01  BA1WJ25274502505USJ8T-14F014-AE   PASS
18    FCT3  20251001  05:13:35  BA1WJ25274502953USJ8T-14F014-AE   PASS
19    FCT3  20251001  05:14:16  BA1WJ25275500124USJ8T-14F014-AE   PASS
20    FCT3  20251001  05:14:57  BA1WJ25275500249USJ8T-14F014-AE   PASS
21    FCT3  20251001  05:15:33  BA1WJ25275500041USJ8T-14F014-AE   PASS
22    FCT3  20251001  05:16:10  BA1WJ25275500596USJ8T-14F014-AE   PASS
23    FCT3  20251001  05:16:44  BA1WJ25275500683USJ8T-14F014-AE   PASS
24    FCT3  20251001  05:17:20  BA1WJ25275500226USJ8T-14F014-AE   PASS
25    FCT3  20251001  06:38:02  BA1WJ25275501515USJ8T-14F014-AE   PASS
26    FCT3  20251001  06:38:42  BA1WJ25275501120USJ8T-14F014-AE   PASS
27    FCT3  20251001  06:39:17  BA1WJ25275500769USJ8T-14F014-AE   PASS
28    FCT3  20251001  06:39:51  BA1WJ25275500770USJ8T-14F014-AE   PASS
29    FCT3  20251001  08:21:56   BA1WJ24085501579N1WT-14F014-AC   PASS

[INFO] FCT4 - 같은 주/야간 내 마지막 PASS

   station   end_day  end_time              barcode_information result
0     FCT4  20250930  06:35:58   BA1WJ25273504256SJ8T-14F014-AE   PASS
1     FCT4  20250930  06:36:33   BA1WJ25273503731SJ8T-14F014-AE   PASS
2     FCT4  20250930  06:37:07   BA1WJ25273503892SJ8T-14F014-AE   PASS
3     FCT4  20250930  06:37:50   BA1WJ25274500026SJ8T-14F014-AE   PASS
4     FCT4  20250930  06:38:26   BA1WJ25274500260SJ8T-14F014-AE   PASS
5     FCT4  20250930  06:39:10   BA1WJ25274500955SJ8T-14F014-AE   PASS
6     FCT4  20250930  06:39:50   BA1WJ25274500975SJ8T-14F014-AE   PASS
7     FCT4  20250930  06:40:23   BA1WJ25274501122SJ8T-14F014-AE   PASS
8     FCT4  20250930  06:40:58   BA1WJ25274500729SJ8T-14F014-AE   PASS
9     FCT4  20250930  06:41:32   BA1WJ25274501226SJ8T-14F014-AE   PASS
10    FCT4  20250930  06:43:51   BA1WJ25274501052SJ8T-14F014-AE   PASS
11    FCT4  20250930  06:44:26   BA1WJ25274501546SJ8T-14F014-AE   PASS
12    FCT4  20250930  08:22:10  BA1WJ23243500760UPC3T-14F014-AC   PASS
13    FCT4  20250930  08:23:45   BA1WJ24243500396SJ8T-14F014-AE   PASS
14    FCT4  20251001  00:33:52  BA1WJ25274502846USJ8T-14F014-AE   PASS
15    FCT4  20251001  00:34:28  BA1WJ25274503117USJ8T-14F014-AE   PASS
16    FCT4  20251001  00:35:08  BA1WJ25274503034USJ8T-14F014-AE   PASS
17    FCT4  20251001  00:35:51  BA1WJ25274502572USJ8T-14F014-AE   PASS
18    FCT4  20251001  00:37:39  BA1WJ25274502770USJ8T-14F014-AE   PASS
19    FCT4  20251001  05:12:00  BA1WJ25274502393USJ8T-14F014-AE   PASS
20    FCT4  20251001  05:12:42  BA1WJ25274502297USJ8T-14F014-AE   PASS
21    FCT4  20251001  05:13:22  BA1WJ25274503138USJ8T-14F014-AE   PASS
22    FCT4  20251001  05:13:57  BA1WJ25275500262USJ8T-14F014-AE   PASS
23    FCT4  20251001  05:14:39  BA1WJ25275500265USJ8T-14F014-AE   PASS
24    FCT4  20251001  05:15:47  BA1WJ25274502126USJ8T-14F014-AE   PASS
25    FCT4  20251001  05:16:22  BA1WJ25275500689USJ8T-14F014-AE   PASS
26    FCT4  20251001  05:17:00  BA1WJ25275500390USJ8T-14F014-AE   PASS
27    FCT4  20251001  06:38:13  BA1WJ25275501509USJ8T-14F014-AE   PASS
28    FCT4  20251001  06:38:56  BA1WJ25275501102USJ8T-14F014-AE   PASS
29    FCT4  20251001  06:39:37  BA1WJ25275500484USJ8T-14F014-AE   PASS

[INFO] 같은 주/야간 내 최초 FAIL 행 개수: 4398

[INFO] 같은 주/야간 내 최초 FAIL 행 개수: 4398

[INFO] FCT1 - 같은 주/야간 내 최초 FAIL

   station   end_day  end_time             barcode_information result
0     FCT1  20250930  01:24:59  BA1WJ25273504256SJ8T-14F014-AE   FAIL
1     FCT1  20250930  01:41:41  BA1WJ25273503731SJ8T-14F014-AE   FAIL
2     FCT1  20250930  02:10:12  BA1WJ25273503864SJ8T-14F014-AE   FAIL
3     FCT1  20250930  02:13:46  BA1WJ25273503901SJ8T-14F014-AE   FAIL
4     FCT1  20250930  02:38:19  BA1WJ25274500274SJ8T-14F014-AE   FAIL
5     FCT1  20250930  02:44:48  BA1WJ25274500403SJ8T-14F014-AE   FAIL
6     FCT1  20250930  02:49:29  BA1WJ25274500417SJ8T-14F014-AE   FAIL
7     FCT1  20250930  03:04:35  BA1WJ25274500062SJ8T-14F014-AE   FAIL
8     FCT1  20250930  03:10:11  BA1WJ25274500072SJ8T-14F014-AE   FAIL
9     FCT1  20250930  03:21:35  BA1WJ25273504838SJ8T-14F014-AE   FAIL
10    FCT1  20250930  03:26:32  BA1WJ25274500026SJ8T-14F014-AE   FAIL
11    FCT1  20250930  03:29:53  BA1WJ25274500030SJ8T-14F014-AE   FAIL
12    FCT1  20250930  03:39:57  BA1WJ25274500260SJ8T-14F014-AE   FAIL
13    FCT1  20250930  03:41:14  BA1WJ25274500256SJ8T-14F014-AE   FAIL
14    FCT1  20250930  03:50:21  BA1WJ25274500790SJ8T-14F014-AE   FAIL
15    FCT1  20250930  04:08:28  BA1WJ25274500955SJ8T-14F014-AE   FAIL
16    FCT1  20250930  04:10:07  BA1WJ25274500964SJ8T-14F014-AE   FAIL
17    FCT1  20250930  04:11:13  BA1WJ25274500975SJ8T-14F014-AE   FAIL
18    FCT1  20250930  04:11:34  BA1WJ25274500974SJ8T-14F014-AE   FAIL
19    FCT1  20250930  04:32:27  BA1WJ25274501122SJ8T-14F014-AE   FAIL
20    FCT1  20250930  04:37:29  BA1WJ25274500729SJ8T-14F014-AE   FAIL
21    FCT1  20250930  04:39:26  BA1WJ25274500737SJ8T-14F014-AE   FAIL
22    FCT1  20250930  05:01:31  BA1WJ25274500874SJ8T-14F014-AE   FAIL
23    FCT1  20250930  05:59:06  BA1WJ25274501407SJ8T-14F014-AE   FAIL
24    FCT1  20250930  06:15:32  BA1WJ25274501517SJ8T-14F014-AE   FAIL
25    FCT1  20250930  06:24:31  BA1WJ25274501546SJ8T-14F014-AE   FAIL
26    FCT1  20250930  06:29:37  BA1WJ25274501044SJ8T-14F014-AE   FAIL
27    FCT1  20250930  06:31:26  BA1WJ25274501052SJ8T-14F014-AE   FAIL
28    FCT1  20250930  06:37:07  BA1WJ25273504101SJ8T-14F014-AE   FAIL
29    FCT1  20250930  06:39:44  BA1WJ25273504121SJ8T-14F014-AE   FAIL

[INFO] FCT2 - 같은 주/야간 내 최초 FAIL

   station   end_day  end_time              barcode_information result
0     FCT2  20250930  01:29:08   BA1WJ25273504258SJ8T-14F014-AE   FAIL
1     FCT2  20250930  01:53:54   BA1WJ25273503945SJ8T-14F014-AE   FAIL
2     FCT2  20250930  02:02:35   BA1WJ25273503994SJ8T-14F014-AE   FAIL
3     FCT2  20250930  02:09:58   BA1WJ25273503865SJ8T-14F014-AE   FAIL
4     FCT2  20250930  02:12:19   BA1WJ25273503892SJ8T-14F014-AE   FAIL
5     FCT2  20250930  02:40:34   BA1WJ25274500281SJ8T-14F014-AE   FAIL
6     FCT2  20250930  02:51:46   BA1WJ25274500466SJ8T-14F014-AE   FAIL
7     FCT2  20250930  02:59:27   BA1WJ25274500548SJ8T-14F014-AE   FAIL
8     FCT2  20250930  04:50:09   BA1WJ25274501226SJ8T-14F014-AE   FAIL
9     FCT2  20250930  05:02:31   BA1WJ25274500871SJ8T-14F014-AE   FAIL
10    FCT2  20250930  05:45:12   BA1WJ25274501437SJ8T-14F014-AE   FAIL
11    FCT2  20250930  05:53:20   BA1WJ25274501383SJ8T-14F014-AE   FAIL
12    FCT2  20250930  05:53:49   BA1WJ25274501382SJ8T-14F014-AE   FAIL
13    FCT2  20250930  06:11:02   BA1WJ25274501503SJ8T-14F014-AE   FAIL
14    FCT2  20250930  06:17:15   BA1WJ25274501526SJ8T-14F014-AE   FAIL
15    FCT2  20250930  06:24:54   BA1WJ25274501545SJ8T-14F014-AE   FAIL
16    FCT2  20250930  06:45:22   BA1WJ25273504132SJ8T-14F014-AE   FAIL
17    FCT2  20250930  07:23:51   BA1WJ25273504369SJ8T-14F014-AE   FAIL
18    FCT2  20250930  08:22:36  BA1WJ23243500555UPC3T-14F014-AC   FAIL
19    FCT2  20250930  08:24:02   BA1WJ24068500088SJ8T-14F014-AC   FAIL
20    FCT2  20251001  00:48:39  BA1WJ25274500330USJ8T-14F014-AE   FAIL
21    FCT2  20251001  01:02:00  BA1WJ25274502472USJ8T-14F014-AE   FAIL
22    FCT2  20251001  01:11:57  BA1WJ25274502496USJ8T-14F014-AE   FAIL
23    FCT2  20251001  01:59:16  BA1WJ25274502174USJ8T-14F014-AE   FAIL
24    FCT2  20251001  02:00:23  BA1WJ25274502170USJ8T-14F014-AE   FAIL
25    FCT2  20251001  02:08:10  BA1WJ25274502117USJ8T-14F014-AE   FAIL
26    FCT2  20251001  02:23:36  BA1WJ25275500007USJ8T-14F014-AE   FAIL
27    FCT2  20251001  02:56:43  BA1WJ25275500084USJ8T-14F014-AE   FAIL
28    FCT2  20251001  03:03:33  BA1WJ25275500252USJ8T-14F014-AE   FAIL
29    FCT2  20251001  03:04:46  BA1WJ25275500248USJ8T-14F014-AE   FAIL

[INFO] FCT3 - 같은 주/야간 내 최초 FAIL

   station   end_day  end_time              barcode_information result
0     FCT3  20250930  02:09:53   BA1WJ25273503678SJ8T-14F014-AE   FAIL
1     FCT3  20250930  02:27:13   BA1WJ25273503880SJ8T-14F014-AE   FAIL
2     FCT3  20250930  03:49:31   BA1WJ25274500040SJ8T-14F014-AE   FAIL
3     FCT3  20250930  04:29:04   BA1WJ25273503630SJ8T-14F014-AE   FAIL
4     FCT3  20250930  04:31:28   BA1WJ25273503636SJ8T-14F014-AE   FAIL
5     FCT3  20250930  05:50:44   BA1WJ25273504754SJ8T-14F014-AE   FAIL
6     FCT3  20250930  06:05:47   BA1WJ25274501466SJ8T-14F014-AE   FAIL
7     FCT3  20250930  06:11:39   BA1WJ25273504808SJ8T-14F014-AE   FAIL
8     FCT3  20250930  06:41:46   BA1WJ25274501437SJ8T-14F014-AE   FAIL
9     FCT3  20250930  06:43:56   BA1WJ25274501545SJ8T-14F014-AE   FAIL
10    FCT3  20250930  06:44:41   BA1WJ25274501526SJ8T-14F014-AE   FAIL
11    FCT3  20250930  07:26:52   BA1WJ25274501305SJ8T-14F014-AE   FAIL
12    FCT3  20250930  07:43:27   BA1WJ25273504066SJ8T-14F014-AE   FAIL
13    FCT3  20250930  08:08:11   BA1WJ25273504393SJ8T-14F014-AE   FAIL
14    FCT3  20250930  08:22:36  BA1WJ23243500548UPC3T-14F014-AC   FAIL
15    FCT3  20250930  08:24:01   BA1WJ24068500081SJ8T-14F014-AC   FAIL
16    FCT3  20251001  00:52:05  BA1WJ25274503057USJ8T-14F014-AE   FAIL
17    FCT3  20251001  00:55:53  BA1WJ25274502925USJ8T-14F014-AE   FAIL
18    FCT3  20251001  02:51:52  BA1WJ25275500019USJ8T-14F014-AE   FAIL
19    FCT3  20251001  03:01:42  BA1WJ25274502013USJ8T-14F014-AE   FAIL
20    FCT3  20251001  03:06:44  BA1WJ25274502039USJ8T-14F014-AE   FAIL
21    FCT3  20251001  04:01:55  BA1WJ25275500663USJ8T-14F014-AE   FAIL
22    FCT3  20251001  05:11:32  BA1WJ25275500827USJ8T-14F014-AE   FAIL
23    FCT3  20251001  05:26:05  BA1WJ25275500500USJ8T-14F014-AE   FAIL
24    FCT3  20251001  06:31:13  BA1WJ25275501212USJ8T-14F014-AE   FAIL
25    FCT3  20251001  07:07:17  BA1WJ25275501722USJ8T-14F014-AE   FAIL
26    FCT3  20251001  07:38:05  BA1WJ25275501795USJ8T-14F014-AE   FAIL
27    FCT3  20251001  07:57:49  BA1WJ25275502071USJ8T-14F014-AE   FAIL
28    FCT3  20251001  08:08:47  BA1WJ25275502063USJ8T-14F014-AE   FAIL
29    FCT3  20251001  11:18:43  BA1WJ25274501184USJ8T-14F014-AE   FAIL

[INFO] FCT4 - 같은 주/야간 내 최초 FAIL

   station   end_day  end_time              barcode_information result
0     FCT4  20250930  01:41:08   BA1WJ25273504199SJ8T-14F014-AE   FAIL
1     FCT4  20250930  01:52:49   BA1WJ25273503746SJ8T-14F014-AE   FAIL
2     FCT4  20250930  02:16:04   BA1WJ25273503972SJ8T-14F014-AE   FAIL
3     FCT4  20250930  04:00:23   BA1WJ25274500524SJ8T-14F014-AE   FAIL
4     FCT4  20250930  05:54:38   BA1WJ25274501410SJ8T-14F014-AE   FAIL
5     FCT4  20250930  06:00:28   BA1WJ25274501455SJ8T-14F014-AE   FAIL
6     FCT4  20250930  06:00:58   BA1WJ25274501453SJ8T-14F014-AE   FAIL
7     FCT4  20250930  06:44:44   BA1WJ25274501466SJ8T-14F014-AE   FAIL
8     FCT4  20250930  06:45:27   BA1WJ25274501382SJ8T-14F014-AE   FAIL
9     FCT4  20250930  07:14:06   BA1WJ25274500659SJ8T-14F014-AE   FAIL
10    FCT4  20250930  07:40:36   BA1WJ25273504061SJ8T-14F014-AE   FAIL
11    FCT4  20250930  08:12:20   BA1WJ25273504430SJ8T-14F014-AE   FAIL
12    FCT4  20250930  08:15:08   BA1WJ25273504434SJ8T-14F014-AE   FAIL
13    FCT4  20250930  08:22:50  BA1WJ23243500750UPC3T-14F014-AC   FAIL
14    FCT4  20250930  08:24:24   BA1WJ24068500124SJ8T-14F014-AC   FAIL
15    FCT4  20251001  00:49:10  BA1WJ25274503052USJ8T-14F014-AE   FAIL
16    FCT4  20251001  04:14:53  BA1WJ25275500805USJ8T-14F014-AE   FAIL
17    FCT4  20251001  05:15:05  BA1WJ25275500006USJ8T-14F014-AE   FAIL
18    FCT4  20251001  07:21:12  BA1WJ25275501612USJ8T-14F014-AE   FAIL
19    FCT4  20251001  07:21:37  BA1WJ25275501611USJ8T-14F014-AE   FAIL
20    FCT4  20251001  07:22:07  BA1WJ25275501609USJ8T-14F014-AE   FAIL
21    FCT4  20251001  07:27:04  BA1WJ25275501474USJ8T-14F014-AE   FAIL
22    FCT4  20251001  08:09:41  BA1WJ25275502060USJ8T-14F014-AE   FAIL
23    FCT4  20251001  08:18:22  BA1WJ25275501417USJ8T-14F014-AE   FAIL
24    FCT4  20251001  08:34:05   BA1WJ25273504652SJ8T-14F014-AE   FAIL
25    FCT4  20251001  08:51:58   BA1WJ25273504600SJ8T-14F014-AE   FAIL
26    FCT4  20251001  10:01:43  BA1WJ25274500966USJ8T-14F014-AE   FAIL
27    FCT4  20251001  12:46:00  BA1WJ25274500085USJ8T-14F014-AE   FAIL
28    FCT4  20251001  13:08:23  BA1WJ25274500092USJ8T-14F014-AE   FAIL
29    FCT4  20251001  13:16:25  BA1WJ25274500262USJ8T-14F014-AE   FAIL

In [31]:
# ============================================
# [4] FCT1~4 + PASS 데이터 조회
#     스키마: a2_fct_vision_testlog_json_processing
#     테이블: fct_vision_testlog_json_processing
# ============================================

query_pass_details = """
SELECT
    station,
    end_day,
    end_time,
    barcode_information,
    result
FROM
    a2_fct_vision_testlog_json_processing.fct_vision_testlog_json_processing
WHERE
    station IN ('FCT1', 'FCT2', 'FCT3', 'FCT4')
    AND result = 'PASS'
ORDER BY
    end_day ASC,
    end_time ASC
"""

df_pass_details = pd.read_sql(query_pass_details, engine)

print("[INFO] FCT1~4 + PASS 행 개수:", len(df_pass_details))
display(df_pass_details.head(50))

# ---- 4-4: station 별로 4개 DataFrame 분리 ----
df_pass_FCT1 = df_pass_details[df_pass_details["station"] == "FCT1"].copy()
df_pass_FCT2 = df_pass_details[df_pass_details["station"] == "FCT2"].copy()
df_pass_FCT3 = df_pass_details[df_pass_details["station"] == "FCT3"].copy()
df_pass_FCT4 = df_pass_details[df_pass_details["station"] == "FCT4"].copy()

print("\n[INFO] PASS 상세 - FCT1 행 개수:", len(df_pass_FCT1))
display(df_pass_FCT1.head(30))

print("\n[INFO] PASS 상세 - FCT2 행 개수:", len(df_pass_FCT2))
display(df_pass_FCT2.head(30))

print("\n[INFO] PASS 상세 - FCT3 행 개수:", len(df_pass_FCT3))
display(df_pass_FCT3.head(30))

print("\n[INFO] PASS 상세 - FCT4 행 개수:", len(df_pass_FCT4))
display(df_pass_FCT4.head(30))

[INFO] FCT1~4 + PASS 행 개수: 176225

   station   end_day  end_time             barcode_information result
0     FCT2  20251001  01:25:03  BA1WJ25273504257SJ8T-14F014-AE   PASS
1     FCT4  20251001  01:25:26  BA1WJ25273504236SJ8T-14F014-AE   PASS
2     FCT1  20251001  01:25:40  BA1WJ25273504255SJ8T-14F014-AE   PASS
3     FCT3  20251001  01:25:40  BA1WJ25273504235SJ8T-14F014-AE   PASS
4     FCT2  20251001  01:25:50  BA1WJ25273504254SJ8T-14F014-AE   PASS
5     FCT4  20251001  01:26:06  BA1WJ25273504234SJ8T-14F014-AE   PASS
6     FCT1  20251001  01:26:22  BA1WJ25273504253SJ8T-14F014-AE   PASS
7     FCT3  20251001  01:26:23  BA1WJ25273504233SJ8T-14F014-AE   PASS
8     FCT2  20251001  01:26:30  BA1WJ25273504252SJ8T-14F014-AE   PASS
9     FCT4  20251001  01:26:41  BA1WJ25273504232SJ8T-14F014-AE   PASS
10    FCT1  20251001  01:26:57  BA1WJ25273504251SJ8T-14F014-AE   PASS
11    FCT3  20251001  01:26:59  BA1WJ25273504231SJ8T-14F014-AE   PASS
12    FCT2  20251001  01:27:13  BA1WJ25273504265SJ8T-14F014-AE   PASS
13    FCT4  20251001  01:27:17  BA1WJ25273504230SJ8T-14F014-AE   PASS
14    FCT1  20251001  01:27:33  BA1WJ25273504263SJ8T-14F014-AE   PASS
15    FCT3  20251001  01:27:41  BA1WJ25273504243SJ8T-14F014-AE   PASS
16    FCT2  20251001  01:27:50  BA1WJ25273504262SJ8T-14F014-AE   PASS
17    FCT4  20251001  01:27:52  BA1WJ25273504242SJ8T-14F014-AE   PASS
18    FCT1  20251001  01:28:09  BA1WJ25273504261SJ8T-14F014-AE   PASS
19    FCT3  20251001  01:28:17  BA1WJ25273504241SJ8T-14F014-AE   PASS
20    FCT2  20251001  01:28:26  BA1WJ25273504260SJ8T-14F014-AE   PASS
21    FCT4  20251001  01:28:35  BA1WJ25273504240SJ8T-14F014-AE   PASS
22    FCT1  20251001  01:28:43  BA1WJ25273504259SJ8T-14F014-AE   PASS
23    FCT3  20251001  01:28:59  BA1WJ25273504239SJ8T-14F014-AE   PASS
24    FCT4  20251001  01:29:09  BA1WJ25273504238SJ8T-14F014-AE   PASS
25    FCT1  20251001  01:29:24  BA1WJ25273504272SJ8T-14F014-AE   PASS
26    FCT3  20251001  01:29:40  BA1WJ25273504237SJ8T-14F014-AE   PASS
27    FCT2  20251001  01:29:44  BA1WJ25273504271SJ8T-14F014-AE   PASS
28    FCT4  20251001  01:29:49  BA1WJ25273504250SJ8T-14F014-AE   PASS
29    FCT1  20251001  01:30:02  BA1WJ25273504270SJ8T-14F014-AE   PASS
30    FCT3  20251001  01:30:15  BA1WJ25273504249SJ8T-14F014-AE   PASS
31    FCT2  20251001  01:30:20  BA1WJ25273504269SJ8T-14F014-AE   PASS
32    FCT4  20251001  01:30:30  BA1WJ25273504248SJ8T-14F014-AE   PASS
33    FCT1  20251001  01:30:36  BA1WJ25273504268SJ8T-14F014-AE   PASS
34    FCT3  20251001  01:30:53  BA1WJ25273504247SJ8T-14F014-AE   PASS
35    FCT2  20251001  01:30:58  BA1WJ25273504267SJ8T-14F014-AE   PASS
36    FCT4  20251001  01:31:06  BA1WJ25273504246SJ8T-14F014-AE   PASS
37    FCT1  20251001  01:31:13  BA1WJ25273504266SJ8T-14F014-AE   PASS
38    FCT3  20251001  01:31:29  BA1WJ25273504245SJ8T-14F014-AE   PASS
39    FCT2  20251001  01:31:34  BA1WJ25273503771SJ8T-14F014-AE   PASS
40    FCT4  20251001  01:31:47  BA1WJ25273504244SJ8T-14F014-AE   PASS
41    FCT1  20251001  01:31:50  BA1WJ25273503770SJ8T-14F014-AE   PASS
42    FCT3  20251001  01:32:05  BA1WJ25273504214SJ8T-14F014-AE   PASS
43    FCT2  20251001  01:32:11  BA1WJ25273503769SJ8T-14F014-AE   PASS
44    FCT4  20251001  01:32:21  BA1WJ25273504213SJ8T-14F014-AE   PASS
45    FCT1  20251001  01:32:25  BA1WJ25273503768SJ8T-14F014-AE   PASS
46    FCT3  20251001  01:32:42  BA1WJ25273504212SJ8T-14F014-AE   PASS
47    FCT2  20251001  01:32:47  BA1WJ25273503767SJ8T-14F014-AE   PASS
48    FCT4  20251001  01:32:54  BA1WJ25273504211SJ8T-14F014-AE   PASS
49    FCT1  20251001  01:33:02  BA1WJ25273503766SJ8T-14F014-AE   PASS

[INFO] PASS 상세 - FCT1 행 개수: 44770

    station   end_day  end_time             barcode_information result
2      FCT1  20251001  01:25:40  BA1WJ25273504255SJ8T-14F014-AE   PASS
6      FCT1  20251001  01:26:22  BA1WJ25273504253SJ8T-14F014-AE   PASS
10     FCT1  20251001  01:26:57  BA1WJ25273504251SJ8T-14F014-AE   PASS
14     FCT1  20251001  01:27:33  BA1WJ25273504263SJ8T-14F014-AE   PASS
18     FCT1  20251001  01:28:09  BA1WJ25273504261SJ8T-14F014-AE   PASS
22     FCT1  20251001  01:28:43  BA1WJ25273504259SJ8T-14F014-AE   PASS
25     FCT1  20251001  01:29:24  BA1WJ25273504272SJ8T-14F014-AE   PASS
29     FCT1  20251001  01:30:02  BA1WJ25273504270SJ8T-14F014-AE   PASS
33     FCT1  20251001  01:30:36  BA1WJ25273504268SJ8T-14F014-AE   PASS
37     FCT1  20251001  01:31:13  BA1WJ25273504266SJ8T-14F014-AE   PASS
41     FCT1  20251001  01:31:50  BA1WJ25273503770SJ8T-14F014-AE   PASS
45     FCT1  20251001  01:32:25  BA1WJ25273503768SJ8T-14F014-AE   PASS
49     FCT1  20251001  01:33:02  BA1WJ25273503766SJ8T-14F014-AE   PASS
53     FCT1  20251001  01:33:38  BA1WJ25273503778SJ8T-14F014-AE   PASS
56     FCT1  20251001  01:34:16  BA1WJ25273503776SJ8T-14F014-AE   PASS
60     FCT1  20251001  01:35:01  BA1WJ25273503774SJ8T-14F014-AE   PASS
64     FCT1  20251001  01:35:37  BA1WJ25273503772SJ8T-14F014-AE   PASS
68     FCT1  20251001  01:36:12  BA1WJ25273503784SJ8T-14F014-AE   PASS
72     FCT1  20251001  01:36:48  BA1WJ25273503782SJ8T-14F014-AE   PASS
76     FCT1  20251001  01:37:27  BA1WJ25273503780SJ8T-14F014-AE   PASS
81     FCT1  20251001  01:38:14  BA1WJ25273503729SJ8T-14F014-AE   PASS
85     FCT1  20251001  01:38:51  BA1WJ25273503727SJ8T-14F014-AE   PASS
89     FCT1  20251001  01:39:26  BA1WJ25273503725SJ8T-14F014-AE   PASS
92     FCT1  20251001  01:40:02  BA1WJ25273503723SJ8T-14F014-AE   PASS
97     FCT1  20251001  01:40:41  BA1WJ25273503735SJ8T-14F014-AE   PASS
100    FCT1  20251001  01:41:19  BA1WJ25273503733SJ8T-14F014-AE   PASS
106    FCT1  20251001  01:42:16  BA1WJ25273503730SJ8T-14F014-AE   PASS
109    FCT1  20251001  01:42:57  BA1WJ25273503742SJ8T-14F014-AE   PASS
114    FCT1  20251001  01:43:44  BA1WJ25273503740SJ8T-14F014-AE   PASS
118    FCT1  20251001  01:44:19  BA1WJ25273503738SJ8T-14F014-AE   PASS

[INFO] PASS 상세 - FCT2 행 개수: 36761

    station   end_day  end_time             barcode_information result
0      FCT2  20251001  01:25:03  BA1WJ25273504257SJ8T-14F014-AE   PASS
4      FCT2  20251001  01:25:50  BA1WJ25273504254SJ8T-14F014-AE   PASS
8      FCT2  20251001  01:26:30  BA1WJ25273504252SJ8T-14F014-AE   PASS
12     FCT2  20251001  01:27:13  BA1WJ25273504265SJ8T-14F014-AE   PASS
16     FCT2  20251001  01:27:50  BA1WJ25273504262SJ8T-14F014-AE   PASS
20     FCT2  20251001  01:28:26  BA1WJ25273504260SJ8T-14F014-AE   PASS
27     FCT2  20251001  01:29:44  BA1WJ25273504271SJ8T-14F014-AE   PASS
31     FCT2  20251001  01:30:20  BA1WJ25273504269SJ8T-14F014-AE   PASS
35     FCT2  20251001  01:30:58  BA1WJ25273504267SJ8T-14F014-AE   PASS
39     FCT2  20251001  01:31:34  BA1WJ25273503771SJ8T-14F014-AE   PASS
43     FCT2  20251001  01:32:11  BA1WJ25273503769SJ8T-14F014-AE   PASS
47     FCT2  20251001  01:32:47  BA1WJ25273503767SJ8T-14F014-AE   PASS
51     FCT2  20251001  01:33:24  BA1WJ25273503765SJ8T-14F014-AE   PASS
55     FCT2  20251001  01:34:05  BA1WJ25273503777SJ8T-14F014-AE   PASS
59     FCT2  20251001  01:34:40  BA1WJ25273503775SJ8T-14F014-AE   PASS
63     FCT2  20251001  01:35:15  BA1WJ25273503773SJ8T-14F014-AE   PASS
67     FCT2  20251001  01:35:53  BA1WJ25273503785SJ8T-14F014-AE   PASS
70     FCT2  20251001  01:36:34  BA1WJ25273503783SJ8T-14F014-AE   PASS
74     FCT2  20251001  01:37:09  BA1WJ25273503781SJ8T-14F014-AE   PASS
78     FCT2  20251001  01:37:46  BA1WJ25273503779SJ8T-14F014-AE   PASS
83     FCT2  20251001  01:38:28  BA1WJ25273503728SJ8T-14F014-AE   PASS
87     FCT2  20251001  01:39:09  BA1WJ25273503726SJ8T-14F014-AE   PASS
91     FCT2  20251001  01:39:50  BA1WJ25273503724SJ8T-14F014-AE   PASS
95     FCT2  20251001  01:40:28  BA1WJ25273503736SJ8T-14F014-AE   PASS
99     FCT2  20251001  01:41:04  BA1WJ25273503734SJ8T-14F014-AE   PASS
102    FCT2  20251001  01:41:41  BA1WJ25273503732SJ8T-14F014-AE   PASS
107    FCT2  20251001  01:42:32  BA1WJ25273503743SJ8T-14F014-AE   PASS
111    FCT2  20251001  01:43:09  BA1WJ25273503741SJ8T-14F014-AE   PASS
115    FCT2  20251001  01:43:46  BA1WJ25273503739SJ8T-14F014-AE   PASS
120    FCT2  20251001  01:44:33  BA1WJ25273503737SJ8T-14F014-AE   PASS

[INFO] PASS 상세 - FCT3 행 개수: 47330

    station   end_day  end_time             barcode_information result
3      FCT3  20251001  01:25:40  BA1WJ25273504235SJ8T-14F014-AE   PASS
7      FCT3  20251001  01:26:23  BA1WJ25273504233SJ8T-14F014-AE   PASS
11     FCT3  20251001  01:26:59  BA1WJ25273504231SJ8T-14F014-AE   PASS
15     FCT3  20251001  01:27:41  BA1WJ25273504243SJ8T-14F014-AE   PASS
19     FCT3  20251001  01:28:17  BA1WJ25273504241SJ8T-14F014-AE   PASS
23     FCT3  20251001  01:28:59  BA1WJ25273504239SJ8T-14F014-AE   PASS
26     FCT3  20251001  01:29:40  BA1WJ25273504237SJ8T-14F014-AE   PASS
30     FCT3  20251001  01:30:15  BA1WJ25273504249SJ8T-14F014-AE   PASS
34     FCT3  20251001  01:30:53  BA1WJ25273504247SJ8T-14F014-AE   PASS
38     FCT3  20251001  01:31:29  BA1WJ25273504245SJ8T-14F014-AE   PASS
42     FCT3  20251001  01:32:05  BA1WJ25273504214SJ8T-14F014-AE   PASS
46     FCT3  20251001  01:32:42  BA1WJ25273504212SJ8T-14F014-AE   PASS
50     FCT3  20251001  01:33:23  BA1WJ25273504210SJ8T-14F014-AE   PASS
54     FCT3  20251001  01:33:59  BA1WJ25273504208SJ8T-14F014-AE   PASS
58     FCT3  20251001  01:34:35  BA1WJ25273504220SJ8T-14F014-AE   PASS
62     FCT3  20251001  01:35:09  BA1WJ25273504218SJ8T-14F014-AE   PASS
66     FCT3  20251001  01:35:51  BA1WJ25273504216SJ8T-14F014-AE   PASS
71     FCT3  20251001  01:36:37  BA1WJ25273504229SJ8T-14F014-AE   PASS
75     FCT3  20251001  01:37:12  BA1WJ25273504227SJ8T-14F014-AE   PASS
79     FCT3  20251001  01:37:52  BA1WJ25273504225SJ8T-14F014-AE   PASS
82     FCT3  20251001  01:38:27  BA1WJ25273504223SJ8T-14F014-AE   PASS
86     FCT3  20251001  01:39:01  BA1WJ25273504192SJ8T-14F014-AE   PASS
90     FCT3  20251001  01:39:37  BA1WJ25273504190SJ8T-14F014-AE   PASS
94     FCT3  20251001  01:40:18  BA1WJ25273504188SJ8T-14F014-AE   PASS
98     FCT3  20251001  01:40:53  BA1WJ25273504200SJ8T-14F014-AE   PASS
101    FCT3  20251001  01:41:29  BA1WJ25273504198SJ8T-14F014-AE   PASS
104    FCT3  20251001  01:42:04  BA1WJ25273504196SJ8T-14F014-AE   PASS
108    FCT3  20251001  01:42:40  BA1WJ25273504194SJ8T-14F014-AE   PASS
112    FCT3  20251001  01:43:14  BA1WJ25273504206SJ8T-14F014-AE   PASS
116    FCT3  20251001  01:43:51  BA1WJ25273504204SJ8T-14F014-AE   PASS

[INFO] PASS 상세 - FCT4 행 개수: 47364

    station   end_day  end_time             barcode_information result
1      FCT4  20251001  01:25:26  BA1WJ25273504236SJ8T-14F014-AE   PASS
5      FCT4  20251001  01:26:06  BA1WJ25273504234SJ8T-14F014-AE   PASS
9      FCT4  20251001  01:26:41  BA1WJ25273504232SJ8T-14F014-AE   PASS
13     FCT4  20251001  01:27:17  BA1WJ25273504230SJ8T-14F014-AE   PASS
17     FCT4  20251001  01:27:52  BA1WJ25273504242SJ8T-14F014-AE   PASS
21     FCT4  20251001  01:28:35  BA1WJ25273504240SJ8T-14F014-AE   PASS
24     FCT4  20251001  01:29:09  BA1WJ25273504238SJ8T-14F014-AE   PASS
28     FCT4  20251001  01:29:49  BA1WJ25273504250SJ8T-14F014-AE   PASS
32     FCT4  20251001  01:30:30  BA1WJ25273504248SJ8T-14F014-AE   PASS
36     FCT4  20251001  01:31:06  BA1WJ25273504246SJ8T-14F014-AE   PASS
40     FCT4  20251001  01:31:47  BA1WJ25273504244SJ8T-14F014-AE   PASS
44     FCT4  20251001  01:32:21  BA1WJ25273504213SJ8T-14F014-AE   PASS
48     FCT4  20251001  01:32:54  BA1WJ25273504211SJ8T-14F014-AE   PASS
52     FCT4  20251001  01:33:38  BA1WJ25273504209SJ8T-14F014-AE   PASS
57     FCT4  20251001  01:34:19  BA1WJ25273504222SJ8T-14F014-AE   PASS
61     FCT4  20251001  01:35:02  BA1WJ25273504219SJ8T-14F014-AE   PASS
65     FCT4  20251001  01:35:43  BA1WJ25273504217SJ8T-14F014-AE   PASS
69     FCT4  20251001  01:36:17  BA1WJ25273504215SJ8T-14F014-AE   PASS
73     FCT4  20251001  01:36:52  BA1WJ25273504228SJ8T-14F014-AE   PASS
77     FCT4  20251001  01:37:27  BA1WJ25273504226SJ8T-14F014-AE   PASS
80     FCT4  20251001  01:38:07  BA1WJ25273504224SJ8T-14F014-AE   PASS
84     FCT4  20251001  01:38:46  BA1WJ25273504193SJ8T-14F014-AE   PASS
88     FCT4  20251001  01:39:22  BA1WJ25273504191SJ8T-14F014-AE   PASS
93     FCT4  20251001  01:40:04  BA1WJ25273504189SJ8T-14F014-AE   PASS
96     FCT4  20251001  01:40:39  BA1WJ25273504187SJ8T-14F014-AE   PASS
103    FCT4  20251001  01:41:42  BA1WJ25273504197SJ8T-14F014-AE   PASS
105    FCT4  20251001  01:42:16  BA1WJ25273504195SJ8T-14F014-AE   PASS
110    FCT4  20251001  01:43:00  BA1WJ25273504207SJ8T-14F014-AE   PASS
113    FCT4  20251001  01:43:33  BA1WJ25273504205SJ8T-14F014-AE   PASS
117    FCT4  20251001  01:44:15  BA1WJ25273504203SJ8T-14F014-AE   PASS

In [32]:
# ============================================
# [5] 3-8의 최초 FAIL 앞에
#     같은 station / 같은 주·야간 안의 PASS 최대 30개를
#     끼워 넣어 출력 (FCT1~4 각각)
#
# 5-1: station 동일
# 5-2: FAIL의 시간대가 주간/야간 규칙에 맞는 경우만 사용
# 5-3: FAIL 시간보다 이전 PASS만 사용
# 5-4: 최대 30개 PASS + FAIL 1개를 하나의 블럭으로 구성
# 5-5: 블럭마다 fail_estimation_group = 1,2,3,... 부여
# ============================================

from datetime import datetime, timedelta, time as dtime

# 시간대 경계
DAY_START   = dtime(8, 30, 0)
DAY_END     = dtime(20, 29, 59)
NIGHT1_START = dtime(20, 30, 0)   # D 20:30 ~ 23:59
NIGHT1_END   = dtime(23, 59, 59)
NIGHT2_START = dtime(0, 0, 0)     # D+1 00:00 ~ 08:29
NIGHT2_END   = dtime(8, 29, 59)

def get_shift_interval_from_fail(shift_day_str: str, time_str: str):
    """
    3-8에서 나온 FAIL 1건에 대해:
    - FAIL의 실제 발생 시각(fail_ts_real)
    - 해당 주/야간 근무의 시작/끝(shift_start, shift_end)
    를 계산한다.
    
    shift_day_str: 3-8의 end_day (YYYYMMDD, '근무일' 기준)
    time_str:      3-8의 end_time (HH:MM:SS)
    """
    base_day = datetime.strptime(shift_day_str, "%Y%m%d").date()
    t = datetime.strptime(time_str, "%H:%M:%S").time()

    # 주간: D 08:30 ~ D 20:29
    if DAY_START <= t <= DAY_END:
        real_day = base_day
        fail_ts = datetime.combine(real_day, t)
        shift_start = datetime.combine(real_day, DAY_START)
        shift_end   = datetime.combine(real_day, DAY_END)
        shift_type = "DAY"

    # 야간 앞부분: D 20:30 ~ D 23:59  (실제 날짜 = D)
    elif NIGHT1_START <= t <= NIGHT1_END:
        real_day = base_day
        fail_ts = datetime.combine(real_day, t)
        shift_start = datetime.combine(real_day, NIGHT1_START)
        shift_end   = datetime.combine(real_day + timedelta(days=1), NIGHT2_END)
        shift_type = "NIGHT"

    # 야간 뒷부분: (근무일 D 기준) 00:00 ~ 08:29
    # 실제 날짜는 D+1일
    elif NIGHT2_START <= t <= NIGHT2_END:
        real_day = base_day + timedelta(days=1)
        fail_ts = datetime.combine(real_day, t)
        shift_start = datetime.combine(real_day - timedelta(days=1), NIGHT1_START)
        shift_end   = datetime.combine(real_day, NIGHT2_END)
        shift_type = "NIGHT"

    else:
        # 정의된 시간대에 안 들어가면 제외
        return None, None, None, None

    # 안전하게, FAIL이 근무 시간대 밖이면 제외
    if not (shift_start <= fail_ts <= shift_end):
        return None, None, None, None

    return shift_type, shift_start, shift_end, fail_ts


def build_pass_before_fail_blocks(df_fail_station, df_pass_station, station_name):
    """
    하나의 station(FCT1~4)에 대해:
    - df_fail_station : 3-8 결과 중 해당 station (최초 FAIL들)
    - df_pass_station : 4번에서 만든 PASS 전체 (해당 station)
    
    각 FAIL마다:
      같은 근무(주/야)의 PASS 중, FAIL 이전 시각인 것들 중에서
      최대 30개를 FAIL 위에 붙여서
      [PASS들] + [FAIL] 블럭을 쌓아 반환.
    그리고 각 블럭마다 fail_estimation_group 번호(1,2,3,...)를 부여.
    """
    cols = ["station", "end_day", "end_time", "barcode_information", "result"]

    if df_fail_station.empty:
        print(f"[INFO] {station_name}: 최초 FAIL 데이터가 없습니다.")
        return pd.DataFrame(columns=cols + ["fail_estimation_group"])

    if df_pass_station.empty:
        print(f"[INFO] {station_name}: PASS 데이터가 없습니다.")
        return pd.DataFrame(columns=cols + ["fail_estimation_group"])

    # PASS의 실제 타임스탬프 생성
    dfp = df_pass_station.copy()
    dfp["ts"] = pd.to_datetime(
        dfp["end_day"].astype(str).str.strip() + " " +
        dfp["end_time"].astype(str).str.strip(),
        format="%Y%m%d %H:%M:%S",
        errors="coerce"
    )

    # 변환 실패한 행 제거
    bad_rows = dfp[dfp["ts"].isna()]
    if len(bad_rows) > 0:
        print(f"[WARN] {station_name}: 형식 이상(end_time 오류) {len(bad_rows)}개 제거")
        print(bad_rows[["end_day", "end_time"]].head(10))
        dfp = dfp.dropna(subset=["ts"])

    blocks = []
    group_id = 0  # fail_estimation_group 시작값

    # ========= FAIL 기준 PASS 블록 생성 =========
    for _, row in df_fail_station.iterrows():
        shift_day = row["end_day"]
        fail_time_str = row["end_time"]

        shift_type, shift_start, shift_end, fail_ts = get_shift_interval_from_fail(
            shift_day, fail_time_str
        )

        # 5-2: 근무 시간대 제외
        if shift_type is None:
            continue

        # FAIL 이전 PASS + 같은 시프트 필터링
        mask = (dfp["ts"] >= shift_start) & (dfp["ts"] <= fail_ts)
        pass_in_shift = dfp.loc[mask].sort_values("ts")

        # PASS 최대 30개만 유지
        if pass_in_shift.empty:
            block_pass = pass_in_shift[cols]
        else:
            block_pass = pass_in_shift.tail(30)[cols]

        # FAIL 한 행 구성
        fail_row_df = pd.DataFrame([[row[c] for c in cols]], columns=cols)

        # PASS위 FAIL 결합
        block = pd.concat([block_pass, fail_row_df], ignore_index=True)

        # === 5-5: 이 블럭 전체에 동일 group 번호 부여 ===
        group_id += 1
        block["fail_estimation_group"] = group_id

        blocks.append(block)

    if not blocks:
        print(f"[INFO] {station_name}: 조건에 맞는 블럭이 없습니다.")
        return pd.DataFrame(columns=cols)

    # ==================================================
    # 모든 블럭 결합
    # ==================================================
    df_all = pd.concat(blocks, ignore_index=True)

    # ==================================================
    # FAIL을 그룹의 맨 아래로 보내기 위한 우선순위 컬럼 생성
    # PASS → 0, FAIL → 1
    # ==================================================
    df_all["fail_order"] = df_all["result"].apply(lambda x: 1 if x == "FAIL" else 0)

    # ==================================================
    # 최종 정렬
    #   1) fail_estimation_group 오름차순
    #   2) fail_order 오름차순 (PASS 먼저 → FAIL 마지막)
    #   3) end_day, end_time 오름차순
    # ==================================================
    df_all = df_all.sort_values(
        by=["fail_estimation_group", "fail_order", "end_day", "end_time"],
        ascending=[True, True, True, True]
    ).reset_index(drop=True)

    # 정렬용 컬럼 제거
    df_all = df_all.drop(columns=["fail_order"])

    return df_all

# -------------------------------
# FCT1 ~ FCT4 각각에 대해 실행
# -------------------------------
df_FCT1_PASS_FAIL = build_pass_before_fail_blocks(df_first_fail_FCT1, df_pass_FCT1, "FCT1")
df_FCT2_PASS_FAIL = build_pass_before_fail_blocks(df_first_fail_FCT2, df_pass_FCT2, "FCT2")
df_FCT3_PASS_FAIL = build_pass_before_fail_blocks(df_first_fail_FCT3, df_pass_FCT3, "FCT3")
df_FCT4_PASS_FAIL = build_pass_before_fail_blocks(df_first_fail_FCT4, df_pass_FCT4, "FCT4")

print("\n[INFO] FCT4 예시 (PASS 최대 30개 + FAIL 1개 블럭 구조 + fail_estimation_group)")
display(df_FCT4_PASS_FAIL.head(60))

[WARN] FCT1: 형식 이상(end_time 오류) 1개 제거
       end_day end_time
4784  20251001       id

[INFO] FCT4 예시 (PASS 최대 30개 + FAIL 1개 블럭 구조 + fail_estimation_group)

,station,end_day,end_time,barcode_information,result,fail_estimation_group
0,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,PASS,1
1,FCT4,20251001,01:26:06,BA1WJ25273504234SJ8T-14F014-AE,PASS,1
2,FCT4,20251001,01:26:41,BA1WJ25273504232SJ8T-14F014-AE,PASS,1
3,FCT4,20251001,01:27:17,BA1WJ25273504230SJ8T-14F014-AE,PASS,1
4,FCT4,20251001,01:27:52,BA1WJ25273504242SJ8T-14F014-AE,PASS,1
5,FCT4,20251001,01:28:35,BA1WJ25273504240SJ8T-14F014-AE,PASS,1
6,FCT4,20251001,01:29:09,BA1WJ25273504238SJ8T-14F014-AE,PASS,1
7,FCT4,20251001,01:29:49,BA1WJ25273504250SJ8T-14F014-AE,PASS,1
8,FCT4,20251001,01:30:30,BA1WJ25273504248SJ8T-14F014-AE,PASS,1
9,FCT4,20251001,01:31:06,BA1WJ25273504246SJ8T-14F014-AE,PASS,1
10,FCT4,20251001,01:31:47,BA1WJ25273504244SJ8T-14F014-AE,PASS,1
11,FCT4,20251001,01:32:21,BA1WJ25273504213SJ8T-14F014-AE,PASS,1
12,FCT4,20251001,01:32:54,BA1WJ25273504211SJ8T-14F014-AE,PASS,1
13,FCT4,20251001,01:33:38,BA1WJ25273504209SJ8T-14F014-AE,PASS,1
14,FCT4,20251001,01:34:19,BA1WJ25273504222SJ8T-14F014-AE,PASS,1
15,FCT4,20251001,01:35:02,BA1WJ25273504219SJ8T-14F014-AE,PASS,1
16,FCT4,20251001,01:35:43,BA1WJ25273504217SJ8T-14F014-AE,PASS,1
17,FCT4,20251001,01:36:17,BA1WJ25273504215SJ8T-14F014-AE,PASS,1
18,FCT4,20251001,01:36:52,BA1WJ25273504228SJ8T-14F014-AE,PASS,1
19,FCT4,20251001,01:37:27,BA1WJ25273504226SJ8T-14F014-AE,PASS,1
20,FCT4,20251001,01:38:07,BA1WJ25273504224SJ8T-14F014-AE,PASS,1
21,FCT4,20251001,01:38:46,BA1WJ25273504193SJ8T-14F014-AE,PASS,1
22,FCT4,20251001,01:39:22,BA1WJ25273504191SJ8T-14F014-AE,PASS,1
23,FCT4,20251001,01:40:04,BA1WJ25273504189SJ8T-14F014-AE,PASS,1
24,FCT4,20251001,01:40:39,BA1WJ25273504187SJ8T-14F014-AE,PASS,1
25,FCT4,20250930,01:41:08,BA1WJ25273504199SJ8T-14F014-AE,FAIL,1
26,FCT4,20251001,01:33:38,BA1WJ25273504209SJ8T-14F014-AE,PASS,2
27,FCT4,20251001,01:34:19,BA1WJ25273504222SJ8T-14F014-AE,PASS,2
28,FCT4,20251001,01:35:02,BA1WJ25273504219SJ8T-14F014-AE,PASS,2
29,FCT4,20251001,01:35:43,BA1WJ25273504217SJ8T-14F014-AE,PASS,2
30,FCT4,20251001,01:36:17,BA1WJ25273504215SJ8T-14F014-AE,PASS,2
31,FCT4,20251001,01:36:52,BA1WJ25273504228SJ8T-14F014-AE,PASS,2
32,FCT4,20251001,01:37:27,BA1WJ25273504226SJ8T-14F014-AE,PASS,2
33,FCT4,20251001,01:38:07,BA1WJ25273504224SJ8T-14F014-AE,PASS,2
34,FCT4,20251001,01:38:46,BA1WJ25273504193SJ8T-14F014-AE,PASS,2
35,FCT4,20251001,01:39:22,BA1WJ25273504191SJ8T-14F014-AE,PASS,2
36,FCT4,20251001,01:40:04,BA1WJ25273504189SJ8T-14F014-AE,PASS,2
37,FCT4,20251001,01:40:39,BA1WJ25273504187SJ8T-14F014-AE,PASS,2
38,FCT4,20251001,01:41:42,BA1WJ25273504197SJ8T-14F014-AE,PASS,2
39,FCT4,20251001,01:42:16,BA1WJ25273504195SJ8T-14F014-AE,PASS,2
40,FCT4,20251001,01:43:00,BA1WJ25273504207SJ8T-14F014-AE,PASS,2
41,FCT4,20251001,01:43:33,BA1WJ25273504205SJ8T-14F014-AE,PASS,2
42,FCT4,20251001,01:44:15,BA1WJ25273504203SJ8T-14F014-AE,PASS,2
43,FCT4,20251001,01:44:48,BA1WJ25273504201SJ8T-14F014-AE,PASS,2
44,FCT4,20251001,01:45:28,BA1WJ25273504171SJ8T-14F014-AE,PASS,2
45,FCT4,20251001,01:46:04,BA1WJ25273504169SJ8T-14F014-AE,PASS,2
46,FCT4,20251001,01:46:44,BA1WJ25273504167SJ8T-14F014-AE,PASS,2
47,FCT4,20251001,01:47:19,BA1WJ25273504179SJ8T-14F014-AE,PASS,2
48,FCT4,20251001,01:47:54,BA1WJ25273504177SJ8T-14F014-AE,PASS,2
49,FCT4,20251001,01:48:36,BA1WJ25273504175SJ8T-14F014-AE,PASS,2
50,FCT4,20251001,01:49:11,BA1WJ25273504173SJ8T-14F014-AE,PASS,2
51,FCT4,20251001,01:49:47,BA1WJ25273504185SJ8T-14F014-AE,PASS,2
52,FCT4,20251001,01:50:20,BA1WJ25273504183SJ8T-14F014-AE,PASS,2
53,FCT4,20251001,01:51:01,BA1WJ25273504181SJ8T-14F014-AE,PASS,2
54,FCT4,20251001,01:51:43,BA1WJ25273503750SJ8T-14F014-AE,PASS,2
55,FCT4,20251001,01:52:20,BA1WJ25273503748SJ8T-14F014-AE,PASS,2
56,FCT4,20250930,01:52:49,BA1WJ25273503746SJ8T-14F014-AE,FAIL,2
57,FCT4,20251001,01:57:34,BA1WJ25273503759SJ8T-14F014-AE,PASS,3
58,FCT4,20251001,01:58:16,BA1WJ25273503708SJ8T-14F014-AE,PASS,3
59,FCT4,20251001,01:58:50,BA1WJ25273503706SJ8T-14F014-AE,PASS,3

In [33]:
# ============================================
# [6] 5번 결과에서 FAIL 제외 + remark 추가 (PD / Non-PD)
#
# barcode_information 의 18번째 글자:
#   'J' 또는 'S' → PD
#   그 외 → Non-PD
#
# FCT1~4 별로 출력
# ============================================

def add_remark(df, station_name):
    if df.empty:
        print(f"[INFO] {station_name}: PASS 데이터가 없어서 remark 생성 불가.")
        return df

    result = df.copy()

    # FAIL 제외
    result = result[result["result"] != "FAIL"].reset_index(drop=True)

    # remark 생성
    def classify_remark(barcode):
        if not isinstance(barcode, str) or len(barcode) < 18:
            return "Non-PD"
        ch = barcode[17]   # 18번째 글자 (index 17)
        return "PD" if ch in ("J", "S") else "Non-PD"

    result["remark"] = result["barcode_information"].apply(classify_remark)

    # 출력
    print(f"\n[INFO] {station_name} - FAIL 제외 + remark(PD/Non-PD) 추가 결과")
    display(result.head(50))

    return result


df_FCT1_PASS_PD = add_remark(df_FCT1_PASS_FAIL, "FCT1")
df_FCT2_PASS_PD = add_remark(df_FCT2_PASS_FAIL, "FCT2")
df_FCT3_PASS_PD = add_remark(df_FCT3_PASS_FAIL, "FCT3")
df_FCT4_PASS_PD = add_remark(df_FCT4_PASS_FAIL, "FCT4")

[INFO] FCT1 - FAIL 제외 + remark(PD/Non-PD) 추가 결과

,station,end_day,end_time,barcode_information,result,fail_estimation_group,remark
0,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,2,PD
1,FCT1,20251001,01:26:22,BA1WJ25273504253SJ8T-14F014-AE,PASS,2,PD
2,FCT1,20251001,01:26:57,BA1WJ25273504251SJ8T-14F014-AE,PASS,2,PD
3,FCT1,20251001,01:27:33,BA1WJ25273504263SJ8T-14F014-AE,PASS,2,PD
4,FCT1,20251001,01:28:09,BA1WJ25273504261SJ8T-14F014-AE,PASS,2,PD
5,FCT1,20251001,01:28:43,BA1WJ25273504259SJ8T-14F014-AE,PASS,2,PD
6,FCT1,20251001,01:29:24,BA1WJ25273504272SJ8T-14F014-AE,PASS,2,PD
7,FCT1,20251001,01:30:02,BA1WJ25273504270SJ8T-14F014-AE,PASS,2,PD
8,FCT1,20251001,01:30:36,BA1WJ25273504268SJ8T-14F014-AE,PASS,2,PD
9,FCT1,20251001,01:31:13,BA1WJ25273504266SJ8T-14F014-AE,PASS,2,PD
10,FCT1,20251001,01:31:50,BA1WJ25273503770SJ8T-14F014-AE,PASS,2,PD
11,FCT1,20251001,01:32:25,BA1WJ25273503768SJ8T-14F014-AE,PASS,2,PD
12,FCT1,20251001,01:33:02,BA1WJ25273503766SJ8T-14F014-AE,PASS,2,PD
13,FCT1,20251001,01:33:38,BA1WJ25273503778SJ8T-14F014-AE,PASS,2,PD
14,FCT1,20251001,01:34:16,BA1WJ25273503776SJ8T-14F014-AE,PASS,2,PD
15,FCT1,20251001,01:35:01,BA1WJ25273503774SJ8T-14F014-AE,PASS,2,PD
16,FCT1,20251001,01:35:37,BA1WJ25273503772SJ8T-14F014-AE,PASS,2,PD
17,FCT1,20251001,01:36:12,BA1WJ25273503784SJ8T-14F014-AE,PASS,2,PD
18,FCT1,20251001,01:36:48,BA1WJ25273503782SJ8T-14F014-AE,PASS,2,PD
19,FCT1,20251001,01:37:27,BA1WJ25273503780SJ8T-14F014-AE,PASS,2,PD
20,FCT1,20251001,01:38:14,BA1WJ25273503729SJ8T-14F014-AE,PASS,2,PD
21,FCT1,20251001,01:38:51,BA1WJ25273503727SJ8T-14F014-AE,PASS,2,PD
22,FCT1,20251001,01:39:26,BA1WJ25273503725SJ8T-14F014-AE,PASS,2,PD
23,FCT1,20251001,01:40:02,BA1WJ25273503723SJ8T-14F014-AE,PASS,2,PD
24,FCT1,20251001,01:40:41,BA1WJ25273503735SJ8T-14F014-AE,PASS,2,PD
25,FCT1,20251001,01:41:19,BA1WJ25273503733SJ8T-14F014-AE,PASS,2,PD
26,FCT1,20251001,01:51:56,BA1WJ25273503938SJ8T-14F014-AE,PASS,3,PD
27,FCT1,20251001,01:52:33,BA1WJ25273503936SJ8T-14F014-AE,PASS,3,PD
28,FCT1,20251001,01:53:08,BA1WJ25273503934SJ8T-14F014-AE,PASS,3,PD
29,FCT1,20251001,01:53:49,BA1WJ25273503946SJ8T-14F014-AE,PASS,3,PD
30,FCT1,20251001,01:54:25,BA1WJ25273503944SJ8T-14F014-AE,PASS,3,PD
31,FCT1,20251001,01:55:00,BA1WJ25273503942SJ8T-14F014-AE,PASS,3,PD
32,FCT1,20251001,01:55:40,BA1WJ25273503940SJ8T-14F014-AE,PASS,3,PD
33,FCT1,20251001,01:56:15,BA1WJ25273503952SJ8T-14F014-AE,PASS,3,PD
34,FCT1,20251001,01:56:50,BA1WJ25273503950SJ8T-14F014-AE,PASS,3,PD
35,FCT1,20251001,01:57:27,BA1WJ25273503948SJ8T-14F014-AE,PASS,3,PD
36,FCT1,20251001,01:58:01,BA1WJ25273503981SJ8T-14F014-AE,PASS,3,PD
37,FCT1,20251001,01:58:43,BA1WJ25273503979SJ8T-14F014-AE,PASS,3,PD
38,FCT1,20251001,01:59:18,BA1WJ25273503977SJ8T-14F014-AE,PASS,3,PD
39,FCT1,20251001,01:59:56,BA1WJ25273503975SJ8T-14F014-AE,PASS,3,PD
40,FCT1,20251001,02:00:33,BA1WJ25273503987SJ8T-14F014-AE,PASS,3,PD
41,FCT1,20251001,02:01:13,BA1WJ25273503985SJ8T-14F014-AE,PASS,3,PD
42,FCT1,20251001,02:01:50,BA1WJ25273503983SJ8T-14F014-AE,PASS,3,PD
43,FCT1,20251001,02:02:26,BA1WJ25273503995SJ8T-14F014-AE,PASS,3,PD
44,FCT1,20251001,02:03:02,BA1WJ25273503993SJ8T-14F014-AE,PASS,3,PD
45,FCT1,20251001,02:03:39,BA1WJ25273503991SJ8T-14F014-AE,PASS,3,PD
46,FCT1,20251001,02:04:15,BA1WJ25273503989SJ8T-14F014-AE,PASS,3,PD
47,FCT1,20251001,02:04:50,BA1WJ25273503854SJ8T-14F014-AE,PASS,3,PD
48,FCT1,20251001,02:05:25,BA1WJ25273503852SJ8T-14F014-AE,PASS,3,PD
49,FCT1,20251001,02:06:01,BA1WJ25273503850SJ8T-14F014-AE,PASS,3,PD

[INFO] FCT2 - FAIL 제외 + remark(PD/Non-PD) 추가 결과

,station,end_day,end_time,barcode_information,result,fail_estimation_group,remark
0,FCT2,20251001,01:25:03,BA1WJ25273504257SJ8T-14F014-AE,PASS,1,PD
1,FCT2,20251001,01:25:50,BA1WJ25273504254SJ8T-14F014-AE,PASS,1,PD
2,FCT2,20251001,01:26:30,BA1WJ25273504252SJ8T-14F014-AE,PASS,1,PD
3,FCT2,20251001,01:27:13,BA1WJ25273504265SJ8T-14F014-AE,PASS,1,PD
4,FCT2,20251001,01:27:50,BA1WJ25273504262SJ8T-14F014-AE,PASS,1,PD
5,FCT2,20251001,01:28:26,BA1WJ25273504260SJ8T-14F014-AE,PASS,1,PD
6,FCT2,20251001,01:34:40,BA1WJ25273503775SJ8T-14F014-AE,PASS,2,PD
7,FCT2,20251001,01:35:15,BA1WJ25273503773SJ8T-14F014-AE,PASS,2,PD
8,FCT2,20251001,01:35:53,BA1WJ25273503785SJ8T-14F014-AE,PASS,2,PD
9,FCT2,20251001,01:36:34,BA1WJ25273503783SJ8T-14F014-AE,PASS,2,PD
10,FCT2,20251001,01:37:09,BA1WJ25273503781SJ8T-14F014-AE,PASS,2,PD
11,FCT2,20251001,01:37:46,BA1WJ25273503779SJ8T-14F014-AE,PASS,2,PD
12,FCT2,20251001,01:38:28,BA1WJ25273503728SJ8T-14F014-AE,PASS,2,PD
13,FCT2,20251001,01:39:09,BA1WJ25273503726SJ8T-14F014-AE,PASS,2,PD
14,FCT2,20251001,01:39:50,BA1WJ25273503724SJ8T-14F014-AE,PASS,2,PD
15,FCT2,20251001,01:40:28,BA1WJ25273503736SJ8T-14F014-AE,PASS,2,PD
16,FCT2,20251001,01:41:04,BA1WJ25273503734SJ8T-14F014-AE,PASS,2,PD
17,FCT2,20251001,01:41:41,BA1WJ25273503732SJ8T-14F014-AE,PASS,2,PD
18,FCT2,20251001,01:42:32,BA1WJ25273503743SJ8T-14F014-AE,PASS,2,PD
19,FCT2,20251001,01:43:09,BA1WJ25273503741SJ8T-14F014-AE,PASS,2,PD
20,FCT2,20251001,01:43:46,BA1WJ25273503739SJ8T-14F014-AE,PASS,2,PD
21,FCT2,20251001,01:44:33,BA1WJ25273503737SJ8T-14F014-AE,PASS,2,PD
22,FCT2,20251001,01:45:09,BA1WJ25273503686SJ8T-14F014-AE,PASS,2,PD
23,FCT2,20251001,01:45:47,BA1WJ25273503684SJ8T-14F014-AE,PASS,2,PD
24,FCT2,20251001,01:46:29,BA1WJ25273503682SJ8T-14F014-AE,PASS,2,PD
25,FCT2,20251001,01:47:04,BA1WJ25273503694SJ8T-14F014-AE,PASS,2,PD
26,FCT2,20251001,01:47:40,BA1WJ25273503692SJ8T-14F014-AE,PASS,2,PD
27,FCT2,20251001,01:48:16,BA1WJ25273503690SJ8T-14F014-AE,PASS,2,PD
28,FCT2,20251001,01:48:53,BA1WJ25273503688SJ8T-14F014-AE,PASS,2,PD
29,FCT2,20251001,01:49:35,BA1WJ25273503700SJ8T-14F014-AE,PASS,2,PD
30,FCT2,20251001,01:50:18,BA1WJ25273503698SJ8T-14F014-AE,PASS,2,PD
31,FCT2,20251001,01:50:55,BA1WJ25273503696SJ8T-14F014-AE,PASS,2,PD
32,FCT2,20251001,01:51:31,BA1WJ25273503939SJ8T-14F014-AE,PASS,2,PD
33,FCT2,20251001,01:52:07,BA1WJ25273503937SJ8T-14F014-AE,PASS,2,PD
34,FCT2,20251001,01:52:47,BA1WJ25273503935SJ8T-14F014-AE,PASS,2,PD
35,FCT2,20251001,01:53:25,BA1WJ25273503933SJ8T-14F014-AE,PASS,2,PD
36,FCT2,20251001,01:43:09,BA1WJ25273503741SJ8T-14F014-AE,PASS,3,PD
37,FCT2,20251001,01:43:46,BA1WJ25273503739SJ8T-14F014-AE,PASS,3,PD
38,FCT2,20251001,01:44:33,BA1WJ25273503737SJ8T-14F014-AE,PASS,3,PD
39,FCT2,20251001,01:45:09,BA1WJ25273503686SJ8T-14F014-AE,PASS,3,PD
40,FCT2,20251001,01:45:47,BA1WJ25273503684SJ8T-14F014-AE,PASS,3,PD
41,FCT2,20251001,01:46:29,BA1WJ25273503682SJ8T-14F014-AE,PASS,3,PD
42,FCT2,20251001,01:47:04,BA1WJ25273503694SJ8T-14F014-AE,PASS,3,PD
43,FCT2,20251001,01:47:40,BA1WJ25273503692SJ8T-14F014-AE,PASS,3,PD
44,FCT2,20251001,01:48:16,BA1WJ25273503690SJ8T-14F014-AE,PASS,3,PD
45,FCT2,20251001,01:48:53,BA1WJ25273503688SJ8T-14F014-AE,PASS,3,PD
46,FCT2,20251001,01:49:35,BA1WJ25273503700SJ8T-14F014-AE,PASS,3,PD
47,FCT2,20251001,01:50:18,BA1WJ25273503698SJ8T-14F014-AE,PASS,3,PD
48,FCT2,20251001,01:50:55,BA1WJ25273503696SJ8T-14F014-AE,PASS,3,PD
49,FCT2,20251001,01:51:31,BA1WJ25273503939SJ8T-14F014-AE,PASS,3,PD

[INFO] FCT3 - FAIL 제외 + remark(PD/Non-PD) 추가 결과

,station,end_day,end_time,barcode_information,result,fail_estimation_group,remark
0,FCT3,20251001,01:50:54,BA1WJ25273504182SJ8T-14F014-AE,PASS,1,PD
1,FCT3,20251001,01:51:30,BA1WJ25273504180SJ8T-14F014-AE,PASS,1,PD
2,FCT3,20251001,01:52:06,BA1WJ25273503749SJ8T-14F014-AE,PASS,1,PD
3,FCT3,20251001,01:52:49,BA1WJ25273503747SJ8T-14F014-AE,PASS,1,PD
4,FCT3,20251001,01:53:45,BA1WJ25273503744SJ8T-14F014-AE,PASS,1,PD
5,FCT3,20251001,01:54:19,BA1WJ25273503756SJ8T-14F014-AE,PASS,1,PD
6,FCT3,20251001,01:54:54,BA1WJ25273503754SJ8T-14F014-AE,PASS,1,PD
7,FCT3,20251001,01:55:31,BA1WJ25273503752SJ8T-14F014-AE,PASS,1,PD
8,FCT3,20251001,01:56:11,BA1WJ25273503764SJ8T-14F014-AE,PASS,1,PD
9,FCT3,20251001,01:56:46,BA1WJ25273503762SJ8T-14F014-AE,PASS,1,PD
10,FCT3,20251001,01:57:27,BA1WJ25273503760SJ8T-14F014-AE,PASS,1,PD
11,FCT3,20251001,01:58:01,BA1WJ25273503758SJ8T-14F014-AE,PASS,1,PD
12,FCT3,20251001,01:58:37,BA1WJ25273503707SJ8T-14F014-AE,PASS,1,PD
13,FCT3,20251001,01:59:19,BA1WJ25273503705SJ8T-14F014-AE,PASS,1,PD
14,FCT3,20251001,01:59:54,BA1WJ25273503703SJ8T-14F014-AE,PASS,1,PD
15,FCT3,20251001,02:00:29,BA1WJ25273503715SJ8T-14F014-AE,PASS,1,PD
16,FCT3,20251001,02:01:05,BA1WJ25273503713SJ8T-14F014-AE,PASS,1,PD
17,FCT3,20251001,02:01:40,BA1WJ25273503711SJ8T-14F014-AE,PASS,1,PD
18,FCT3,20251001,02:02:20,BA1WJ25273503709SJ8T-14F014-AE,PASS,1,PD
19,FCT3,20251001,02:02:57,BA1WJ25273503721SJ8T-14F014-AE,PASS,1,PD
20,FCT3,20251001,02:03:43,BA1WJ25273503719SJ8T-14F014-AE,PASS,1,PD
21,FCT3,20251001,02:04:19,BA1WJ25273503717SJ8T-14F014-AE,PASS,1,PD
22,FCT3,20251001,02:04:53,BA1WJ25273503666SJ8T-14F014-AE,PASS,1,PD
23,FCT3,20251001,02:05:30,BA1WJ25273503664SJ8T-14F014-AE,PASS,1,PD
24,FCT3,20251001,02:06:10,BA1WJ25273503662SJ8T-14F014-AE,PASS,1,PD
25,FCT3,20251001,02:06:45,BA1WJ25273503660SJ8T-14F014-AE,PASS,1,PD
26,FCT3,20251001,02:07:26,BA1WJ25273503672SJ8T-14F014-AE,PASS,1,PD
27,FCT3,20251001,02:08:06,BA1WJ25273503670SJ8T-14F014-AE,PASS,1,PD
28,FCT3,20251001,02:08:41,BA1WJ25273503668SJ8T-14F014-AE,PASS,1,PD
29,FCT3,20251001,02:09:23,BA1WJ25273503680SJ8T-14F014-AE,PASS,1,PD
30,FCT3,20251001,02:08:06,BA1WJ25273503670SJ8T-14F014-AE,PASS,2,PD
31,FCT3,20251001,02:08:41,BA1WJ25273503668SJ8T-14F014-AE,PASS,2,PD
32,FCT3,20251001,02:09:23,BA1WJ25273503680SJ8T-14F014-AE,PASS,2,PD
33,FCT3,20251001,02:10:29,BA1WJ25273503676SJ8T-14F014-AE,PASS,2,PD
34,FCT3,20251001,02:11:04,BA1WJ25273503674SJ8T-14F014-AE,PASS,2,PD
35,FCT3,20251001,02:11:45,BA1WJ25273503959SJ8T-14F014-AE,PASS,2,PD
36,FCT3,20251001,02:12:21,BA1WJ25273503957SJ8T-14F014-AE,PASS,2,PD
37,FCT3,20251001,02:12:57,BA1WJ25273503955SJ8T-14F014-AE,PASS,2,PD
38,FCT3,20251001,02:13:32,BA1WJ25273503967SJ8T-14F014-AE,PASS,2,PD
39,FCT3,20251001,02:14:08,BA1WJ25273503965SJ8T-14F014-AE,PASS,2,PD
40,FCT3,20251001,02:14:44,BA1WJ25273503963SJ8T-14F014-AE,PASS,2,PD
41,FCT3,20251001,02:15:21,BA1WJ25273503961SJ8T-14F014-AE,PASS,2,PD
42,FCT3,20251001,02:16:04,BA1WJ25273503973SJ8T-14F014-AE,PASS,2,PD
43,FCT3,20251001,02:16:56,BA1WJ25273503970SJ8T-14F014-AE,PASS,2,PD
44,FCT3,20251001,02:17:30,BA1WJ25273503968SJ8T-14F014-AE,PASS,2,PD
45,FCT3,20251001,02:18:07,BA1WJ25273504001SJ8T-14F014-AE,PASS,2,PD
46,FCT3,20251001,02:18:41,BA1WJ25273503999SJ8T-14F014-AE,PASS,2,PD
47,FCT3,20251001,02:19:22,BA1WJ25273503997SJ8T-14F014-AE,PASS,2,PD
48,FCT3,20251001,02:20:03,BA1WJ25273504009SJ8T-14F014-AE,PASS,2,PD
49,FCT3,20251001,02:20:39,BA1WJ25273504007SJ8T-14F014-AE,PASS,2,PD

[INFO] FCT4 - FAIL 제외 + remark(PD/Non-PD) 추가 결과

,station,end_day,end_time,barcode_information,result,fail_estimation_group,remark
0,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,PASS,1,PD
1,FCT4,20251001,01:26:06,BA1WJ25273504234SJ8T-14F014-AE,PASS,1,PD
2,FCT4,20251001,01:26:41,BA1WJ25273504232SJ8T-14F014-AE,PASS,1,PD
3,FCT4,20251001,01:27:17,BA1WJ25273504230SJ8T-14F014-AE,PASS,1,PD
4,FCT4,20251001,01:27:52,BA1WJ25273504242SJ8T-14F014-AE,PASS,1,PD
5,FCT4,20251001,01:28:35,BA1WJ25273504240SJ8T-14F014-AE,PASS,1,PD
6,FCT4,20251001,01:29:09,BA1WJ25273504238SJ8T-14F014-AE,PASS,1,PD
7,FCT4,20251001,01:29:49,BA1WJ25273504250SJ8T-14F014-AE,PASS,1,PD
8,FCT4,20251001,01:30:30,BA1WJ25273504248SJ8T-14F014-AE,PASS,1,PD
9,FCT4,20251001,01:31:06,BA1WJ25273504246SJ8T-14F014-AE,PASS,1,PD
10,FCT4,20251001,01:31:47,BA1WJ25273504244SJ8T-14F014-AE,PASS,1,PD
11,FCT4,20251001,01:32:21,BA1WJ25273504213SJ8T-14F014-AE,PASS,1,PD
12,FCT4,20251001,01:32:54,BA1WJ25273504211SJ8T-14F014-AE,PASS,1,PD
13,FCT4,20251001,01:33:38,BA1WJ25273504209SJ8T-14F014-AE,PASS,1,PD
14,FCT4,20251001,01:34:19,BA1WJ25273504222SJ8T-14F014-AE,PASS,1,PD
15,FCT4,20251001,01:35:02,BA1WJ25273504219SJ8T-14F014-AE,PASS,1,PD
16,FCT4,20251001,01:35:43,BA1WJ25273504217SJ8T-14F014-AE,PASS,1,PD
17,FCT4,20251001,01:36:17,BA1WJ25273504215SJ8T-14F014-AE,PASS,1,PD
18,FCT4,20251001,01:36:52,BA1WJ25273504228SJ8T-14F014-AE,PASS,1,PD
19,FCT4,20251001,01:37:27,BA1WJ25273504226SJ8T-14F014-AE,PASS,1,PD
20,FCT4,20251001,01:38:07,BA1WJ25273504224SJ8T-14F014-AE,PASS,1,PD
21,FCT4,20251001,01:38:46,BA1WJ25273504193SJ8T-14F014-AE,PASS,1,PD
22,FCT4,20251001,01:39:22,BA1WJ25273504191SJ8T-14F014-AE,PASS,1,PD
23,FCT4,20251001,01:40:04,BA1WJ25273504189SJ8T-14F014-AE,PASS,1,PD
24,FCT4,20251001,01:40:39,BA1WJ25273504187SJ8T-14F014-AE,PASS,1,PD
25,FCT4,20251001,01:33:38,BA1WJ25273504209SJ8T-14F014-AE,PASS,2,PD
26,FCT4,20251001,01:34:19,BA1WJ25273504222SJ8T-14F014-AE,PASS,2,PD
27,FCT4,20251001,01:35:02,BA1WJ25273504219SJ8T-14F014-AE,PASS,2,PD
28,FCT4,20251001,01:35:43,BA1WJ25273504217SJ8T-14F014-AE,PASS,2,PD
29,FCT4,20251001,01:36:17,BA1WJ25273504215SJ8T-14F014-AE,PASS,2,PD
30,FCT4,20251001,01:36:52,BA1WJ25273504228SJ8T-14F014-AE,PASS,2,PD
31,FCT4,20251001,01:37:27,BA1WJ25273504226SJ8T-14F014-AE,PASS,2,PD
32,FCT4,20251001,01:38:07,BA1WJ25273504224SJ8T-14F014-AE,PASS,2,PD
33,FCT4,20251001,01:38:46,BA1WJ25273504193SJ8T-14F014-AE,PASS,2,PD
34,FCT4,20251001,01:39:22,BA1WJ25273504191SJ8T-14F014-AE,PASS,2,PD
35,FCT4,20251001,01:40:04,BA1WJ25273504189SJ8T-14F014-AE,PASS,2,PD
36,FCT4,20251001,01:40:39,BA1WJ25273504187SJ8T-14F014-AE,PASS,2,PD
37,FCT4,20251001,01:41:42,BA1WJ25273504197SJ8T-14F014-AE,PASS,2,PD
38,FCT4,20251001,01:42:16,BA1WJ25273504195SJ8T-14F014-AE,PASS,2,PD
39,FCT4,20251001,01:43:00,BA1WJ25273504207SJ8T-14F014-AE,PASS,2,PD
40,FCT4,20251001,01:43:33,BA1WJ25273504205SJ8T-14F014-AE,PASS,2,PD
41,FCT4,20251001,01:44:15,BA1WJ25273504203SJ8T-14F014-AE,PASS,2,PD
42,FCT4,20251001,01:44:48,BA1WJ25273504201SJ8T-14F014-AE,PASS,2,PD
43,FCT4,20251001,01:45:28,BA1WJ25273504171SJ8T-14F014-AE,PASS,2,PD
44,FCT4,20251001,01:46:04,BA1WJ25273504169SJ8T-14F014-AE,PASS,2,PD
45,FCT4,20251001,01:46:44,BA1WJ25273504167SJ8T-14F014-AE,PASS,2,PD
46,FCT4,20251001,01:47:19,BA1WJ25273504179SJ8T-14F014-AE,PASS,2,PD
47,FCT4,20251001,01:47:54,BA1WJ25273504177SJ8T-14F014-AE,PASS,2,PD
48,FCT4,20251001,01:48:36,BA1WJ25273504175SJ8T-14F014-AE,PASS,2,PD
49,FCT4,20251001,01:49:11,BA1WJ25273504173SJ8T-14F014-AE,PASS,2,PD

In [34]:
# ============================================
# [7] JSON 테이블과 6번 결과 매칭 (end_time 포함)
#   스키마: a4_fct_json_table_processing
#   테이블: fct_json_table_processing
#
# 조건:
#  7-1) 6번 DF의 (station, end_day, end_time, barcode_information, result)와
#       동일한 JSON 행만 사용
#  7-2) 해당 행들의 step_description, value 붙이기
#  7-3) step_description, value 결측치 제거
#  7-4) station(FCT1~4) × remark(PD / Non-PD) → 8개 DF로 분리
#       (이때 end_time 반드시 포함)
# ============================================

from sqlalchemy import text

# -------------------------------------
# 1) 6번 결과 합치기
# -------------------------------------
cols_base = [
    "station",
    "end_day",
    "end_time",
    "barcode_information",
    "result",
    "remark",
    "fail_estimation_group",   # ⭐ 추가
]

df6_all = pd.concat(
    [
        df_FCT1_PASS_PD[cols_base],
        df_FCT2_PASS_PD[cols_base],
        df_FCT3_PASS_PD[cols_base],
        df_FCT4_PASS_PD[cols_base],
    ],
    ignore_index=True,
)

print("[INFO] 6번 합친 DF 행 개수:", len(df6_all))
display(df6_all.head(10))

if df6_all.empty:
    print("[WARN] 6번 결과가 비어 있어서 7번 수행 불가")
else:
    # -------------------------------------
    # 2) JSON 테이블에서 필요한 범위만 조회
    #    - station: 6번 DF에 있는 것만
    #    - end_day: 6번 DF에 있는 것만
    # -------------------------------------
    stations = sorted(df6_all["station"].dropna().unique().tolist())
    end_days = sorted(df6_all["end_day"].dropna().unique().tolist())

    stations_sql = ",".join(f"'{s}'" for s in stations)
    end_days_sql = ",".join(f"'{d}'" for d in end_days)

    query_json = f"""
    SELECT
        station,
        end_day,
        end_time,
        barcode_information,
        result,
        step_description,
        value
    FROM a4_fct_json_table_processing.fct_json_table_processing
    WHERE station IN ({stations_sql})
      AND end_day IN ({end_days_sql});
    """

    print("\n[INFO] JSON 조회 쿼리 실행 중...")
    df_json = pd.read_sql(text(query_json), engine)
    print("[INFO] JSON 조회 행 개수:", len(df_json))
    display(df_json.head(10))

    # -------------------------------------
    # 3) result 포맷 정규화 (예: '[PASS]' → 'PASS')
    # -------------------------------------
    def norm_result(s):
        s = str(s)
        if "PASS" in s:
            return "PASS"
        if "FAIL" in s:
            return "FAIL"
        return s

    df6_all = df6_all.copy()
    df_json = df_json.copy()

    df6_all["result_norm"] = df6_all["result"].apply(norm_result)
    df_json["result_norm"] = df_json["result"].apply(norm_result)

    # 문자열 방어 (공백 제거)
    for c in ["station", "end_day", "end_time", "barcode_information"]:
        df6_all[c] = df6_all[c].astype(str).str.strip()
        df_json[c] = df_json[c].astype(str).str.strip()

    # -------------------------------------
    # 4) 7-1: 완전 동일 key로 inner merge
    #    key = station, end_day, end_time, barcode_information, result_norm
    #    → end_time까지 포함해서 정확히 한 번의 테스트에만 매칭
    # -------------------------------------
    merge_keys = ["station", "end_day", "end_time", "barcode_information", "result_norm"]

    df_merged = pd.merge(
        df6_all,
        df_json,
        on=merge_keys,
        how="inner",
        suffixes=("_6", "_json"),
    )

    print("\n[INFO] merge 후 행 개수:", len(df_merged))
    display(df_merged.head(20))

    # -------------------------------------
    # 5) 7-2, 7-3: step_description, value 결측치 제거
    #     + 최종 사용할 컬럼만 추출 (end_time 포함!)
    # -------------------------------------
    df_merged = df_merged.dropna(subset=["step_description", "value"]).reset_index(drop=True)

    df_final = df_merged[[
        "fail_estimation_group",   # ⭐ 추가
        "remark",                  # PD / Non-PD
        "station",
        "end_day",
        "end_time",                # ⭐ 반드시 포함
        "barcode_information",
        "step_description",
        "value",
    ]].copy()

    # 동일 테스트(end_time 기준)에서 완전 중복 row 제거
    df_final = df_final.drop_duplicates(
        subset=[
            "fail_estimation_group",          # ⭐ 추가
            "remark",
            "station",
            "end_day",
            "end_time",
            "barcode_information",
            "step_description",
            "value",
        ]
    ).reset_index(drop=True)

    print("\n[INFO] 결측 및 중복 제거 후 최종 행 개수:", len(df_final))
    display(df_final.head(20))

    # -------------------------------------
    # 6) station × remark 로 8개 DF 분리
    #     (정렬 기준에도 end_time 포함)
    # -------------------------------------
    def split_station_remark(df, st, rk):
        sub = df[(df["station"] == st) & (df["remark"] == rk)].copy()
        sub = sub.sort_values(
            ["fail_estimation_group", "end_day", "end_time", "barcode_information", "step_description"]
        ).reset_index(drop=True)
        print(f"[INFO] {st}-{rk}: {len(sub)} rows")
        display(sub.head(10))
        return sub

    df_FCT1_PD    = split_station_remark(df_final, "FCT1", "PD")
    df_FCT1_NonPD = split_station_remark(df_final, "FCT1", "Non-PD")

    df_FCT2_PD    = split_station_remark(df_final, "FCT2", "PD")
    df_FCT2_NonPD = split_station_remark(df_final, "FCT2", "Non-PD")

    df_FCT3_PD    = split_station_remark(df_final, "FCT3", "PD")
    df_FCT3_NonPD = split_station_remark(df_final, "FCT3", "Non-PD")

    df_FCT4_PD    = split_station_remark(df_final, "FCT4", "PD")
    df_FCT4_NonPD = split_station_remark(df_final, "FCT4", "Non-PD")

[INFO] 6번 합친 DF 행 개수: 123391

,station,end_day,end_time,barcode_information,result,remark,fail_estimation_group
0,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2
1,FCT1,20251001,01:26:22,BA1WJ25273504253SJ8T-14F014-AE,PASS,PD,2
2,FCT1,20251001,01:26:57,BA1WJ25273504251SJ8T-14F014-AE,PASS,PD,2
3,FCT1,20251001,01:27:33,BA1WJ25273504263SJ8T-14F014-AE,PASS,PD,2
4,FCT1,20251001,01:28:09,BA1WJ25273504261SJ8T-14F014-AE,PASS,PD,2
5,FCT1,20251001,01:28:43,BA1WJ25273504259SJ8T-14F014-AE,PASS,PD,2
6,FCT1,20251001,01:29:24,BA1WJ25273504272SJ8T-14F014-AE,PASS,PD,2
7,FCT1,20251001,01:30:02,BA1WJ25273504270SJ8T-14F014-AE,PASS,PD,2
8,FCT1,20251001,01:30:36,BA1WJ25273504268SJ8T-14F014-AE,PASS,PD,2
9,FCT1,20251001,01:31:13,BA1WJ25273504266SJ8T-14F014-AE,PASS,PD,2

[INFO] JSON 조회 쿼리 실행 중...
[INFO] JSON 조회 행 개수: 6309466

,station,end_day,end_time,barcode_information,result,step_description,value
0,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
1,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.10 Test Boston Firmware Version,7.08
2,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.11 Test Boston ASIC Version,42.22
3,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.12_Test_Carplay_Type-C(B_side),PASS
4,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.13_Test_Carplay_Type-A,PASS
5,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.14 Profile Count Check,1
6,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.15 Test Power-NC_Line(ohm)Resistor,9999
7,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.16 Test DIM-NC_Line(ohm),9999
8,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.17 Test DIM-GND(ohm),9999
9,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.18 Test Input Voltage(V),18.00

[INFO] merge 후 행 개수: 4420806

,station,end_day,end_time,barcode_information,result_6,remark,fail_estimation_group,result_norm,result_json,step_description,value
0,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.01 Test Input Voltage(V),14.68
1,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.02_Test_USB2_error(Type-C_A_side),0
2,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.03_Test USB2 benchmark.maxrd(Mbit/s),360Mbit/s
3,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.04 Test USB2 benchmark.maxwr(Mbit/s),360Mbit/s
4,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.05 Test USB2 benchmark.avgrw(Mbit/s),343Mbit/s
5,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.06_Test_USB1_error(Type-A),0
6,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.07 Test USB1 benchmark.maxrd(Mbit/s),360Mbit/s
7,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.08 Test USB1 benchmark.maxwr(Mbit/s),360Mbit/s
8,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
9,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.10 Test Boston Firmware Version,7.03
10,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.11 Test Boston ASIC Version,42.22
11,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.12_Test_Carplay_Type-C(B_side),PASS
12,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.13_Test_Carplay_Type-A,PASS
13,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.14 Profile Count Check,1
14,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.15 Test Power-NC_Line(ohm)Resistor,9999
15,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.16 Test DIM-NC_Line(ohm),9999
16,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.17 Test DIM-GND(ohm),9999
17,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.18 Test Input Voltage(V),17.97
18,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.19 Test Idle Current(mA),0.05831544
19,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,PASS,PD,2,PASS,[PASS],1.20 Test VUSB_type-C(No-Load-A_side),5.147

[INFO] 결측 및 중복 제거 후 최종 행 개수: 4420770

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,step_description,value
0,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.01 Test Input Voltage(V),14.68
1,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.02_Test_USB2_error(Type-C_A_side),0
2,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.03_Test USB2 benchmark.maxrd(Mbit/s),360Mbit/s
3,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.04 Test USB2 benchmark.maxwr(Mbit/s),360Mbit/s
4,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.05 Test USB2 benchmark.avgrw(Mbit/s),343Mbit/s
5,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.06_Test_USB1_error(Type-A),0
6,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.07 Test USB1 benchmark.maxrd(Mbit/s),360Mbit/s
7,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.08 Test USB1 benchmark.maxwr(Mbit/s),360Mbit/s
8,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
9,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.10 Test Boston Firmware Version,7.03
10,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.11 Test Boston ASIC Version,42.22
11,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.12_Test_Carplay_Type-C(B_side),PASS
12,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.13_Test_Carplay_Type-A,PASS
13,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.14 Profile Count Check,1
14,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.15 Test Power-NC_Line(ohm)Resistor,9999
15,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.16 Test DIM-NC_Line(ohm),9999
16,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.17 Test DIM-GND(ohm),9999
17,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.18 Test Input Voltage(V),17.97
18,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.19 Test Idle Current(mA),0.05831544
19,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.20 Test VUSB_type-C(No-Load-A_side),5.147

[INFO] FCT1-PD: 1098664 rows

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,step_description,value
0,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.01 Test Input Voltage(V),14.68
1,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.02_Test_USB2_error(Type-C_A_side),0
2,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.03_Test USB2 benchmark.maxrd(Mbit/s),360Mbit/s
3,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.04 Test USB2 benchmark.maxwr(Mbit/s),360Mbit/s
4,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.05 Test USB2 benchmark.avgrw(Mbit/s),343Mbit/s
5,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.06_Test_USB1_error(Type-A),0
6,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.07 Test USB1 benchmark.maxrd(Mbit/s),360Mbit/s
7,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.08 Test USB1 benchmark.maxwr(Mbit/s),360Mbit/s
8,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
9,2,PD,FCT1,20251001,01:25:40,BA1WJ25273504255SJ8T-14F014-AE,1.10 Test Boston Firmware Version,7.03

[INFO] FCT1-Non-PD: 63030 rows

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,step_description,value
0,35,Non-PD,FCT1,20251001,08:21:43,BA1WJ23243500743UPC3T-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.40
1,35,Non-PD,FCT1,20251001,08:21:43,BA1WJ23243500743UPC3T-14F014-AC,1.01 Test RGUSB_usb(ohm),0.16
2,35,Non-PD,FCT1,20251001,08:21:43,BA1WJ23243500743UPC3T-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.28
3,35,Non-PD,FCT1,20251001,08:21:43,BA1WJ23243500743UPC3T-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
4,35,Non-PD,FCT1,20251001,08:21:43,BA1WJ23243500743UPC3T-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999
5,35,Non-PD,FCT1,20251001,08:21:43,BA1WJ23243500743UPC3T-14F014-AC,1.05 Test DIM-GND(ohm),9999
6,35,Non-PD,FCT1,20251001,08:21:43,BA1WJ23243500743UPC3T-14F014-AC,1.06 Test Input Voltage(V),16.48
7,35,Non-PD,FCT1,20251001,08:21:43,BA1WJ23243500743UPC3T-14F014-AC,1.07 Test Idle Current(mA),0.03783306
8,35,Non-PD,FCT1,20251001,08:21:43,BA1WJ23243500743UPC3T-14F014-AC,1.08 Test Boston Firmware Version,2.24
9,35,Non-PD,FCT1,20251001,08:21:43,BA1WJ23243500743UPC3T-14F014-AC,1.09 Test Boston ASIC Version,42.22

[INFO] FCT2-PD: 1581525 rows

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,step_description,value
0,1,PD,FCT2,20251001,01:25:03,BA1WJ25273504257SJ8T-14F014-AE,1.01 Test Input Voltage(V),14.68
1,1,PD,FCT2,20251001,01:25:03,BA1WJ25273504257SJ8T-14F014-AE,1.02_Test_USB2_error(Type-C_A_side),0
2,1,PD,FCT2,20251001,01:25:03,BA1WJ25273504257SJ8T-14F014-AE,1.03_Test USB2 benchmark.maxrd(Mbit/s),360Mbit/s
3,1,PD,FCT2,20251001,01:25:03,BA1WJ25273504257SJ8T-14F014-AE,1.04 Test USB2 benchmark.maxwr(Mbit/s),360Mbit/s
4,1,PD,FCT2,20251001,01:25:03,BA1WJ25273504257SJ8T-14F014-AE,1.05 Test USB2 benchmark.avgrw(Mbit/s),343Mbit/s
5,1,PD,FCT2,20251001,01:25:03,BA1WJ25273504257SJ8T-14F014-AE,1.06_Test_USB1_error(Type-A),0
6,1,PD,FCT2,20251001,01:25:03,BA1WJ25273504257SJ8T-14F014-AE,1.07 Test USB1 benchmark.maxrd(Mbit/s),360Mbit/s
7,1,PD,FCT2,20251001,01:25:03,BA1WJ25273504257SJ8T-14F014-AE,1.08 Test USB1 benchmark.maxwr(Mbit/s),360Mbit/s
8,1,PD,FCT2,20251001,01:25:03,BA1WJ25273504257SJ8T-14F014-AE,1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
9,1,PD,FCT2,20251001,01:25:03,BA1WJ25273504257SJ8T-14F014-AE,1.10 Test Boston Firmware Version,7.03

[INFO] FCT2-Non-PD: 71775 rows

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,step_description,value
0,19,Non-PD,FCT2,20251001,08:21:52,BA1WJ23228500512N1WT-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.40
1,19,Non-PD,FCT2,20251001,08:21:52,BA1WJ23228500512N1WT-14F014-AC,1.01 Test RGUSB_usb(ohm),0.36
2,19,Non-PD,FCT2,20251001,08:21:52,BA1WJ23228500512N1WT-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.40
3,19,Non-PD,FCT2,20251001,08:21:52,BA1WJ23228500512N1WT-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
4,19,Non-PD,FCT2,20251001,08:21:52,BA1WJ23228500512N1WT-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999
5,19,Non-PD,FCT2,20251001,08:21:52,BA1WJ23228500512N1WT-14F014-AC,1.05 Test DIM-GND(ohm),9999
6,19,Non-PD,FCT2,20251001,08:21:52,BA1WJ23228500512N1WT-14F014-AC,1.06 Test Input Voltage(V),16.48
7,19,Non-PD,FCT2,20251001,08:21:52,BA1WJ23228500512N1WT-14F014-AC,1.07 Test Idle Current(mA),0.03720309
8,19,Non-PD,FCT2,20251001,08:21:52,BA1WJ23228500512N1WT-14F014-AC,1.08 Test Boston Firmware Version,2.21
9,19,Non-PD,FCT2,20251001,08:21:52,BA1WJ23228500512N1WT-14F014-AC,1.09 Test Boston ASIC Version,42.22

[INFO] FCT3-PD: 653342 rows

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,step_description,value
0,1,PD,FCT3,20251001,01:50:54,BA1WJ25273504182SJ8T-14F014-AE,1.01 Test Input Voltage(V),14.67
1,1,PD,FCT3,20251001,01:50:54,BA1WJ25273504182SJ8T-14F014-AE,1.02_Test_USB2_error(Type-C_A_side),0
2,1,PD,FCT3,20251001,01:50:54,BA1WJ25273504182SJ8T-14F014-AE,1.03_Test USB2 benchmark.maxrd(Mbit/s),360Mbit/s
3,1,PD,FCT3,20251001,01:50:54,BA1WJ25273504182SJ8T-14F014-AE,1.04 Test USB2 benchmark.maxwr(Mbit/s),360Mbit/s
4,1,PD,FCT3,20251001,01:50:54,BA1WJ25273504182SJ8T-14F014-AE,1.05 Test USB2 benchmark.avgrw(Mbit/s),343Mbit/s
5,1,PD,FCT3,20251001,01:50:54,BA1WJ25273504182SJ8T-14F014-AE,1.06_Test_USB1_error(Type-A),0
6,1,PD,FCT3,20251001,01:50:54,BA1WJ25273504182SJ8T-14F014-AE,1.07 Test USB1 benchmark.maxrd(Mbit/s),360Mbit/s
7,1,PD,FCT3,20251001,01:50:54,BA1WJ25273504182SJ8T-14F014-AE,1.08 Test USB1 benchmark.maxwr(Mbit/s),360Mbit/s
8,1,PD,FCT3,20251001,01:50:54,BA1WJ25273504182SJ8T-14F014-AE,1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
9,1,PD,FCT3,20251001,01:50:54,BA1WJ25273504182SJ8T-14F014-AE,1.10 Test Boston Firmware Version,7.03

[INFO] FCT3-Non-PD: 63261 rows

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,step_description,value
0,15,Non-PD,FCT3,20251001,08:22:03,BA1WJ24085501579N1WT-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.26
1,15,Non-PD,FCT3,20251001,08:22:03,BA1WJ24085501579N1WT-14F014-AC,1.01 Test RGUSB_usb(ohm),0.21
2,15,Non-PD,FCT3,20251001,08:22:03,BA1WJ24085501579N1WT-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.23
3,15,Non-PD,FCT3,20251001,08:22:03,BA1WJ24085501579N1WT-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
4,15,Non-PD,FCT3,20251001,08:22:03,BA1WJ24085501579N1WT-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999
5,15,Non-PD,FCT3,20251001,08:22:03,BA1WJ24085501579N1WT-14F014-AC,1.05 Test DIM-GND(ohm),9999
6,15,Non-PD,FCT3,20251001,08:22:03,BA1WJ24085501579N1WT-14F014-AC,1.06 Test Input Voltage(V),16.48
7,15,Non-PD,FCT3,20251001,08:22:03,BA1WJ24085501579N1WT-14F014-AC,1.07 Test Idle Current(mA),0.03791266
8,15,Non-PD,FCT3,20251001,08:22:03,BA1WJ24085501579N1WT-14F014-AC,1.08 Test Boston Firmware Version,2.21
9,15,Non-PD,FCT3,20251001,08:22:03,BA1WJ24085501579N1WT-14F014-AC,1.09 Test Boston ASIC Version,42.22

[INFO] FCT4-PD: 813207 rows

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,step_description,value
0,1,PD,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,1.01 Test Input Voltage(V),14.67
1,1,PD,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,1.02_Test_USB2_error(Type-C_A_side),0
2,1,PD,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,1.03_Test USB2 benchmark.maxrd(Mbit/s),360Mbit/s
3,1,PD,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,1.04 Test USB2 benchmark.maxwr(Mbit/s),360Mbit/s
4,1,PD,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,1.05 Test USB2 benchmark.avgrw(Mbit/s),343Mbit/s
5,1,PD,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,1.06_Test_USB1_error(Type-A),0
6,1,PD,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,1.07 Test USB1 benchmark.maxrd(Mbit/s),360Mbit/s
7,1,PD,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,1.08 Test USB1 benchmark.maxwr(Mbit/s),360Mbit/s
8,1,PD,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
9,1,PD,FCT4,20251001,01:25:26,BA1WJ25273504236SJ8T-14F014-AE,1.10 Test Boston Firmware Version,7.03

[INFO] FCT4-Non-PD: 75966 rows

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,step_description,value
0,14,Non-PD,FCT4,20251001,08:22:10,BA1WJ23243500760UPC3T-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.23
1,14,Non-PD,FCT4,20251001,08:22:10,BA1WJ23243500760UPC3T-14F014-AC,1.01 Test RGUSB_usb(ohm),0.21
2,14,Non-PD,FCT4,20251001,08:22:10,BA1WJ23243500760UPC3T-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.17
3,14,Non-PD,FCT4,20251001,08:22:10,BA1WJ23243500760UPC3T-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
4,14,Non-PD,FCT4,20251001,08:22:10,BA1WJ23243500760UPC3T-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999
5,14,Non-PD,FCT4,20251001,08:22:10,BA1WJ23243500760UPC3T-14F014-AC,1.05 Test DIM-GND(ohm),9999
6,14,Non-PD,FCT4,20251001,08:22:10,BA1WJ23243500760UPC3T-14F014-AC,1.06 Test Input Voltage(V),16.50
7,14,Non-PD,FCT4,20251001,08:22:10,BA1WJ23243500760UPC3T-14F014-AC,1.07 Test Idle Current(mA),0.03859356
8,14,Non-PD,FCT4,20251001,08:22:10,BA1WJ23243500760UPC3T-14F014-AC,1.08 Test Boston Firmware Version,2.24
9,14,Non-PD,FCT4,20251001,08:22:10,BA1WJ23243500760UPC3T-14F014-AC,1.09 Test Boston ASIC Version,42.22

In [35]:
# ============================================
# [8] 최종 DataFrame을 PostgreSQL에 저장 (스키마 자동 생성 포함)
#     스키마: e3_fct_dataframe
# ============================================

from sqlalchemy import text

schema_name = "e3_fct_dataframe"

engine = get_engine()

# ---------------------------------------------------------
# 0) 스키마가 없다면 생성
# ---------------------------------------------------------
with engine.connect() as conn:
    conn.execute(text(f"CREATE SCHEMA IF NOT EXISTS {schema_name};"))
    conn.commit()

print(f"[INFO] 스키마 확인 완료 → {schema_name}")

# ---------------------------------------------------------
# 저장할 DF 목록과 테이블명 매핑
# ---------------------------------------------------------
save_targets = {
    "fct1_pd_before_ng_dataframe": df_FCT1_PD,
    "fct1_non_pd_before_ng_dataframe": df_FCT1_NonPD,
    "fct2_pd_before_ng_dataframe": df_FCT2_PD,
    "fct2_non_pd_before_ng_dataframe": df_FCT2_NonPD,
    "fct3_pd_before_ng_dataframe": df_FCT3_PD,
    "fct3_non_pd_before_ng_dataframe": df_FCT3_NonPD,
    "fct4_pd_before_ng_dataframe": df_FCT4_PD,
    "fct4_non_pd_before_ng_dataframe": df_FCT4_NonPD,
}

# ---------------------------------------------------------
# DataFrame → PostgreSQL 저장
# ---------------------------------------------------------
for table_name, df_data in save_targets.items():
    print(f"\n[INFO] 저장 시작 → {schema_name}.{table_name}")

    if df_data.empty:
        print(f"[WARN] DataFrame이 비어 있어서 저장하지 않음: {table_name}")
        continue

    df_data.to_sql(
        name=table_name,
        con=engine,
        schema=schema_name,
        if_exists="replace",   # 기존테이블 덮어쓰기
        index=False
    )

    print(f"[OK] 저장 완료 → {schema_name}.{table_name} (rows={len(df_data)})")

print("\n[INFO] 8번 작업 전체 완료!")

[INFO] Connection String: postgresql+psycopg2://postgres:leejangwoo1%21@localhost:5432/postgres
[INFO] 스키마 확인 완료 → e3_fct_dataframe

[INFO] 저장 시작 → e3_fct_dataframe.fct1_pd_before_ng_dataframe
[OK] 저장 완료 → e3_fct_dataframe.fct1_pd_before_ng_dataframe (rows=1098664)

[INFO] 저장 시작 → e3_fct_dataframe.fct1_non_pd_before_ng_dataframe
[OK] 저장 완료 → e3_fct_dataframe.fct1_non_pd_before_ng_dataframe (rows=63030)

[INFO] 저장 시작 → e3_fct_dataframe.fct2_pd_before_ng_dataframe
[OK] 저장 완료 → e3_fct_dataframe.fct2_pd_before_ng_dataframe (rows=1581525)

[INFO] 저장 시작 → e3_fct_dataframe.fct2_non_pd_before_ng_dataframe
[OK] 저장 완료 → e3_fct_dataframe.fct2_non_pd_before_ng_dataframe (rows=71775)

[INFO] 저장 시작 → e3_fct_dataframe.fct3_pd_before_ng_dataframe
[OK] 저장 완료 → e3_fct_dataframe.fct3_pd_before_ng_dataframe (rows=653342)

[INFO] 저장 시작 → e3_fct_dataframe.fct3_non_pd_before_ng_dataframe
[OK] 저장 완료 → e3_fct_dataframe.fct3_non_pd_before_ng_dataframe (rows=63261)

[INFO] 저장 시작 → e3_fct_dataframe.fct4_pd_before_ng_dataframe
[OK] 저장 완료 → e3_fct_dataframe.fct4_pd_before_ng_dataframe (rows=813207)

[INFO] 저장 시작 → e3_fct_dataframe.fct4_non_pd_before_ng_dataframe
[OK] 저장 완료 → e3_fct_dataframe.fct4_non_pd_before_ng_dataframe (rows=75966)

[INFO] 8번 작업 전체 완료!

In [36]:
# ============================================
# [9] JSON 원본 테이블에서 전체 PASS 데이터 읽기
#     스키마: a4_fct_json_table_processing
#     테이블: fct_json_table_processing
#
# 9-1: 컬럼 [remark, station, end_day, end_time,
#           barcode_information, step_description, value]
# 9-2: 8번(before NG) dataframe에 해당하는 "테스트(1회)"는 통째로 제외
#      → 기준 key = (station, end_day, end_time, barcode_information)
# 9-3: remark = barcode 18번째 글자(J/S → PD, 그 외 Non-PD)
# 9-4: station(FCT1~4) × PD/Non-PD → 8개 DF
# 9-5: 각 DF를 PostgreSQL(e3_fct_dataframe)에 저장
# ============================================

from sqlalchemy import text

engine = get_engine()

# ---------------------------------------------------------
# 0) 8번에서 저장된 DF들(FAIL 이전 PASS) 합치기
#    df_FCTx_PD / df_FCTx_NonPD 는 7번에서 만든 것과 동일
#    컬럼: remark, station, end_day, end_time,
#          barcode_information, step_description, value
# ---------------------------------------------------------
df_8_dict = {
    "fct1_pd":     df_FCT1_PD,
    "fct1_non_pd": df_FCT1_NonPD,
    "fct2_pd":     df_FCT2_PD,
    "fct2_non_pd": df_FCT2_NonPD,
    "fct3_pd":     df_FCT3_PD,
    "fct3_non_pd": df_FCT3_NonPD,
    "fct4_pd":     df_FCT4_PD,
    "fct4_non_pd": df_FCT4_NonPD,
}

df8_all = pd.concat(df_8_dict.values(), ignore_index=True)

# 8번에서 사용된 "테스트(1회)" key 만들기
#   기준: station + end_day + end_time + barcode_information
df8_all["test_key"] = list(zip(
    df8_all["station"].astype(str).str.strip(),
    df8_all["end_day"].astype(str).str.strip(),
    df8_all["end_time"].astype(str).str.strip(),
    df8_all["barcode_information"].astype(str).str.strip(),
))
df8_key_set = set(df8_all["test_key"])

print("[INFO] 8번 테스트 key 개수:", len(df8_key_set))

# ---------------------------------------------------------
# 1) JSON 테이블 전체 PASS 데이터 조회 (9-1)
#     → end_time 포함
# ---------------------------------------------------------
query_json_all = """
SELECT
    station,
    end_day,
    end_time,
    barcode_information,
    step_description,
    value,
    result
FROM a4_fct_json_table_processing.fct_json_table_processing
WHERE result LIKE '%PASS%';
"""

df_json_all = pd.read_sql(text(query_json_all), engine)

print("[INFO] JSON PASS 전체 행 개수:", len(df_json_all))
display(df_json_all.head(10))

# ---------------------------------------------------------
# 2) 8번 테스트를 통째로 제외 (9-2)
#    기준 key = station + end_day + end_time + barcode_information
#    → 같은 테스트(같은 시간에 같은 바코드로 찍힌 것)는 전부 제거
# ---------------------------------------------------------
df_json_all["test_key"] = list(zip(
    df_json_all["station"].astype(str).str.strip(),
    df_json_all["end_day"].astype(str).str.strip(),
    df_json_all["end_time"].astype(str).str.strip(),
    df_json_all["barcode_information"].astype(str).str.strip(),
))

df_filtered = df_json_all[~df_json_all["test_key"].isin(df8_key_set)].copy()

print("[INFO] 8번 테스트 제외 후 행 개수:", len(df_filtered))
display(df_filtered.head(10))

# ---------------------------------------------------------
# 3) remark 생성 (PD / Non-PD) (9-3)
# ---------------------------------------------------------
def classify_remark(barcode):
    if not isinstance(barcode, str) or len(barcode) < 18:
        return "Non-PD"
    return "PD" if barcode[17] in ("J", "S") else "Non-PD"

df_filtered["remark"] = df_filtered["barcode_information"].astype(str).apply(classify_remark)

# ---------------------------------------------------------
# 4) 필요한 컬럼만 유지 + 순서 정리 (9-1)
# ---------------------------------------------------------
df_filtered = df_filtered[[
    "remark",
    "station",
    "end_day",
    "end_time",
    "barcode_information",
    "step_description",
    "value",
]]

print("[INFO] 필수 컬럼 정리 후 샘플:")
display(df_filtered.head(10))

# ---------------------------------------------------------
# 5) FCT1~4 × PD/Non-PD  → 8개 DataFrame 생성 (9-4)
# ---------------------------------------------------------
def split_df(df, station, remark):
    sub = df[(df["station"] == station) & (df["remark"] == remark)].copy()
    sub = sub.sort_values(
        ["end_day", "end_time", "barcode_information", "step_description"]
    ).reset_index(drop=True)
    print(f"[INFO] {station}-{remark}: {len(sub)} rows")
    display(sub.head(10))
    return sub

df9_FCT1_PD    = split_df(df_filtered, "FCT1", "PD")
df9_FCT1_NonPD = split_df(df_filtered, "FCT1", "Non-PD")

df9_FCT2_PD    = split_df(df_filtered, "FCT2", "PD")
df9_FCT2_NonPD = split_df(df_filtered, "FCT2", "Non-PD")

df9_FCT3_PD    = split_df(df_filtered, "FCT3", "PD")
df9_FCT3_NonPD = split_df(df_filtered, "FCT3", "Non-PD")

df9_FCT4_PD    = split_df(df_filtered, "FCT4", "PD")
df9_FCT4_NonPD = split_df(df_filtered, "FCT4", "Non-PD")

# ============================================
# 6) PostgreSQL 저장 (9-5)
#    스키마: e3_fct_dataframe
#    테이블명:
#      fct1_pd_pass_dataframe
#      fct1_non-pd_pass_dataframe
#      ...
# ============================================

schema_name = "e3_fct_dataframe"

# 스키마 없으면 생성
with engine.connect() as conn:
    conn.execute(text(f"CREATE SCHEMA IF NOT EXISTS {schema_name};"))
    conn.commit()

save_map = {
    "fct1_pd_pass_dataframe":        df9_FCT1_PD,
    "fct1_non_pd_pass_dataframe":    df9_FCT1_NonPD,
    "fct2_pd_pass_dataframe":        df9_FCT2_PD,
    "fct2_non_pd_pass_dataframe":    df9_FCT2_NonPD,
    "fct3_pd_pass_dataframe":        df9_FCT3_PD,
    "fct3_non_pd_pass_dataframe":    df9_FCT3_NonPD,
    "fct4_pd_pass_dataframe":        df9_FCT4_PD,
    "fct4_non_pd_pass_dataframe":    df9_FCT4_NonPD,
}

for table_name, df_data in save_map.items():
    print(f"\n[INFO] 저장 시작 → {schema_name}.{table_name}")
    if df_data.empty:
        print("[WARN] DataFrame이 비어 있음 → 저장 생략")
        continue

    df_data.to_sql(
        name=table_name,
        con=engine,
        schema=schema_name,
        if_exists="replace",
        index=False
    )

    print(f"[OK] 저장 완료: {schema_name}.{table_name} (rows={len(df_data)})")

print("\n[INFO] 9번 전체 완료!")

[INFO] Connection String: postgresql+psycopg2://postgres:leejangwoo1%21@localhost:5432/postgres
[INFO] 8번 테스트 key 개수: 51890
[INFO] JSON PASS 전체 행 개수: 6305069

,station,end_day,end_time,barcode_information,step_description,value,result
0,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s,[PASS]
1,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.10 Test Boston Firmware Version,7.08,[PASS]
2,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.11 Test Boston ASIC Version,42.22,[PASS]
3,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.12_Test_Carplay_Type-C(B_side),PASS,[PASS]
4,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.13_Test_Carplay_Type-A,PASS,[PASS]
5,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.14 Profile Count Check,1,[PASS]
6,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.15 Test Power-NC_Line(ohm)Resistor,9999,[PASS]
7,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.16 Test DIM-NC_Line(ohm),9999,[PASS]
8,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.17 Test DIM-GND(ohm),9999,[PASS]
9,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.18 Test Input Voltage(V),18.00,[PASS]

[INFO] 8번 테스트 제외 후 행 개수: 4446815

,station,end_day,end_time,barcode_information,step_description,value,result,test_key
0,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s,[PASS],"(FCT4, 20251108, 01:33:19, BA1WJ25310500923SJ8..."
1,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.10 Test Boston Firmware Version,7.08,[PASS],"(FCT4, 20251108, 01:33:19, BA1WJ25310500923SJ8..."
2,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.11 Test Boston ASIC Version,42.22,[PASS],"(FCT4, 20251108, 01:33:19, BA1WJ25310500923SJ8..."
3,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.12_Test_Carplay_Type-C(B_side),PASS,[PASS],"(FCT4, 20251108, 01:33:19, BA1WJ25310500923SJ8..."
4,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.13_Test_Carplay_Type-A,PASS,[PASS],"(FCT4, 20251108, 01:33:19, BA1WJ25310500923SJ8..."
5,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.14 Profile Count Check,1,[PASS],"(FCT4, 20251108, 01:33:19, BA1WJ25310500923SJ8..."
6,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.15 Test Power-NC_Line(ohm)Resistor,9999,[PASS],"(FCT4, 20251108, 01:33:19, BA1WJ25310500923SJ8..."
7,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.16 Test DIM-NC_Line(ohm),9999,[PASS],"(FCT4, 20251108, 01:33:19, BA1WJ25310500923SJ8..."
8,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.17 Test DIM-GND(ohm),9999,[PASS],"(FCT4, 20251108, 01:33:19, BA1WJ25310500923SJ8..."
9,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.18 Test Input Voltage(V),18.00,[PASS],"(FCT4, 20251108, 01:33:19, BA1WJ25310500923SJ8..."

[INFO] 필수 컬럼 정리 후 샘플:

,remark,station,end_day,end_time,barcode_information,step_description,value
0,PD,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
1,PD,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.10 Test Boston Firmware Version,7.08
2,PD,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.11 Test Boston ASIC Version,42.22
3,PD,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.12_Test_Carplay_Type-C(B_side),PASS
4,PD,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.13_Test_Carplay_Type-A,PASS
5,PD,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.14 Profile Count Check,1
6,PD,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.15 Test Power-NC_Line(ohm)Resistor,9999
7,PD,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.16 Test DIM-NC_Line(ohm),9999
8,PD,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.17 Test DIM-GND(ohm),9999
9,PD,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,1.18 Test Input Voltage(V),18.00

[INFO] FCT1-PD: 782118 rows

,remark,station,end_day,end_time,barcode_information,step_description,value
0,PD,FCT1,20251001,01:24:59,BA1WJ25273504256SJ8T-14F014-AE,1.01 Test Input Voltage(V),14.68
1,PD,FCT1,20251001,01:41:41,BA1WJ25273503731SJ8T-14F014-AE,1.01 Test Input Voltage(V),14.68
2,PD,FCT1,20251001,01:42:16,BA1WJ25273503730SJ8T-14F014-AE,1.01 Test Input Voltage(V),14.68
3,PD,FCT1,20251001,01:42:16,BA1WJ25273503730SJ8T-14F014-AE,1.02_Test_USB2_error(Type-C_A_side),0
4,PD,FCT1,20251001,01:42:16,BA1WJ25273503730SJ8T-14F014-AE,1.03_Test USB2 benchmark.maxrd(Mbit/s),360Mbit/s
5,PD,FCT1,20251001,01:42:16,BA1WJ25273503730SJ8T-14F014-AE,1.04 Test USB2 benchmark.maxwr(Mbit/s),360Mbit/s
6,PD,FCT1,20251001,01:42:16,BA1WJ25273503730SJ8T-14F014-AE,1.05 Test USB2 benchmark.avgrw(Mbit/s),343Mbit/s
7,PD,FCT1,20251001,01:42:16,BA1WJ25273503730SJ8T-14F014-AE,1.06_Test_USB1_error(Type-A),0
8,PD,FCT1,20251001,01:42:16,BA1WJ25273503730SJ8T-14F014-AE,1.07 Test USB1 benchmark.maxrd(Mbit/s),360Mbit/s
9,PD,FCT1,20251001,01:42:16,BA1WJ25273503730SJ8T-14F014-AE,1.08 Test USB1 benchmark.maxwr(Mbit/s),360Mbit/s

[INFO] FCT1-Non-PD: 274442 rows

,remark,station,end_day,end_time,barcode_information,step_description,value
0,Non-PD,FCT1,20251001,08:22:18,BA1WJ23243500751UPC3T-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.47
1,Non-PD,FCT1,20251001,08:22:18,BA1WJ23243500751UPC3T-14F014-AC,1.01 Test RGUSB_usb(ohm),0.21
2,Non-PD,FCT1,20251001,08:22:18,BA1WJ23243500751UPC3T-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.37
3,Non-PD,FCT1,20251001,08:22:18,BA1WJ23243500751UPC3T-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
4,Non-PD,FCT1,20251001,08:22:18,BA1WJ23243500751UPC3T-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999
5,Non-PD,FCT1,20251001,20:21:12,BA1WJ23243500751UPC3T-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.61
6,Non-PD,FCT1,20251001,20:21:12,BA1WJ23243500751UPC3T-14F014-AC,1.01 Test RGUSB_usb(ohm),0.28
7,Non-PD,FCT1,20251001,20:21:12,BA1WJ23243500751UPC3T-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.52
8,Non-PD,FCT1,20251001,20:21:12,BA1WJ23243500751UPC3T-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
9,Non-PD,FCT1,20251001,20:21:12,BA1WJ23243500751UPC3T-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999

[INFO] FCT2-PD: 429664 rows

,remark,station,end_day,end_time,barcode_information,step_description,value
0,PD,FCT2,20251001,01:29:08,BA1WJ25273504258SJ8T-14F014-AE,1.01 Test Input Voltage(V),14.67
1,PD,FCT2,20251001,01:29:08,BA1WJ25273504258SJ8T-14F014-AE,1.02_Test_USB2_error(Type-C_A_side),0
2,PD,FCT2,20251001,01:29:08,BA1WJ25273504258SJ8T-14F014-AE,1.03_Test USB2 benchmark.maxrd(Mbit/s),360Mbit/s
3,PD,FCT2,20251001,01:29:08,BA1WJ25273504258SJ8T-14F014-AE,1.04 Test USB2 benchmark.maxwr(Mbit/s),360Mbit/s
4,PD,FCT2,20251001,01:29:08,BA1WJ25273504258SJ8T-14F014-AE,1.05 Test USB2 benchmark.avgrw(Mbit/s),343Mbit/s
5,PD,FCT2,20251001,01:29:08,BA1WJ25273504258SJ8T-14F014-AE,1.06_Test_USB1_error(Type-A),0
6,PD,FCT2,20251001,01:29:08,BA1WJ25273504258SJ8T-14F014-AE,1.07 Test USB1 benchmark.maxrd(Mbit/s),360Mbit/s
7,PD,FCT2,20251001,01:29:08,BA1WJ25273504258SJ8T-14F014-AE,1.08 Test USB1 benchmark.maxwr(Mbit/s),360Mbit/s
8,PD,FCT2,20251001,01:29:08,BA1WJ25273504258SJ8T-14F014-AE,1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
9,PD,FCT2,20251001,01:29:08,BA1WJ25273504258SJ8T-14F014-AE,1.10 Test Boston Firmware Version,7.03

[INFO] FCT2-Non-PD: 282272 rows

,remark,station,end_day,end_time,barcode_information,step_description,value
0,Non-PD,FCT2,20251001,08:22:37,BA1WJ23243500555UPC3T-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.25
1,Non-PD,FCT2,20251001,08:22:37,BA1WJ23243500555UPC3T-14F014-AC,1.01 Test RGUSB_usb(ohm),0.20
2,Non-PD,FCT2,20251001,08:22:37,BA1WJ23243500555UPC3T-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.22
3,Non-PD,FCT2,20251001,08:22:37,BA1WJ23243500555UPC3T-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
4,Non-PD,FCT2,20251001,08:22:37,BA1WJ23243500555UPC3T-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999
5,Non-PD,FCT2,20251001,20:21:30,BA1WJ23243500555UPC3T-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.27
6,Non-PD,FCT2,20251001,20:21:30,BA1WJ23243500555UPC3T-14F014-AC,1.01 Test RGUSB_usb(ohm),0.20
7,Non-PD,FCT2,20251001,20:21:30,BA1WJ23243500555UPC3T-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.22
8,Non-PD,FCT2,20251001,20:21:30,BA1WJ23243500555UPC3T-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
9,Non-PD,FCT2,20251001,20:21:30,BA1WJ23243500555UPC3T-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999

[INFO] FCT3-PD: 1037886 rows

,remark,station,end_day,end_time,barcode_information,step_description,value
0,PD,FCT3,20251001,01:25:40,BA1WJ25273504235SJ8T-14F014-AE,1.01 Test Input Voltage(V),14.67
1,PD,FCT3,20251001,01:25:40,BA1WJ25273504235SJ8T-14F014-AE,1.02_Test_USB2_error(Type-C_A_side),0
2,PD,FCT3,20251001,01:25:40,BA1WJ25273504235SJ8T-14F014-AE,1.03_Test USB2 benchmark.maxrd(Mbit/s),360Mbit/s
3,PD,FCT3,20251001,01:25:40,BA1WJ25273504235SJ8T-14F014-AE,1.04 Test USB2 benchmark.maxwr(Mbit/s),360Mbit/s
4,PD,FCT3,20251001,01:25:40,BA1WJ25273504235SJ8T-14F014-AE,1.05 Test USB2 benchmark.avgrw(Mbit/s),343Mbit/s
5,PD,FCT3,20251001,01:25:40,BA1WJ25273504235SJ8T-14F014-AE,1.06_Test_USB1_error(Type-A),0
6,PD,FCT3,20251001,01:25:40,BA1WJ25273504235SJ8T-14F014-AE,1.07 Test USB1 benchmark.maxrd(Mbit/s),360Mbit/s
7,PD,FCT3,20251001,01:25:40,BA1WJ25273504235SJ8T-14F014-AE,1.08 Test USB1 benchmark.maxwr(Mbit/s),360Mbit/s
8,PD,FCT3,20251001,01:25:40,BA1WJ25273504235SJ8T-14F014-AE,1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
9,PD,FCT3,20251001,01:25:40,BA1WJ25273504235SJ8T-14F014-AE,1.10 Test Boston Firmware Version,7.03

[INFO] FCT3-Non-PD: 302077 rows

,remark,station,end_day,end_time,barcode_information,step_description,value
0,Non-PD,FCT3,20251001,08:22:36,BA1WJ23243500548UPC3T-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.26
1,Non-PD,FCT3,20251001,08:22:36,BA1WJ23243500548UPC3T-14F014-AC,1.01 Test RGUSB_usb(ohm),0.24
2,Non-PD,FCT3,20251001,08:22:36,BA1WJ23243500548UPC3T-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.25
3,Non-PD,FCT3,20251001,08:22:36,BA1WJ23243500548UPC3T-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
4,Non-PD,FCT3,20251001,08:22:36,BA1WJ23243500548UPC3T-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999
5,Non-PD,FCT3,20251001,20:22:10,BA1WJ23243500548UPC3T-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.29
6,Non-PD,FCT3,20251001,20:22:10,BA1WJ23243500548UPC3T-14F014-AC,1.01 Test RGUSB_usb(ohm),0.21
7,Non-PD,FCT3,20251001,20:22:10,BA1WJ23243500548UPC3T-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.24
8,Non-PD,FCT3,20251001,20:22:10,BA1WJ23243500548UPC3T-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
9,Non-PD,FCT3,20251001,20:22:10,BA1WJ23243500548UPC3T-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999

[INFO] FCT4-PD: 1024028 rows

,remark,station,end_day,end_time,barcode_information,step_description,value
0,PD,FCT4,20251001,01:41:08,BA1WJ25273504199SJ8T-14F014-AE,1.01 Test Input Voltage(V),14.66
1,PD,FCT4,20251001,01:41:08,BA1WJ25273504199SJ8T-14F014-AE,1.02_Test_USB2_error(Type-C_A_side),0
2,PD,FCT4,20251001,01:41:08,BA1WJ25273504199SJ8T-14F014-AE,1.03_Test USB2 benchmark.maxrd(Mbit/s),360Mbit/s
3,PD,FCT4,20251001,01:41:08,BA1WJ25273504199SJ8T-14F014-AE,1.04 Test USB2 benchmark.maxwr(Mbit/s),360Mbit/s
4,PD,FCT4,20251001,01:41:08,BA1WJ25273504199SJ8T-14F014-AE,1.05 Test USB2 benchmark.avgrw(Mbit/s),343Mbit/s
5,PD,FCT4,20251001,01:41:08,BA1WJ25273504199SJ8T-14F014-AE,1.06_Test_USB1_error(Type-A),0
6,PD,FCT4,20251001,01:41:08,BA1WJ25273504199SJ8T-14F014-AE,1.07 Test USB1 benchmark.maxrd(Mbit/s),360Mbit/s
7,PD,FCT4,20251001,01:41:08,BA1WJ25273504199SJ8T-14F014-AE,1.08 Test USB1 benchmark.maxwr(Mbit/s),360Mbit/s
8,PD,FCT4,20251001,01:41:08,BA1WJ25273504199SJ8T-14F014-AE,1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
9,PD,FCT4,20251001,01:41:08,BA1WJ25273504199SJ8T-14F014-AE,1.10 Test Boston Firmware Version,7.03

[INFO] FCT4-Non-PD: 314328 rows

,remark,station,end_day,end_time,barcode_information,step_description,value
0,Non-PD,FCT4,20251001,08:22:50,BA1WJ23243500750UPC3T-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.21
1,Non-PD,FCT4,20251001,08:22:50,BA1WJ23243500750UPC3T-14F014-AC,1.01 Test RGUSB_usb(ohm),0.21
2,Non-PD,FCT4,20251001,08:22:50,BA1WJ23243500750UPC3T-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.20
3,Non-PD,FCT4,20251001,08:22:50,BA1WJ23243500750UPC3T-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
4,Non-PD,FCT4,20251001,08:22:50,BA1WJ23243500750UPC3T-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999
5,Non-PD,FCT4,20251001,20:22:26,BA1WJ23243500750UPC3T-14F014-AC,1.00 Test RGUSB_MiniB(ohm),0.22
6,Non-PD,FCT4,20251001,20:22:26,BA1WJ23243500750UPC3T-14F014-AC,1.01 Test RGUSB_usb(ohm),0.22
7,Non-PD,FCT4,20251001,20:22:26,BA1WJ23243500750UPC3T-14F014-AC,1.02 Test RGUSB_type-C(ohm),0.20
8,Non-PD,FCT4,20251001,20:22:26,BA1WJ23243500750UPC3T-14F014-AC,1.03 Test Power-NC_Line(ohm),9999
9,Non-PD,FCT4,20251001,20:22:26,BA1WJ23243500750UPC3T-14F014-AC,1.04 Test DIM-NC_Line(ohm),9999

[INFO] 저장 시작 → e3_fct_dataframe.fct1_pd_pass_dataframe
[OK] 저장 완료: e3_fct_dataframe.fct1_pd_pass_dataframe (rows=782118)

[INFO] 저장 시작 → e3_fct_dataframe.fct1_non_pd_pass_dataframe
[OK] 저장 완료: e3_fct_dataframe.fct1_non_pd_pass_dataframe (rows=274442)

[INFO] 저장 시작 → e3_fct_dataframe.fct2_pd_pass_dataframe
[OK] 저장 완료: e3_fct_dataframe.fct2_pd_pass_dataframe (rows=429664)

[INFO] 저장 시작 → e3_fct_dataframe.fct2_non_pd_pass_dataframe
[OK] 저장 완료: e3_fct_dataframe.fct2_non_pd_pass_dataframe (rows=282272)

[INFO] 저장 시작 → e3_fct_dataframe.fct3_pd_pass_dataframe
[OK] 저장 완료: e3_fct_dataframe.fct3_pd_pass_dataframe (rows=1037886)

[INFO] 저장 시작 → e3_fct_dataframe.fct3_non_pd_pass_dataframe
[OK] 저장 완료: e3_fct_dataframe.fct3_non_pd_pass_dataframe (rows=302077)

[INFO] 저장 시작 → e3_fct_dataframe.fct4_pd_pass_dataframe
[OK] 저장 완료: e3_fct_dataframe.fct4_pd_pass_dataframe (rows=1024028)

[INFO] 저장 시작 → e3_fct_dataframe.fct4_non_pd_pass_dataframe
[OK] 저장 완료: e3_fct_dataframe.fct4_non_pd_pass_dataframe (rows=314328)

[INFO] 9번 전체 완료!

In [37]:
# ============================================
# [10-0] FAIL 행에 대한 fail_estimation_group 매핑 테이블 생성
#   - 5번에서 만든 df_FCTx_PASS_FAIL(DataFrame)에
#     result='FAIL' 인 행만 모아서 매핑용 DF 생성
# ============================================

fail_group_cols = [
    "station",
    "end_day",
    "end_time",
    "barcode_information",
    "fail_estimation_group",
]

df_fail_group_map = pd.concat(
    [
        df_FCT1_PASS_FAIL[df_FCT1_PASS_FAIL["result"] == "FAIL"][fail_group_cols],
        df_FCT2_PASS_FAIL[df_FCT2_PASS_FAIL["result"] == "FAIL"][fail_group_cols],
        df_FCT3_PASS_FAIL[df_FCT3_PASS_FAIL["result"] == "FAIL"][fail_group_cols],
        df_FCT4_PASS_FAIL[df_FCT4_PASS_FAIL["result"] == "FAIL"][fail_group_cols],
    ],
    ignore_index=True,
)

print("[INFO] FAIL 그룹 매핑 DF 행 개수:", len(df_fail_group_map))
display(df_fail_group_map.head(10))

[INFO] FAIL 그룹 매핑 DF 행 개수: 4398

,station,end_day,end_time,barcode_information,fail_estimation_group
0,FCT1,20250930,01:24:59,BA1WJ25273504256SJ8T-14F014-AE,1
1,FCT1,20250930,01:41:41,BA1WJ25273503731SJ8T-14F014-AE,2
2,FCT1,20250930,02:10:12,BA1WJ25273503864SJ8T-14F014-AE,3
3,FCT1,20250930,02:13:46,BA1WJ25273503901SJ8T-14F014-AE,4
4,FCT1,20250930,02:38:19,BA1WJ25274500274SJ8T-14F014-AE,5
5,FCT1,20250930,02:44:48,BA1WJ25274500403SJ8T-14F014-AE,6
6,FCT1,20250930,02:49:29,BA1WJ25274500417SJ8T-14F014-AE,7
7,FCT1,20250930,03:04:35,BA1WJ25274500062SJ8T-14F014-AE,8
8,FCT1,20250930,03:10:11,BA1WJ25274500072SJ8T-14F014-AE,9
9,FCT1,20250930,03:21:35,BA1WJ25273504838SJ8T-14F014-AE,10

In [38]:
# ============================================
# [10] JSON 테이블에서 3-8 최초 FAIL 상세 가져오기 (+ PD/Non-PD 분리)
# ============================================

from sqlalchemy import text

engine = get_engine()

# -------------------------------------
# 1) 3-8 결과(FCT1~4)를 하나로 합치기
# -------------------------------------
df_fail_all = pd.concat(
    [
        df_first_fail_FCT1,
        df_first_fail_FCT2,
        df_first_fail_FCT3,
        df_first_fail_FCT4,
    ],
    ignore_index=True,
)

print("[INFO] 3-8 최초 FAIL 전체 행 개수:", len(df_fail_all))
display(df_fail_all.head(10))

if df_fail_all.empty:
    print("[WARN] 3-8 최초 FAIL 데이터가 없어 10번 수행 불가")
else:
    # 문자열 / 공백 정리
    for c in ["station", "end_day", "end_time", "barcode_information", "result"]:
        df_fail_all[c] = df_fail_all[c].astype(str).str.strip()

    # 🔹 10-1) 3-8 최초 FAIL 리스트에 fail_estimation_group 붙이기
    #      키: station, end_day, end_time, barcode_information
    df_fail_all = pd.merge(
        df_fail_all,
        df_fail_group_map,
        on=["station", "end_day", "end_time", "barcode_information"],
        how="left",
    )

    print("[INFO] fail_estimation_group 병합 후 샘플:")
    display(df_fail_all.head(10))

    # result 정규화 함수 (FAIL / PASS 로만 통일)
    def norm_result(s: str) -> str:
        s = str(s).upper()
        if "FAIL" in s:
            return "FAIL"
        if "PASS" in s:
            return "PASS"
        return s

    df_fail_all["result_norm"] = df_fail_all["result"].apply(norm_result)

    # FCT1~4, end_day 범위만 추려서 JSON 쿼리 범위 제한
    stations = sorted(df_fail_all["station"].dropna().unique().tolist())
    end_days = sorted(df_fail_all["end_day"].dropna().unique().tolist())

    stations_sql = ",".join(f"'{s}'" for s in stations)
    end_days_sql = ",".join(f"'{d}'" for d in end_days)

    # -------------------------------------
    # 2) JSON 테이블에서 후보 데이터 조회
    #    (station, end_day로 1차 필터링)
    # -------------------------------------
    query_json_fail = f"""
    SELECT
        station,
        end_day,
        end_time,
        barcode_information,
        result,
        step_description,
        value
    FROM a4_fct_json_table_processing.fct_json_table_processing
    WHERE station IN ({stations_sql})
      AND end_day IN ({end_days_sql});
    """

    print("\n[INFO] JSON FAIL 후보 조회 쿼리 실행 중...")
    df_json_fail = pd.read_sql(text(query_json_fail), engine)

    print("[INFO] JSON 후보 행 개수:", len(df_json_fail))
    display(df_json_fail.head(10))

    # 문자열 / 공백 정리
    for c in ["station", "end_day", "end_time", "barcode_information", "result"]:
        df_json_fail[c] = df_json_fail[c].astype(str).str.strip()

    # JSON result도 동일하게 정규화
    df_json_fail["result_norm"] = df_json_fail["result"].apply(norm_result)

    # -------------------------------------
    # 3) 5개 컬럼(단 result는 result_norm) 기준으로 inner merge
    #    key = station, end_day, end_time, barcode_information, result_norm
    # -------------------------------------
    merge_keys = [
        "station",
        "end_day",
        "end_time",
        "barcode_information",
        "result_norm",
    ]

    df10_merged = pd.merge(
        df_fail_all,      # ← 여기 안에 이미 fail_estimation_group 포함
        df_json_fail,
        on=merge_keys,
        how="inner",
        suffixes=("_fail", "_json"),
    )

    print("\n[INFO] 3-8 최초 FAIL과 JSON 매칭 후 행 개수:", len(df10_merged))
    display(df10_merged.head(20))

    # remark 생성 (PD / Non-PD)
    def classify_remark(barcode: str) -> str:
        if not isinstance(barcode, str):
            barcode = str(barcode)
        if len(barcode) < 18:
            return "Non-PD"
        return "PD" if barcode[17] in ("J", "S") else "Non-PD"

    df10_merged["remark"] = df10_merged["barcode_information"].apply(classify_remark)

    # -------------------------------------------------
    # 🔥 바코드별 "진짜 최초 FAIL"만 남기기
    #     기준: station + barcode_information 별 fail_ts 최소
    # -------------------------------------------------
    df10_merged["fail_ts"] = pd.to_datetime(
        df10_merged["end_day"].astype(str).str.strip() + " " +
        df10_merged["end_time"].astype(str).str.strip(),
        format="%Y%m%d %H:%M:%S",
        errors="coerce",
    )

    min_fail_ts = (
        df10_merged
        .groupby(["station", "barcode_information"])["fail_ts"]
        .transform("min")
    )

    df10_earliest = df10_merged[df10_merged["fail_ts"] == min_fail_ts].copy()

    print("\n[INFO] 바코드별 최초 FAIL만 남긴 후 행 개수:",
          len(df10_earliest))
    display(df10_earliest.head(20))

    # -------------------------------------------------
    # 최종 사용할 컬럼만 정리
    #  → fail_estimation_group 포함
    # -------------------------------------------------
    df10_final = df10_earliest[[
        "fail_estimation_group",   # ⭐ 그룹 번호
        "remark",
        "station",
        "end_day",
        "end_time",
        "barcode_information",
        "result_fail",        # 3-8에서 가져온 result
        "step_description",
        "value",
    ]].rename(columns={"result_fail": "result"})

    df10_final = df10_final.sort_values(
        [
            "fail_estimation_group",         # ⭐ 그룹 오름차순
            "station",
            "remark",
            "end_day",
            "end_time",
            "barcode_information",
            "step_description",
        ]
    ).reset_index(drop=True)

    print("\n[INFO] 10번 최종 FAIL 상세 DF 샘플:")
    display(df10_final.head(20))

    # -------------------------------------
    # station × remark 별 DF 분리
    #   → 각 셀에 fail_estimation_group 그대로 보이게
    # -------------------------------------
    def split_station_remark_fail(df, st, rk):
        sub = df[(df["station"] == st) & (df["remark"] == rk)].copy()
        sub = sub.sort_values(
            [
                "fail_estimation_group",
                "end_day",
                "end_time",
                "barcode_information",
                "step_description",
            ]
        ).reset_index(drop=True)
        print(f"\n[INFO] {st}-{rk} 최초 FAIL 상세 (rows={len(sub)})")
        display(sub.head(20))
        return sub

    df10_FCT1_PD_FAIL    = split_station_remark_fail(df10_final, "FCT1", "PD")
    df10_FCT1_NonPD_FAIL = split_station_remark_fail(df10_final, "FCT1", "Non-PD")

    df10_FCT2_PD_FAIL    = split_station_remark_fail(df10_final, "FCT2", "PD")
    df10_FCT2_NonPD_FAIL = split_station_remark_fail(df10_final, "FCT2", "Non-PD")

    df10_FCT3_PD_FAIL    = split_station_remark_fail(df10_final, "FCT3", "PD")
    df10_FCT3_NonPD_FAIL = split_station_remark_fail(df10_final, "FCT3", "Non-PD")

    df10_FCT4_PD_FAIL    = split_station_remark_fail(df10_final, "FCT4", "PD")
    df10_FCT4_NonPD_FAIL = split_station_remark_fail(df10_final, "FCT4", "Non-PD")

[INFO] Connection String: postgresql+psycopg2://postgres:leejangwoo1%21@localhost:5432/postgres
[INFO] 3-8 최초 FAIL 전체 행 개수: 4398

  station   end_day  end_time             barcode_information result
0    FCT1  20250930  01:24:59  BA1WJ25273504256SJ8T-14F014-AE   FAIL
1    FCT1  20250930  01:41:41  BA1WJ25273503731SJ8T-14F014-AE   FAIL
2    FCT1  20250930  02:10:12  BA1WJ25273503864SJ8T-14F014-AE   FAIL
3    FCT1  20250930  02:13:46  BA1WJ25273503901SJ8T-14F014-AE   FAIL
4    FCT1  20250930  02:38:19  BA1WJ25274500274SJ8T-14F014-AE   FAIL
5    FCT1  20250930  02:44:48  BA1WJ25274500403SJ8T-14F014-AE   FAIL
6    FCT1  20250930  02:49:29  BA1WJ25274500417SJ8T-14F014-AE   FAIL
7    FCT1  20250930  03:04:35  BA1WJ25274500062SJ8T-14F014-AE   FAIL
8    FCT1  20250930  03:10:11  BA1WJ25274500072SJ8T-14F014-AE   FAIL
9    FCT1  20250930  03:21:35  BA1WJ25273504838SJ8T-14F014-AE   FAIL

[INFO] fail_estimation_group 병합 후 샘플:

,station,end_day,end_time,barcode_information,result,fail_estimation_group
0,FCT1,20250930,01:24:59,BA1WJ25273504256SJ8T-14F014-AE,FAIL,1
1,FCT1,20250930,01:41:41,BA1WJ25273503731SJ8T-14F014-AE,FAIL,2
2,FCT1,20250930,02:10:12,BA1WJ25273503864SJ8T-14F014-AE,FAIL,3
3,FCT1,20250930,02:13:46,BA1WJ25273503901SJ8T-14F014-AE,FAIL,4
4,FCT1,20250930,02:38:19,BA1WJ25274500274SJ8T-14F014-AE,FAIL,5
5,FCT1,20250930,02:44:48,BA1WJ25274500403SJ8T-14F014-AE,FAIL,6
6,FCT1,20250930,02:49:29,BA1WJ25274500417SJ8T-14F014-AE,FAIL,7
7,FCT1,20250930,03:04:35,BA1WJ25274500062SJ8T-14F014-AE,FAIL,8
8,FCT1,20250930,03:10:11,BA1WJ25274500072SJ8T-14F014-AE,FAIL,9
9,FCT1,20250930,03:21:35,BA1WJ25273504838SJ8T-14F014-AE,FAIL,10

[INFO] JSON FAIL 후보 조회 쿼리 실행 중...
[INFO] JSON 후보 행 개수: 6123405

,station,end_day,end_time,barcode_information,result,step_description,value
0,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.09 Test USB1 benchmark.avgrw(Mbit/s),343Mbit/s
1,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.10 Test Boston Firmware Version,7.08
2,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.11 Test Boston ASIC Version,42.22
3,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.12_Test_Carplay_Type-C(B_side),PASS
4,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.13_Test_Carplay_Type-A,PASS
5,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.14 Profile Count Check,1
6,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.15 Test Power-NC_Line(ohm)Resistor,9999
7,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.16 Test DIM-NC_Line(ohm),9999
8,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.17 Test DIM-GND(ohm),9999
9,FCT4,20251108,01:33:19,BA1WJ25310500923SJ8T-14F014-AF,[PASS],1.18 Test Input Voltage(V),18.00

[INFO] 3-8 최초 FAIL과 JSON 매칭 후 행 개수: 2170

,station,end_day,end_time,barcode_information,result_fail,fail_estimation_group,result_norm,result_json,step_description,value
0,FCT1,20251001,08:57:12,BA1WJ25274500616SJ8T-14F014-AE,FAIL,70,FAIL,[FAIL],1.12_Test_Carplay_Type-C(B_side),FAIL
1,FCT1,20251001,09:52:38,BA1WJ25274500938USJ8T-14F014-AE,FAIL,71,FAIL,[FAIL],1.14 Profile Count Check,4
2,FCT1,20251001,09:55:50,BA1WJ25274500815USJ8T-14F014-AE,FAIL,72,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),
3,FCT1,20251001,10:02:55,BA1WJ25274500765USJ8T-14F014-AE,FAIL,73,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),
4,FCT1,20251001,10:46:49,BA1WJ25274501250USJ8T-14F014-AE,FAIL,74,FAIL,[FAIL],1.14 Profile Count Check,4
5,FCT1,20251001,10:57:37,BA1WJ25274501116USJ8T-14F014-AE,FAIL,75,FAIL,[FAIL],1.14 Profile Count Check,4
6,FCT1,20251001,11:12:27,BA1WJ25274500055USJ8T-14F014-AE,FAIL,76,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),
7,FCT1,20251001,12:56:55,BA1WJ25274500298USJ8T-14F014-AE,FAIL,77,FAIL,[FAIL],1.14 Profile Count Check,4
8,FCT1,20251001,12:59:26,BA1WJ25274500240USJ8T-14F014-AE,FAIL,78,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),
9,FCT1,20251001,13:02:29,BA1WJ25274500258USJ8T-14F014-AE,FAIL,79,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),
10,FCT1,20251001,16:25:47,BA1WJ25274500406USJ8T-14F014-AE,FAIL,80,FAIL,[FAIL],1.13_Test_Carplay_Type-A,FAIL
11,FCT1,20251001,20:21:12,BA1WJ23243500751UPC3T-14F014-AC,FAIL,81,FAIL,[FAIL],1.05 Test DIM-GND(ohm),0.96
12,FCT1,20251001,20:22:47,BA1WJ24068500086SJ8T-14F014-AC,FAIL,82,FAIL,[FAIL],1.14 Profile Count Check,4
13,FCT1,20251001,20:31:32,BA1WJ23243500751UPC3T-14F014-AC,FAIL,83,FAIL,[FAIL],1.05 Test DIM-GND(ohm),0.98
14,FCT1,20251001,20:33:08,BA1WJ24068500086SJ8T-14F014-AC,FAIL,84,FAIL,[FAIL],1.14 Profile Count Check,4
15,FCT1,20251001,20:54:15,BA1WJ25274501900USJ8T-14F014-AE,FAIL,85,FAIL,[FAIL],1.14 Profile Count Check,4
16,FCT1,20251001,21:08:56,BA1WJ25274501790USJ8T-14F014-AE,FAIL,86,FAIL,[FAIL],1.14 Profile Count Check,4
17,FCT1,20251001,21:17:31,BA1WJ25274501841USJ8T-14F014-AE,FAIL,87,FAIL,[FAIL],1.14 Profile Count Check,4
18,FCT1,20251001,21:32:32,BA1WJ25274501490USJ8T-14F014-AE,FAIL,88,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),
19,FCT1,20251001,21:37:00,BA1WJ25274501355USJ8T-14F014-AE,FAIL,89,FAIL,[FAIL],1.14 Profile Count Check,4

[INFO] 바코드별 최초 FAIL만 남긴 후 행 개수: 1849

,station,end_day,end_time,barcode_information,result_fail,fail_estimation_group,result_norm,result_json,step_description,value,remark,fail_ts
0,FCT1,20251001,08:57:12,BA1WJ25274500616SJ8T-14F014-AE,FAIL,70,FAIL,[FAIL],1.12_Test_Carplay_Type-C(B_side),FAIL,PD,2025-10-01 08:57:12
1,FCT1,20251001,09:52:38,BA1WJ25274500938USJ8T-14F014-AE,FAIL,71,FAIL,[FAIL],1.14 Profile Count Check,4,PD,2025-10-01 09:52:38
2,FCT1,20251001,09:55:50,BA1WJ25274500815USJ8T-14F014-AE,FAIL,72,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),,PD,2025-10-01 09:55:50
3,FCT1,20251001,10:02:55,BA1WJ25274500765USJ8T-14F014-AE,FAIL,73,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),,PD,2025-10-01 10:02:55
4,FCT1,20251001,10:46:49,BA1WJ25274501250USJ8T-14F014-AE,FAIL,74,FAIL,[FAIL],1.14 Profile Count Check,4,PD,2025-10-01 10:46:49
5,FCT1,20251001,10:57:37,BA1WJ25274501116USJ8T-14F014-AE,FAIL,75,FAIL,[FAIL],1.14 Profile Count Check,4,PD,2025-10-01 10:57:37
6,FCT1,20251001,11:12:27,BA1WJ25274500055USJ8T-14F014-AE,FAIL,76,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),,PD,2025-10-01 11:12:27
7,FCT1,20251001,12:56:55,BA1WJ25274500298USJ8T-14F014-AE,FAIL,77,FAIL,[FAIL],1.14 Profile Count Check,4,PD,2025-10-01 12:56:55
8,FCT1,20251001,12:59:26,BA1WJ25274500240USJ8T-14F014-AE,FAIL,78,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),,PD,2025-10-01 12:59:26
9,FCT1,20251001,13:02:29,BA1WJ25274500258USJ8T-14F014-AE,FAIL,79,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),,PD,2025-10-01 13:02:29
10,FCT1,20251001,16:25:47,BA1WJ25274500406USJ8T-14F014-AE,FAIL,80,FAIL,[FAIL],1.13_Test_Carplay_Type-A,FAIL,PD,2025-10-01 16:25:47
11,FCT1,20251001,20:21:12,BA1WJ23243500751UPC3T-14F014-AC,FAIL,81,FAIL,[FAIL],1.05 Test DIM-GND(ohm),0.96,Non-PD,2025-10-01 20:21:12
12,FCT1,20251001,20:22:47,BA1WJ24068500086SJ8T-14F014-AC,FAIL,82,FAIL,[FAIL],1.14 Profile Count Check,4,PD,2025-10-01 20:22:47
15,FCT1,20251001,20:54:15,BA1WJ25274501900USJ8T-14F014-AE,FAIL,85,FAIL,[FAIL],1.14 Profile Count Check,4,PD,2025-10-01 20:54:15
16,FCT1,20251001,21:08:56,BA1WJ25274501790USJ8T-14F014-AE,FAIL,86,FAIL,[FAIL],1.14 Profile Count Check,4,PD,2025-10-01 21:08:56
17,FCT1,20251001,21:17:31,BA1WJ25274501841USJ8T-14F014-AE,FAIL,87,FAIL,[FAIL],1.14 Profile Count Check,4,PD,2025-10-01 21:17:31
18,FCT1,20251001,21:32:32,BA1WJ25274501490USJ8T-14F014-AE,FAIL,88,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),,PD,2025-10-01 21:32:32
19,FCT1,20251001,21:37:00,BA1WJ25274501355USJ8T-14F014-AE,FAIL,89,FAIL,[FAIL],1.14 Profile Count Check,4,PD,2025-10-01 21:37:00
20,FCT1,20251001,21:44:27,BA1WJ25274501396USJ8T-14F014-AE,FAIL,90,FAIL,[FAIL],1.20 Test VUSB_type-C(No-Load-A_side),0.015,PD,2025-10-01 21:44:27
21,FCT1,20251001,22:08:30,BA1WJ25274502572USJ8T-14F014-AE,FAIL,91,FAIL,[FAIL],1.02_Test_USB2_error(Type-C_A_side),,PD,2025-10-01 22:08:30

[INFO] 10번 최종 FAIL 상세 DF 샘플:

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,result,step_description,value
0,25,PD,FCT4,20251001,08:34:05,BA1WJ25273504652SJ8T-14F014-AE,FAIL,1.34_Test_VUSB_Type-C_A(ELoad2=1.35A)vol,4.987
1,26,PD,FCT4,20251001,08:51:58,BA1WJ25273504600SJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
2,27,PD,FCT4,20251001,10:01:43,BA1WJ25274500966USJ8T-14F014-AE,FAIL,1.01 Test Input Voltage(V),14.51
3,28,PD,FCT4,20251001,12:46:00,BA1WJ25274500085USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
4,29,PD,FCT4,20251001,13:08:23,BA1WJ25274500092USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
5,30,PD,FCT3,20251001,11:18:43,BA1WJ25274501184USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
6,30,PD,FCT4,20251001,13:16:25,BA1WJ25274500262USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
7,31,PD,FCT4,20251001,17:15:42,BA1WJ25274500015USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
8,32,PD,FCT3,20251001,16:31:17,BA1WJ25274500165USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
9,32,PD,FCT4,20251001,19:07:02,BA1WJ25274500123USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
10,33,PD,FCT3,20251001,16:33:10,BA1WJ25274500194USJ8T-14F014-AE,FAIL,1.06_Test_USB1_error(Type-A),
11,33,PD,FCT4,20251001,19:59:53,BA1WJ25274501565USJ8T-14F014-AE,FAIL,1.12_Test_Carplay_Type-C(B_side),FAIL
12,34,PD,FCT3,20251001,17:10:28,BA1WJ25274500004USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
13,34,Non-PD,FCT4,20251001,20:22:26,BA1WJ23243500750UPC3T-14F014-AC,FAIL,1.05 Test DIM-GND(ohm),0.70
14,35,PD,FCT3,20251001,19:15:27,BA1WJ25274501033USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
15,35,PD,FCT4,20251001,20:23:59,BA1WJ24068500124SJ8T-14F014-AC,FAIL,1.17 Test DIM-GND(ohm),0.91
16,36,Non-PD,FCT3,20251001,20:22:10,BA1WJ23243500548UPC3T-14F014-AC,FAIL,1.05 Test DIM-GND(ohm),0.64
17,37,PD,FCT3,20251001,20:23:36,BA1WJ24068500081SJ8T-14F014-AC,FAIL,1.02_Test_USB2_error(Type-C_A_side),
18,38,PD,FCT4,20251001,21:26:29,BA1WJ25274501682USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
19,40,PD,FCT3,20251001,21:06:07,BA1WJ25274501749USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4

[INFO] FCT1-PD 최초 FAIL 상세 (rows=437)

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,result,step_description,value
0,70,PD,FCT1,20251001,08:57:12,BA1WJ25274500616SJ8T-14F014-AE,FAIL,1.12_Test_Carplay_Type-C(B_side),FAIL
1,71,PD,FCT1,20251001,09:52:38,BA1WJ25274500938USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
2,72,PD,FCT1,20251001,09:55:50,BA1WJ25274500815USJ8T-14F014-AE,FAIL,1.02_Test_USB2_error(Type-C_A_side),
3,73,PD,FCT1,20251001,10:02:55,BA1WJ25274500765USJ8T-14F014-AE,FAIL,1.02_Test_USB2_error(Type-C_A_side),
4,74,PD,FCT1,20251001,10:46:49,BA1WJ25274501250USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
5,75,PD,FCT1,20251001,10:57:37,BA1WJ25274501116USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
6,76,PD,FCT1,20251001,11:12:27,BA1WJ25274500055USJ8T-14F014-AE,FAIL,1.02_Test_USB2_error(Type-C_A_side),
7,77,PD,FCT1,20251001,12:56:55,BA1WJ25274500298USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
8,78,PD,FCT1,20251001,12:59:26,BA1WJ25274500240USJ8T-14F014-AE,FAIL,1.02_Test_USB2_error(Type-C_A_side),
9,79,PD,FCT1,20251001,13:02:29,BA1WJ25274500258USJ8T-14F014-AE,FAIL,1.02_Test_USB2_error(Type-C_A_side),
10,80,PD,FCT1,20251001,16:25:47,BA1WJ25274500406USJ8T-14F014-AE,FAIL,1.13_Test_Carplay_Type-A,FAIL
11,82,PD,FCT1,20251001,20:22:47,BA1WJ24068500086SJ8T-14F014-AC,FAIL,1.14 Profile Count Check,4
12,85,PD,FCT1,20251001,20:54:15,BA1WJ25274501900USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
13,86,PD,FCT1,20251001,21:08:56,BA1WJ25274501790USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
14,87,PD,FCT1,20251001,21:17:31,BA1WJ25274501841USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
15,88,PD,FCT1,20251001,21:32:32,BA1WJ25274501490USJ8T-14F014-AE,FAIL,1.02_Test_USB2_error(Type-C_A_side),
16,89,PD,FCT1,20251001,21:37:00,BA1WJ25274501355USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
17,90,PD,FCT1,20251001,21:44:27,BA1WJ25274501396USJ8T-14F014-AE,FAIL,1.20 Test VUSB_type-C(No-Load-A_side),0.015
18,91,PD,FCT1,20251001,22:08:30,BA1WJ25274502572USJ8T-14F014-AE,FAIL,1.02_Test_USB2_error(Type-C_A_side),
19,92,PD,FCT1,20251001,22:13:01,BA1WJ25274502674USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4

[INFO] FCT1-Non-PD 최초 FAIL 상세 (rows=18)

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,result,step_description,value
0,81,Non-PD,FCT1,20251001,20:21:12,BA1WJ23243500751UPC3T-14F014-AC,FAIL,1.05 Test DIM-GND(ohm),0.96
1,163,Non-PD,FCT1,20251010,17:32:02,BA1WJ25283500440PC3T-14F014-AC,FAIL,1.22 Test Carplay type-C,FAIL
2,164,Non-PD,FCT1,20251010,17:38:57,BA1WJ25283500408PC3T-14F014-AC,FAIL,1.22 Test Carplay type-C,FAIL
3,167,Non-PD,FCT1,20251010,20:43:31,BA1WJ25283502058PC3T-14F014-AC,FAIL,1.22 Test Carplay type-C,FAIL
4,189,Non-PD,FCT1,20251013,09:42:55,BA1WJ25286500198PC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
5,190,Non-PD,FCT1,20251013,17:16:37,BA1WJ25284500564PC3T-14F014-AC,FAIL,1.01 Test RGUSB_usb(ohm),9999
6,192,Non-PD,FCT1,20251013,22:12:23,BA1WJ25286504953PC3T-14F014-AC,FAIL,1.12 Test VUSB_type-C(ELoad2=5A)(V),0.001
7,258,Non-PD,FCT1,20251015,21:56:41,BA1WJ25288500162PC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
8,259,Non-PD,FCT1,20251015,23:20:04,BA1WJ25288500780PC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
9,261,Non-PD,FCT1,20251015,23:55:28,BA1WJ25288501846UPC3T-14F014-AC,FAIL,1.15 Test VUSB_usb (ELoad1=5A)(V),5.003
10,401,Non-PD,FCT1,20251026,09:45:06,BA1WJ25297500488UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01444127
11,402,Non-PD,FCT1,20251026,09:45:20,BA1WJ25297500487UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01471683
12,403,Non-PD,FCT1,20251026,09:46:54,BA1WJ25297500482UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01442223
13,404,Non-PD,FCT1,20251026,09:47:51,BA1WJ25297500494UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01462281
14,405,Non-PD,FCT1,20251026,09:48:05,BA1WJ25297500493UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01439684
15,406,Non-PD,FCT1,20251026,09:48:22,BA1WJ25297500492UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01424145
16,671,Non-PD,FCT1,20251030,20:21:48,BA1WJ23243500743UPC3T-14F014-AC,FAIL,1.12 Test VUSB_type-C(ELoad2=5A)(V),0.210
17,1004,Non-PD,FCT1,20251113,15:24:35,BA1WJ25314502644PC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.02168163

[INFO] FCT2-PD 최초 FAIL 상세 (rows=709)

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,result,step_description,value
0,53,PD,FCT2,20251001,10:46:05,BA1WJ25274501252USJ8T-14F014-AE,FAIL,1.02_Test_USB2_error(Type-C_A_side),
1,54,PD,FCT2,20251001,10:46:32,BA1WJ25274501251USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
2,57,PD,FCT2,20251001,12:53:27,BA1WJ25274500295USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
3,60,PD,FCT2,20251001,20:22:57,BA1WJ24068500088SJ8T-14F014-AC,FAIL,1.02_Test_USB2_error(Type-C_A_side),
4,64,PD,FCT2,20251001,21:47:49,BA1WJ25274501399USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
5,65,PD,FCT2,20251001,21:52:56,BA1WJ25274502608USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
6,66,PD,FCT2,20251001,22:13:17,BA1WJ25274502673USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
7,112,PD,FCT2,20251002,08:35:29,BA1WJ25275502514USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
8,115,PD,FCT2,20251002,10:00:53,BA1WJ25275502674USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
9,118,PD,FCT2,20251002,10:35:46,BA1WJ25275503160USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
10,119,PD,FCT2,20251002,10:43:13,BA1WJ25275503450USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
11,120,PD,FCT2,20251002,10:52:00,BA1WJ25275503045USJ8T-14F014-AE,FAIL,1.20 Test VUSB_type-C(No-Load-A_side),0.026
12,121,PD,FCT2,20251002,11:36:40,BA1WJ25275503715USJ8T-14F014-AE,FAIL,1.06_Test_USB1_error(Type-A),
13,122,PD,FCT2,20251002,12:18:29,BA1WJ25275502297USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
14,123,PD,FCT2,20251002,12:29:52,BA1WJ25275501260USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
15,124,PD,FCT2,20251002,12:36:48,BA1WJ25275501972USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
16,125,PD,FCT2,20251002,12:50:17,BA1WJ25275502352USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
17,126,PD,FCT2,20251002,13:41:33,BA1WJ25275504386USJ8T-14F014-AE,FAIL,1.20 Test VUSB_type-C(No-Load-A_side),0.017
18,127,PD,FCT2,20251002,13:41:55,BA1WJ25275504384USJ8T-14F014-AE,FAIL,1.02_Test_USB2_error(Type-C_A_side),
19,128,PD,FCT2,20251002,13:42:17,BA1WJ25275504383USJ8T-14F014-AE,FAIL,1.02_Test_USB2_error(Type-C_A_side),

[INFO] FCT2-Non-PD 최초 FAIL 상세 (rows=21)

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,result,step_description,value
0,59,Non-PD,FCT2,20251001,20:21:30,BA1WJ23243500555UPC3T-14F014-AC,FAIL,1.05 Test DIM-GND(ohm),0.65
1,228,Non-PD,FCT2,20251010,17:32:17,BA1WJ25283500439PC3T-14F014-AC,FAIL,1.22 Test Carplay type-C,FAIL
2,260,Non-PD,FCT2,20251013,20:31:28,BA1WJ25286504107PC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
3,261,Non-PD,FCT2,20251013,23:06:50,BA1WJ25286505479PC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.02191815
4,323,Non-PD,FCT2,20251015,19:06:08,BA1WJ25288503462PC3T-14F014-AC,FAIL,1.22 Test Carplay type-C,FAIL
5,326,Non-PD,FCT2,20251015,20:32:19,BA1WJ25288500780PC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
6,327,Non-PD,FCT2,20251015,20:49:38,BA1WJ25288503055PC3T-14F014-AC,FAIL,1.24 Test USB2 error,
7,329,Non-PD,FCT2,20251015,23:21:56,BA1WJ25288500162PC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
8,332,Non-PD,FCT2,20251016,09:26:03,BA1WJ25288500683UPC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
9,460,Non-PD,FCT2,20251026,09:43:17,BA1WJ25297500481UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01475260
10,461,Non-PD,FCT2,20251026,09:45:38,BA1WJ25297500486UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01439993
11,462,Non-PD,FCT2,20251026,09:46:08,BA1WJ25297500484UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01431604
12,463,Non-PD,FCT2,20251026,09:46:25,BA1WJ25297500483UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01447648
13,464,Non-PD,FCT2,20251026,09:49:59,BA1WJ25297500491UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01469087
14,465,Non-PD,FCT2,20251026,09:50:44,BA1WJ25297500489UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01441798
15,602,Non-PD,FCT2,20251028,21:55:39,BA1WJ25301502926PC3T-14F014-AC,FAIL,1.23 Test Carplay usb,FAIL
16,606,Non-PD,FCT2,20251028,21:58:24,BA1WJ25301502931PC3T-14F014-AC,FAIL,1.23 Test Carplay usb,FAIL
17,746,Non-PD,FCT2,20251030,20:21:58,BA1WJ23228500512N1WT-14F014-AC,FAIL,1.12 Test VUSB_type-C(ELoad2=5A)(V),0.161
18,1592,Non-PD,FCT2,20251113,15:50:03,BA1WJ25314502977PC3T-14F014-AC,FAIL,1.16 Test Check CC1 level(V),1.50
19,1598,Non-PD,FCT2,20251113,16:37:48,BA1WJ25314501990PC3T-14F014-AC,FAIL,1.00 Test RGUSB_MiniB(ohm),6.03

[INFO] FCT3-PD 최초 FAIL 상세 (rows=275)

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,result,step_description,value
0,30,PD,FCT3,20251001,11:18:43,BA1WJ25274501184USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
1,32,PD,FCT3,20251001,16:31:17,BA1WJ25274500165USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
2,33,PD,FCT3,20251001,16:33:10,BA1WJ25274500194USJ8T-14F014-AE,FAIL,1.06_Test_USB1_error(Type-A),
3,34,PD,FCT3,20251001,17:10:28,BA1WJ25274500004USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
4,35,PD,FCT3,20251001,19:15:27,BA1WJ25274501033USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
5,37,PD,FCT3,20251001,20:23:36,BA1WJ24068500081SJ8T-14F014-AC,FAIL,1.02_Test_USB2_error(Type-C_A_side),
6,40,PD,FCT3,20251001,21:06:07,BA1WJ25274501749USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
7,41,PD,FCT3,20251001,21:12:02,BA1WJ25274501772USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
8,42,PD,FCT3,20251001,21:23:44,BA1WJ25274501677USJ8T-14F014-AE,FAIL,1.06_Test_USB1_error(Type-A),
9,43,PD,FCT3,20251001,21:55:18,BA1WJ25274500377USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
10,44,PD,FCT3,20251001,22:44:56,BA1WJ25274502687USJ8T-14F014-AE,FAIL,1.02_Test_USB2_error(Type-C_A_side),
11,56,PD,FCT3,20251002,09:57:56,BA1WJ25275502990USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
12,57,PD,FCT3,20251002,10:13:39,BA1WJ25275502503USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
13,60,PD,FCT3,20251002,10:26:25,BA1WJ25275502707USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
14,61,PD,FCT3,20251002,10:56:37,BA1WJ25275503261USJ8T-14F014-AE,FAIL,1.10 Test Boston Firmware Version,
15,64,PD,FCT3,20251002,13:43:28,BA1WJ25275504238USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
16,67,PD,FCT3,20251002,17:20:26,BA1WJ25275505692USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
17,68,PD,FCT3,20251002,17:58:28,BA1WJ25275506004USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
18,69,PD,FCT3,20251002,18:34:01,BA1WJ25275505919USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
19,70,PD,FCT3,20251002,19:09:21,BA1WJ25275504689USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4

[INFO] FCT3-Non-PD 최초 FAIL 상세 (rows=19)

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,result,step_description,value
0,36,Non-PD,FCT3,20251001,20:22:10,BA1WJ23243500548UPC3T-14F014-AC,FAIL,1.05 Test DIM-GND(ohm),0.64
1,105,Non-PD,FCT3,20251010,15:37:47,BA1WJ25283500250PC3T-14F014-AC,FAIL,1.22 Test Carplay type-C,FAIL
2,106,Non-PD,FCT3,20251010,19:57:17,BA1WJ25283502852PC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
3,132,Non-PD,FCT3,20251013,10:42:38,BA1WJ25284501350PC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
4,133,Non-PD,FCT3,20251013,19:18:59,BA1WJ25286503638PC3T-14F014-AC,FAIL,1.24 Test USB2 error,
5,134,Non-PD,FCT3,20251013,22:55:11,BA1WJ25286505159PC3T-14F014-AC,FAIL,1.22 Test Carplay type-C,FAIL
6,201,Non-PD,FCT3,20251015,20:46:13,BA1WJ25288501048PC3T-14F014-AC,FAIL,1.24 Test USB2 error,
7,202,Non-PD,FCT3,20251015,20:50:47,BA1WJ25288500784PC3T-14F014-AC,FAIL,1.12 Test VUSB_type-C(ELoad2=5A)(V),0.009
8,203,Non-PD,FCT3,20251015,20:51:15,BA1WJ25288500796PC3T-14F014-AC,FAIL,1.12 Test VUSB_type-C(ELoad2=5A)(V),0.000
9,204,Non-PD,FCT3,20251015,20:51:44,BA1WJ25288500794PC3T-14F014-AC,FAIL,1.12 Test VUSB_type-C(ELoad2=5A)(V),0.000
10,205,Non-PD,FCT3,20251015,21:08:41,BA1WJ25288500828PC3T-14F014-AC,FAIL,1.12 Test VUSB_type-C(ELoad2=5A)(V),0.000
11,206,Non-PD,FCT3,20251015,21:09:07,BA1WJ25288500826PC3T-14F014-AC,FAIL,1.12 Test VUSB_type-C(ELoad2=5A)(V),0.000
12,350,Non-PD,FCT3,20251026,10:17:06,BA1WJ25297500502UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01448861
13,351,Non-PD,FCT3,20251026,10:18:02,BA1WJ25297500498UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01448142
14,352,Non-PD,FCT3,20251026,10:20:46,BA1WJ25297500505UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01443665
15,353,Non-PD,FCT3,20251026,10:21:02,BA1WJ25297500504UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01433841
16,354,Non-PD,FCT3,20251026,10:24:26,BA1WJ25297500503UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01464395
17,355,Non-PD,FCT3,20251026,13:13:39,BA1WJ25296501859UPC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
18,570,Non-PD,FCT3,20251030,20:22:41,BA1WJ24085501579N1WT-14F014-AC,FAIL,1.12 Test VUSB_type-C(ELoad2=5A)(V),0.040

[INFO] FCT4-PD 최초 FAIL 상세 (rows=358)

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,result,step_description,value
0,25,PD,FCT4,20251001,08:34:05,BA1WJ25273504652SJ8T-14F014-AE,FAIL,1.34_Test_VUSB_Type-C_A(ELoad2=1.35A)vol,4.987
1,26,PD,FCT4,20251001,08:51:58,BA1WJ25273504600SJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
2,27,PD,FCT4,20251001,10:01:43,BA1WJ25274500966USJ8T-14F014-AE,FAIL,1.01 Test Input Voltage(V),14.51
3,28,PD,FCT4,20251001,12:46:00,BA1WJ25274500085USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
4,29,PD,FCT4,20251001,13:08:23,BA1WJ25274500092USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
5,30,PD,FCT4,20251001,13:16:25,BA1WJ25274500262USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
6,31,PD,FCT4,20251001,17:15:42,BA1WJ25274500015USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
7,32,PD,FCT4,20251001,19:07:02,BA1WJ25274500123USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
8,33,PD,FCT4,20251001,19:59:53,BA1WJ25274501565USJ8T-14F014-AE,FAIL,1.12_Test_Carplay_Type-C(B_side),FAIL
9,35,PD,FCT4,20251001,20:23:59,BA1WJ24068500124SJ8T-14F014-AC,FAIL,1.17 Test DIM-GND(ohm),0.91
10,38,PD,FCT4,20251001,21:26:29,BA1WJ25274501682USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
11,108,PD,FCT4,20251002,10:27:12,BA1WJ25275502704USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
12,109,PD,FCT4,20251002,12:50:23,BA1WJ25275500167USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
13,113,PD,FCT4,20251002,17:04:20,BA1WJ25275504288USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
14,115,PD,FCT4,20251002,17:54:27,BA1WJ25275505989USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
15,116,PD,FCT4,20251002,17:56:31,BA1WJ25275505997USJ8T-14F014-AE,FAIL,1.36 Test iqz(uA),0.06981083
16,117,PD,FCT4,20251002,18:20:25,BA1WJ25275505962USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
17,118,PD,FCT4,20251002,18:54:27,BA1WJ25275504642USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
18,119,PD,FCT4,20251002,19:07:57,BA1WJ25275504338USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4
19,120,PD,FCT4,20251002,21:03:50,BA1WJ25275506970USJ8T-14F014-AE,FAIL,1.14 Profile Count Check,4

[INFO] FCT4-Non-PD 최초 FAIL 상세 (rows=12)

,fail_estimation_group,remark,station,end_day,end_time,barcode_information,result,step_description,value
0,34,Non-PD,FCT4,20251001,20:22:26,BA1WJ23243500750UPC3T-14F014-AC,FAIL,1.05 Test DIM-GND(ohm),0.70
1,139,Non-PD,FCT4,20251010,17:52:33,BA1WJ25283500422PC3T-14F014-AC,FAIL,1.22 Test Carplay type-C,FAIL
2,143,Non-PD,FCT4,20251010,23:34:35,BA1WJ25283501247UPC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
3,289,Non-PD,FCT4,20251015,21:03:07,BA1WJ25288500747PC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
4,435,Non-PD,FCT4,20251026,08:41:01,BA1WJ25297500964UPC3T-14F014-AC,FAIL,1.03 Test Power-NC_Line(ohm),0.53
5,438,Non-PD,FCT4,20251026,10:18:31,BA1WJ25297500496UPC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.01425860
6,439,Non-PD,FCT4,20251026,15:08:21,BA1WJ25296501125UPC3T-14F014-AC,FAIL,1.24 Test USB2 error,
7,442,Non-PD,FCT4,20251026,21:47:19,BA1WJ25297502722UPC3T-14F014-AC,FAIL,1.06 Test Input Voltage(V),16.52
8,648,Non-PD,FCT4,20251030,20:22:50,BA1WJ23243500760UPC3T-14F014-AC,FAIL,1.12 Test VUSB_type-C(ELoad2=5A)(V),0.108
9,662,Non-PD,FCT4,20251031,08:59:24,BA1WJ25302503061UPC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,
10,842,Non-PD,FCT4,20251113,17:56:28,BA1WJ25314502644PC3T-14F014-AC,FAIL,1.07 Test Idle Current(mA),0.02164971
11,843,Non-PD,FCT4,20251113,18:10:30,BA1WJ25314501297PC3T-14F014-AC,FAIL,1.08 Test Boston Firmware Version,

In [39]:
# ============================================
# [11] 10번 FAIL 상세 DataFrame들을 PostgreSQL에 저장
#
# 스키마 : e3_fct_dataframe
#
# 매핑:
#  FCT1-PD     → FAIL_testitem_fct1_pd
#  FCT1-Non-PD → FAIL_testitem_fct1_non-pd
#  FCT2-PD     → FAIL_testitem_fct2_pd
#  FCT2-Non-PD → FAIL_testitem_fct2_non-pd
#  FCT3-PD     → FAIL_testitem_fct3_pd
#  FCT3-Non-PD → FAIL_testitem_fct3_non-pd
#  FCT4-PD     → FAIL_testitem_fct4_pd
#  FCT4-Non-PD → FAIL_testitem_fct4_non-pd
# ============================================

from sqlalchemy import text

engine = get_engine()
schema_name = "e3_fct_dataframe"

# 10번에서 만든 DF들이 있다고 가정:
# df10_FCT1_PD_FAIL, df10_FCT1_NonPD_FAIL, ...
save_map_11 = {
    "FAIL_testitem_fct1_pd":      df10_FCT1_PD_FAIL,
    "FAIL_testitem_fct1_non_pd":  df10_FCT1_NonPD_FAIL,
    "FAIL_testitem_fct2_pd":      df10_FCT2_PD_FAIL,
    "FAIL_testitem_fct2_non_pd":  df10_FCT2_NonPD_FAIL,
    "FAIL_testitem_fct3_pd":      df10_FCT3_PD_FAIL,
    "FAIL_testitem_fct3_non_pd":  df10_FCT3_NonPD_FAIL,
    "FAIL_testitem_fct4_pd":      df10_FCT4_PD_FAIL,
    "FAIL_testitem_fct4_non_pd":  df10_FCT4_NonPD_FAIL,
}

# 스키마 없으면 생성
with engine.connect() as conn:
    conn.execute(text(f"CREATE SCHEMA IF NOT EXISTS {schema_name};"))
    conn.commit()

for table_name, df_data in save_map_11.items():
    print(f"\n[INFO] 저장 시작 → {schema_name}.{table_name}")
    if df_data is None or df_data.empty:
        print("[WARN] DataFrame이 비어 있음 → 저장 생략")
        continue

    df_data.to_sql(
        name=table_name,
        con=engine,
        schema=schema_name,
        if_exists="replace",  # 기존 테이블 있으면 덮어쓰기
        index=False,
    )

    print(f"[OK] 저장 완료: {schema_name}.{table_name} (rows={len(df_data)})")

print("\n[INFO] 11번 전체 완료!")

[INFO] Connection String: postgresql+psycopg2://postgres:leejangwoo1%21@localhost:5432/postgres

[INFO] 저장 시작 → e3_fct_dataframe.FAIL_testitem_fct1_pd
[OK] 저장 완료: e3_fct_dataframe.FAIL_testitem_fct1_pd (rows=437)

[INFO] 저장 시작 → e3_fct_dataframe.FAIL_testitem_fct1_non_pd
[OK] 저장 완료: e3_fct_dataframe.FAIL_testitem_fct1_non_pd (rows=18)

[INFO] 저장 시작 → e3_fct_dataframe.FAIL_testitem_fct2_pd
[OK] 저장 완료: e3_fct_dataframe.FAIL_testitem_fct2_pd (rows=709)

[INFO] 저장 시작 → e3_fct_dataframe.FAIL_testitem_fct2_non_pd
[OK] 저장 완료: e3_fct_dataframe.FAIL_testitem_fct2_non_pd (rows=21)

[INFO] 저장 시작 → e3_fct_dataframe.FAIL_testitem_fct3_pd
[OK] 저장 완료: e3_fct_dataframe.FAIL_testitem_fct3_pd (rows=275)

[INFO] 저장 시작 → e3_fct_dataframe.FAIL_testitem_fct3_non_pd
[OK] 저장 완료: e3_fct_dataframe.FAIL_testitem_fct3_non_pd (rows=19)

[INFO] 저장 시작 → e3_fct_dataframe.FAIL_testitem_fct4_pd
[OK] 저장 완료: e3_fct_dataframe.FAIL_testitem_fct4_pd (rows=358)

[INFO] 저장 시작 → e3_fct_dataframe.FAIL_testitem_fct4_non_pd
[OK] 저장 완료: e3_fct_dataframe.FAIL_testitem_fct4_non_pd (rows=12)

[INFO] 11번 전체 완료!